// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (provider_id, environment_id, actor_type, actor_id, action, target_type, target_id, metadata, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, provider_id, environment_id, actor_type, actor_id, action, target_type, target_id, metadata, request_id, created_at
`

type InsertAuditEventParams struct {
	ProviderID    uuid.NullUUID `json:"provider_id"`
	EnvironmentID uuid.NullUUID `json:"environment_id"`
	ActorType     string        `json:"actor_type"`
	ActorID       string        `json:"actor_id"`
	Action        string        `json:"action"`
	TargetType    pgtype.Text   `json:"target_type"`
	TargetID      pgtype.Text   `json:"target_id"`
	Metadata      []byte        `json:"metadata"`
	RequestID     pgtype.Text   `json:"request_id"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.RequestID,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEventsByProvider = `-- name: ListAuditEventsByProvider :many
SELECT id, provider_id, environment_id, actor_type, actor_id, action, target_type, target_id, metadata, request_id, created_at FROM audit_events
WHERE provider_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAuditEventsByProviderParams struct {
	ProviderID uuid.NullUUID `json:"provider_id"`
	Limit      int32         `json:"limit"`
}

func (q *Queries) ListAuditEventsByProvider(ctx context.Context, arg ListAuditEventsByProviderParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByProvider, arg.ProviderID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
