// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createAuthConfig = `-- name: CreateAuthConfig :one
INSERT INTO provider_auth_configs (
    provider_id, environment_id,
    zitadel_project_id, zitadel_app_id, zitadel_client_id, zitadel_client_secret
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider_id, environment_id, zitadel_project_id, zitadel_app_id, zitadel_client_id, zitadel_client_secret, enabled, created_at, updated_at
`

type CreateAuthConfigParams struct {
	ProviderID          uuid.UUID `json:"provider_id"`
	EnvironmentID       uuid.UUID `json:"environment_id"`
	ZitadelProjectID    string    `json:"zitadel_project_id"`
	ZitadelAppID        string    `json:"zitadel_app_id"`
	ZitadelClientID     string    `json:"zitadel_client_id"`
	ZitadelClientSecret string    `json:"zitadel_client_secret"`
}

func (q *Queries) CreateAuthConfig(ctx context.Context, arg CreateAuthConfigParams) (ProviderAuthConfig, error) {
	row := q.db.QueryRow(ctx, createAuthConfig,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.ZitadelProjectID,
		arg.ZitadelAppID,
		arg.ZitadelClientID,
		arg.ZitadelClientSecret,
	)
	var i ProviderAuthConfig
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ZitadelProjectID,
		&i.ZitadelAppID,
		&i.ZitadelClientID,
		&i.ZitadelClientSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthConfig = `-- name: DeleteAuthConfig :exec
DELETE FROM provider_auth_configs
WHERE provider_id = $1 AND environment_id = $2
`

type DeleteAuthConfigParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) DeleteAuthConfig(ctx context.Context, arg DeleteAuthConfigParams) error {
	_, err := q.db.Exec(ctx, deleteAuthConfig, arg.ProviderID, arg.EnvironmentID)
	return err
}

const getAuthConfigByTenant = `-- name: GetAuthConfigByTenant :one
SELECT id, provider_id, environment_id, zitadel_project_id, zitadel_app_id, zitadel_client_id, zitadel_client_secret, enabled, created_at, updated_at FROM provider_auth_configs
WHERE provider_id = $1 AND environment_id = $2
`

type GetAuthConfigByTenantParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) GetAuthConfigByTenant(ctx context.Context, arg GetAuthConfigByTenantParams) (ProviderAuthConfig, error) {
	row := q.db.QueryRow(ctx, getAuthConfigByTenant, arg.ProviderID, arg.EnvironmentID)
	var i ProviderAuthConfig
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ZitadelProjectID,
		&i.ZitadelAppID,
		&i.ZitadelClientID,
		&i.ZitadelClientSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
