// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth_vault.sql

package storegen

import (
	"context"
	"time"
)

const createAuthVault = `-- name: CreateAuthVault :one

INSERT INTO auth_session_vault (
    id, user_sub, email, name, roles, workspace_id, env,
    access_token, refresh_token, token_exp, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_sub, email, name, roles, workspace_id, env, access_token, refresh_token, token_exp, created_at, expires_at
`

type CreateAuthVaultParams struct {
	ID           string    `json:"id"`
	UserSub      string    `json:"user_sub"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	Roles        []byte    `json:"roles"`
	WorkspaceID  string    `json:"workspace_id"`
	Env          string    `json:"env"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	TokenExp     int64     `json:"token_exp"`
	ExpiresAt    time.Time `json:"expires_at"`
}

// Server-side OIDC token vault for vLogBin web sessions.
func (q *Queries) CreateAuthVault(ctx context.Context, arg CreateAuthVaultParams) (AuthSessionVault, error) {
	row := q.db.QueryRow(ctx, createAuthVault,
		arg.ID,
		arg.UserSub,
		arg.Email,
		arg.Name,
		arg.Roles,
		arg.WorkspaceID,
		arg.Env,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExp,
		arg.ExpiresAt,
	)
	var i AuthSessionVault
	err := row.Scan(
		&i.ID,
		&i.UserSub,
		&i.Email,
		&i.Name,
		&i.Roles,
		&i.WorkspaceID,
		&i.Env,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExp,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAuthVault = `-- name: DeleteAuthVault :exec
DELETE FROM auth_session_vault WHERE id = $1
`

func (q *Queries) DeleteAuthVault(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAuthVault, id)
	return err
}

const deleteExpiredAuthVaults = `-- name: DeleteExpiredAuthVaults :execrows
DELETE FROM auth_session_vault WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredAuthVaults(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthVaults)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthVault = `-- name: GetAuthVault :one
SELECT id, user_sub, email, name, roles, workspace_id, env, access_token, refresh_token, token_exp, created_at, expires_at
FROM auth_session_vault
WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetAuthVault(ctx context.Context, id string) (AuthSessionVault, error) {
	row := q.db.QueryRow(ctx, getAuthVault, id)
	var i AuthSessionVault
	err := row.Scan(
		&i.ID,
		&i.UserSub,
		&i.Email,
		&i.Name,
		&i.Roles,
		&i.WorkspaceID,
		&i.Env,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExp,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
