// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: billing.sql

package storegen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkUsageInvoiced = `-- name: CheckUsageInvoiced :one
SELECT EXISTS(
    SELECT 1 FROM invoice_lines
    WHERE event_transaction_id = $1
    AND provider_id = $2
    AND environment_id = $3
) AS invoiced
`

type CheckUsageInvoicedParams struct {
	EventTransactionID pgtype.Text `json:"event_transaction_id"`
	ProviderID         uuid.UUID   `json:"provider_id"`
	EnvironmentID      uuid.UUID   `json:"environment_id"`
}

// Returns true if any invoice line references the given transaction_id,
// meaning the usage has been included in an invoice and cannot be directly
// reversed (Testing #6 post-invoice reversal).
func (q *Queries) CheckUsageInvoiced(ctx context.Context, arg CheckUsageInvoicedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsageInvoiced, arg.EventTransactionID, arg.ProviderID, arg.EnvironmentID)
	var invoiced bool
	err := row.Scan(&invoiced)
	return invoiced, err
}

const deleteEntitlementOverride = `-- name: DeleteEntitlementOverride :execrows
DELETE FROM entitlement_overrides WHERE subscription_id = $1 AND key = $2
`

type DeleteEntitlementOverrideParams struct {
	SubscriptionID uuid.UUID `json:"subscription_id"`
	Key            string    `json:"key"`
}

func (q *Queries) DeleteEntitlementOverride(ctx context.Context, arg DeleteEntitlementOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntitlementOverride, arg.SubscriptionID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGrantsByVersion = `-- name: DeleteGrantsByVersion :exec
DELETE FROM entitlement_grants WHERE catalog_version_id = $1
`

func (q *Queries) DeleteGrantsByVersion(ctx context.Context, catalogVersionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGrantsByVersion, catalogVersionID)
	return err
}

const deleteInvoiceLinesByInvoice = `-- name: DeleteInvoiceLinesByInvoice :exec
DELETE FROM invoice_lines WHERE invoice_id = $1 AND provider_id = $2 AND environment_id = $3
`

type DeleteInvoiceLinesByInvoiceParams struct {
	InvoiceID     uuid.UUID `json:"invoice_id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) DeleteInvoiceLinesByInvoice(ctx context.Context, arg DeleteInvoiceLinesByInvoiceParams) error {
	_, err := q.db.Exec(ctx, deleteInvoiceLinesByInvoice, arg.InvoiceID, arg.ProviderID, arg.EnvironmentID)
	return err
}

const deleteMetricsByVersion = `-- name: DeleteMetricsByVersion :exec
DELETE FROM metrics WHERE catalog_version_id = $1
`

func (q *Queries) DeleteMetricsByVersion(ctx context.Context, catalogVersionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMetricsByVersion, catalogVersionID)
	return err
}

const deletePlansByVersion = `-- name: DeletePlansByVersion :exec
DELETE FROM plans WHERE catalog_version_id = $1
`

func (q *Queries) DeletePlansByVersion(ctx context.Context, catalogVersionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlansByVersion, catalogVersionID)
	return err
}

const deletePricesByVersion = `-- name: DeletePricesByVersion :exec
DELETE FROM prices WHERE catalog_version_id = $1
`

func (q *Queries) DeletePricesByVersion(ctx context.Context, catalogVersionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePricesByVersion, catalogVersionID)
	return err
}

const getActiveSubscriptionByCustomer = `-- name: GetActiveSubscriptionByCustomer :one
SELECT id, provider_id, environment_id, external_id, customer_account_id, catalog_version_id, plan_id, status, started_at, terminated_at FROM subscriptions
WHERE customer_account_id = $1 AND status = 'active'
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscriptionByCustomer(ctx context.Context, customerAccountID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByCustomer, customerAccountID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.CustomerAccountID,
		&i.CatalogVersionID,
		&i.PlanID,
		&i.Status,
		&i.StartedAt,
		&i.TerminatedAt,
	)
	return i, err
}

const getCatalogVersionByID = `-- name: GetCatalogVersionByID :one
SELECT id, provider_id, environment_id, version, state, created_at, validated_at, published_at, retired_at FROM catalog_versions WHERE id = $1
`

func (q *Queries) GetCatalogVersionByID(ctx context.Context, id uuid.UUID) (CatalogVersion, error) {
	row := q.db.QueryRow(ctx, getCatalogVersionByID, id)
	var i CatalogVersion
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Version,
		&i.State,
		&i.CreatedAt,
		&i.ValidatedAt,
		&i.PublishedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getCustomerByExternalID = `-- name: GetCustomerByExternalID :one
SELECT id, provider_id, environment_id, external_id, account_type, display_name, created_at FROM customer_accounts
WHERE provider_id = $1 AND environment_id = $2 AND external_id = $3
`

type GetCustomerByExternalIDParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ExternalID    string    `json:"external_id"`
}

func (q *Queries) GetCustomerByExternalID(ctx context.Context, arg GetCustomerByExternalIDParams) (CustomerAccount, error) {
	row := q.db.QueryRow(ctx, getCustomerByExternalID, arg.ProviderID, arg.EnvironmentID, arg.ExternalID)
	var i CustomerAccount
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.AccountType,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, provider_id, environment_id, external_id, account_type, display_name, created_at FROM customer_accounts WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id uuid.UUID) (CustomerAccount, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i CustomerAccount
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.AccountType,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, provider_id, environment_id, lago_id, number, customer_account_id, subscription_id, catalog_version_id, issuing_date, invoice_type, status, payment_status, currency, fees_amount_cents, coupons_amount_cents, credit_notes_amount_cents, sub_total_excluding_taxes_amount_cents, taxes_amount_cents, sub_total_including_taxes_amount_cents, total_amount_cents, file_url, web_url, lago_created_at, synced_at, finalized_at, voided_at, created_at, updated_at FROM invoices WHERE id = $1 AND provider_id = $2 AND environment_id = $3
`

type GetInvoiceByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, arg GetInvoiceByIDParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, arg.ID, arg.ProviderID, arg.EnvironmentID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.LagoID,
		&i.Number,
		&i.CustomerAccountID,
		&i.SubscriptionID,
		&i.CatalogVersionID,
		&i.IssuingDate,
		&i.InvoiceType,
		&i.Status,
		&i.PaymentStatus,
		&i.Currency,
		&i.FeesAmountCents,
		&i.CouponsAmountCents,
		&i.CreditNotesAmountCents,
		&i.SubTotalExcludingTaxesAmountCents,
		&i.TaxesAmountCents,
		&i.SubTotalIncludingTaxesAmountCents,
		&i.TotalAmountCents,
		&i.FileUrl,
		&i.WebUrl,
		&i.LagoCreatedAt,
		&i.SyncedAt,
		&i.FinalizedAt,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceStatusByLagoID = `-- name: GetInvoiceStatusByLagoID :one
SELECT id, status FROM invoices WHERE provider_id = $1 AND environment_id = $2 AND lago_id = $3
`

type GetInvoiceStatusByLagoIDParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	LagoID        string    `json:"lago_id"`
}

type GetInvoiceStatusByLagoIDRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) GetInvoiceStatusByLagoID(ctx context.Context, arg GetInvoiceStatusByLagoIDParams) (GetInvoiceStatusByLagoIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceStatusByLagoID, arg.ProviderID, arg.EnvironmentID, arg.LagoID)
	var i GetInvoiceStatusByLagoIDRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getMetricByVersionAndCode = `-- name: GetMetricByVersionAndCode :one
SELECT id, catalog_version_id, provider_id, environment_id, code, name, aggregation_type, field_name, billable FROM metrics WHERE catalog_version_id = $1 AND code = $2
`

type GetMetricByVersionAndCodeParams struct {
	CatalogVersionID uuid.UUID `json:"catalog_version_id"`
	Code             string    `json:"code"`
}

func (q *Queries) GetMetricByVersionAndCode(ctx context.Context, arg GetMetricByVersionAndCodeParams) (Metric, error) {
	row := q.db.QueryRow(ctx, getMetricByVersionAndCode, arg.CatalogVersionID, arg.Code)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.CatalogVersionID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Code,
		&i.Name,
		&i.AggregationType,
		&i.FieldName,
		&i.Billable,
	)
	return i, err
}

const getPlanByVersionAndCode = `-- name: GetPlanByVersionAndCode :one
SELECT id, catalog_version_id, provider_id, environment_id, code, name, interval, currency FROM plans WHERE catalog_version_id = $1 AND code = $2
`

type GetPlanByVersionAndCodeParams struct {
	CatalogVersionID uuid.UUID `json:"catalog_version_id"`
	Code             string    `json:"code"`
}

func (q *Queries) GetPlanByVersionAndCode(ctx context.Context, arg GetPlanByVersionAndCodeParams) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByVersionAndCode, arg.CatalogVersionID, arg.Code)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.CatalogVersionID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Code,
		&i.Name,
		&i.Interval,
		&i.Currency,
	)
	return i, err
}

const getReversalForUsageEvent = `-- name: GetReversalForUsageEvent :one
SELECT id, provider_id, environment_id, transaction_id, kind, metric_code, customer_account_id, subscription_id, event_timestamp, properties, payload_hash, reverses_id, reason, created_at FROM usage_events WHERE reverses_id = $1
`

func (q *Queries) GetReversalForUsageEvent(ctx context.Context, reversesID uuid.NullUUID) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, getReversalForUsageEvent, reversesID)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.TransactionID,
		&i.Kind,
		&i.MetricCode,
		&i.CustomerAccountID,
		&i.SubscriptionID,
		&i.EventTimestamp,
		&i.Properties,
		&i.PayloadHash,
		&i.ReversesID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByExternalID = `-- name: GetSubscriptionByExternalID :one
SELECT id, provider_id, environment_id, external_id, customer_account_id, catalog_version_id, plan_id, status, started_at, terminated_at FROM subscriptions
WHERE provider_id = $1 AND environment_id = $2 AND external_id = $3
`

type GetSubscriptionByExternalIDParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ExternalID    string    `json:"external_id"`
}

func (q *Queries) GetSubscriptionByExternalID(ctx context.Context, arg GetSubscriptionByExternalIDParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByExternalID, arg.ProviderID, arg.EnvironmentID, arg.ExternalID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.CustomerAccountID,
		&i.CatalogVersionID,
		&i.PlanID,
		&i.Status,
		&i.StartedAt,
		&i.TerminatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, provider_id, environment_id, external_id, customer_account_id, catalog_version_id, plan_id, status, started_at, terminated_at FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.CustomerAccountID,
		&i.CatalogVersionID,
		&i.PlanID,
		&i.Status,
		&i.StartedAt,
		&i.TerminatedAt,
	)
	return i, err
}

const getUsageEventByTransactionID = `-- name: GetUsageEventByTransactionID :one
SELECT id, provider_id, environment_id, transaction_id, kind, metric_code, customer_account_id, subscription_id, event_timestamp, properties, payload_hash, reverses_id, reason, created_at FROM usage_events
WHERE provider_id = $1 AND environment_id = $2 AND transaction_id = $3
`

type GetUsageEventByTransactionIDParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	TransactionID string    `json:"transaction_id"`
}

func (q *Queries) GetUsageEventByTransactionID(ctx context.Context, arg GetUsageEventByTransactionIDParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, getUsageEventByTransactionID, arg.ProviderID, arg.EnvironmentID, arg.TransactionID)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.TransactionID,
		&i.Kind,
		&i.MetricCode,
		&i.CustomerAccountID,
		&i.SubscriptionID,
		&i.EventTimestamp,
		&i.Properties,
		&i.PayloadHash,
		&i.ReversesID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertCatalogVersion = `-- name: InsertCatalogVersion :one
INSERT INTO catalog_versions (provider_id, environment_id, version)
VALUES ($1, $2, $3)
RETURNING id, provider_id, environment_id, version, state, created_at, validated_at, published_at, retired_at
`

type InsertCatalogVersionParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Version       int32     `json:"version"`
}

func (q *Queries) InsertCatalogVersion(ctx context.Context, arg InsertCatalogVersionParams) (CatalogVersion, error) {
	row := q.db.QueryRow(ctx, insertCatalogVersion, arg.ProviderID, arg.EnvironmentID, arg.Version)
	var i CatalogVersion
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Version,
		&i.State,
		&i.CreatedAt,
		&i.ValidatedAt,
		&i.PublishedAt,
		&i.RetiredAt,
	)
	return i, err
}

const insertCustomerAccount = `-- name: InsertCustomerAccount :one

INSERT INTO customer_accounts (provider_id, environment_id, external_id, account_type, display_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider_id, environment_id, external_id, account_type, display_name, created_at
`

type InsertCustomerAccountParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ExternalID    string    `json:"external_id"`
	AccountType   string    `json:"account_type"`
	DisplayName   string    `json:"display_name"`
}

// ---- customer accounts ----
func (q *Queries) InsertCustomerAccount(ctx context.Context, arg InsertCustomerAccountParams) (CustomerAccount, error) {
	row := q.db.QueryRow(ctx, insertCustomerAccount,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.ExternalID,
		arg.AccountType,
		arg.DisplayName,
	)
	var i CustomerAccount
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.AccountType,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const insertEntitlementGrant = `-- name: InsertEntitlementGrant :one

INSERT INTO entitlement_grants (plan_id, catalog_version_id, provider_id, environment_id, key, value_type, value)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, plan_id, catalog_version_id, provider_id, environment_id, key, value_type, value
`

type InsertEntitlementGrantParams struct {
	PlanID           uuid.UUID `json:"plan_id"`
	CatalogVersionID uuid.UUID `json:"catalog_version_id"`
	ProviderID       uuid.UUID `json:"provider_id"`
	EnvironmentID    uuid.UUID `json:"environment_id"`
	Key              string    `json:"key"`
	ValueType        string    `json:"value_type"`
	Value            []byte    `json:"value"`
}

// ---- entitlement grants ----
func (q *Queries) InsertEntitlementGrant(ctx context.Context, arg InsertEntitlementGrantParams) (EntitlementGrant, error) {
	row := q.db.QueryRow(ctx, insertEntitlementGrant,
		arg.PlanID,
		arg.CatalogVersionID,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Key,
		arg.ValueType,
		arg.Value,
	)
	var i EntitlementGrant
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.CatalogVersionID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Key,
		&i.ValueType,
		&i.Value,
	)
	return i, err
}

const insertEntitlementSnapshot = `-- name: InsertEntitlementSnapshot :one

INSERT INTO entitlement_snapshots (provider_id, environment_id, customer_account_id, subscription_id, catalog_version_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider_id, environment_id, customer_account_id, subscription_id, catalog_version_id, payload, computed_at
`

type InsertEntitlementSnapshotParams struct {
	ProviderID        uuid.UUID `json:"provider_id"`
	EnvironmentID     uuid.UUID `json:"environment_id"`
	CustomerAccountID uuid.UUID `json:"customer_account_id"`
	SubscriptionID    uuid.UUID `json:"subscription_id"`
	CatalogVersionID  uuid.UUID `json:"catalog_version_id"`
	Payload           []byte    `json:"payload"`
}

// ---- entitlement snapshots ----
func (q *Queries) InsertEntitlementSnapshot(ctx context.Context, arg InsertEntitlementSnapshotParams) (EntitlementSnapshot, error) {
	row := q.db.QueryRow(ctx, insertEntitlementSnapshot,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.CustomerAccountID,
		arg.SubscriptionID,
		arg.CatalogVersionID,
		arg.Payload,
	)
	var i EntitlementSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.CustomerAccountID,
		&i.SubscriptionID,
		&i.CatalogVersionID,
		&i.Payload,
		&i.ComputedAt,
	)
	return i, err
}

const insertInvoiceLine = `-- name: InsertInvoiceLine :one
INSERT INTO invoice_lines (
    invoice_id, provider_id, environment_id, lago_fee_id,
    metric_code, item_type, item_name, units, precise_unit_amount,
    amount_cents, taxes_amount_cents, total_amount_cents, currency,
    event_transaction_id, from_date, to_date, metric_id, price_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, invoice_id, provider_id, environment_id, lago_fee_id, metric_code, item_type, item_name, units, precise_unit_amount, amount_cents, taxes_amount_cents, total_amount_cents, currency, event_transaction_id, from_date, to_date, created_at, metric_id, price_id
`

type InsertInvoiceLineParams struct {
	InvoiceID          uuid.UUID     `json:"invoice_id"`
	ProviderID         uuid.UUID     `json:"provider_id"`
	EnvironmentID      uuid.UUID     `json:"environment_id"`
	LagoFeeID          string        `json:"lago_fee_id"`
	MetricCode         string        `json:"metric_code"`
	ItemType           string        `json:"item_type"`
	ItemName           string        `json:"item_name"`
	Units              string        `json:"units"`
	PreciseUnitAmount  string        `json:"precise_unit_amount"`
	AmountCents        int64         `json:"amount_cents"`
	TaxesAmountCents   int64         `json:"taxes_amount_cents"`
	TotalAmountCents   int64         `json:"total_amount_cents"`
	Currency           string        `json:"currency"`
	EventTransactionID pgtype.Text   `json:"event_transaction_id"`
	FromDate           *time.Time    `json:"from_date"`
	ToDate             *time.Time    `json:"to_date"`
	MetricID           uuid.NullUUID `json:"metric_id"`
	PriceID            uuid.NullUUID `json:"price_id"`
}

func (q *Queries) InsertInvoiceLine(ctx context.Context, arg InsertInvoiceLineParams) (InvoiceLine, error) {
	row := q.db.QueryRow(ctx, insertInvoiceLine,
		arg.InvoiceID,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.LagoFeeID,
		arg.MetricCode,
		arg.ItemType,
		arg.ItemName,
		arg.Units,
		arg.PreciseUnitAmount,
		arg.AmountCents,
		arg.TaxesAmountCents,
		arg.TotalAmountCents,
		arg.Currency,
		arg.EventTransactionID,
		arg.FromDate,
		arg.ToDate,
		arg.MetricID,
		arg.PriceID,
	)
	var i InvoiceLine
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.LagoFeeID,
		&i.MetricCode,
		&i.ItemType,
		&i.ItemName,
		&i.Units,
		&i.PreciseUnitAmount,
		&i.AmountCents,
		&i.TaxesAmountCents,
		&i.TotalAmountCents,
		&i.Currency,
		&i.EventTransactionID,
		&i.FromDate,
		&i.ToDate,
		&i.CreatedAt,
		&i.MetricID,
		&i.PriceID,
	)
	return i, err
}

const insertMetric = `-- name: InsertMetric :one

INSERT INTO metrics (catalog_version_id, provider_id, environment_id, code, name, aggregation_type, field_name, billable)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, catalog_version_id, provider_id, environment_id, code, name, aggregation_type, field_name, billable
`

type InsertMetricParams struct {
	CatalogVersionID uuid.UUID   `json:"catalog_version_id"`
	ProviderID       uuid.UUID   `json:"provider_id"`
	EnvironmentID    uuid.UUID   `json:"environment_id"`
	Code             string      `json:"code"`
	Name             string      `json:"name"`
	AggregationType  string      `json:"aggregation_type"`
	FieldName        pgtype.Text `json:"field_name"`
	Billable         bool        `json:"billable"`
}

// ---- metrics ----
func (q *Queries) InsertMetric(ctx context.Context, arg InsertMetricParams) (Metric, error) {
	row := q.db.QueryRow(ctx, insertMetric,
		arg.CatalogVersionID,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Code,
		arg.Name,
		arg.AggregationType,
		arg.FieldName,
		arg.Billable,
	)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.CatalogVersionID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Code,
		&i.Name,
		&i.AggregationType,
		&i.FieldName,
		&i.Billable,
	)
	return i, err
}

const insertPlan = `-- name: InsertPlan :one

INSERT INTO plans (catalog_version_id, provider_id, environment_id, code, name, interval, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, catalog_version_id, provider_id, environment_id, code, name, interval, currency
`

type InsertPlanParams struct {
	CatalogVersionID uuid.UUID `json:"catalog_version_id"`
	ProviderID       uuid.UUID `json:"provider_id"`
	EnvironmentID    uuid.UUID `json:"environment_id"`
	Code             string    `json:"code"`
	Name             string    `json:"name"`
	Interval         string    `json:"interval"`
	Currency         string    `json:"currency"`
}

// ---- plans ----
func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, insertPlan,
		arg.CatalogVersionID,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Code,
		arg.Name,
		arg.Interval,
		arg.Currency,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.CatalogVersionID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Code,
		&i.Name,
		&i.Interval,
		&i.Currency,
	)
	return i, err
}

const insertPrice = `-- name: InsertPrice :one

INSERT INTO prices (plan_id, catalog_version_id, provider_id, environment_id, metric_id, charge_model, properties)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, plan_id, catalog_version_id, provider_id, environment_id, metric_id, charge_model, properties
`

type InsertPriceParams struct {
	PlanID           uuid.UUID     `json:"plan_id"`
	CatalogVersionID uuid.UUID     `json:"catalog_version_id"`
	ProviderID       uuid.UUID     `json:"provider_id"`
	EnvironmentID    uuid.UUID     `json:"environment_id"`
	MetricID         uuid.NullUUID `json:"metric_id"`
	ChargeModel      string        `json:"charge_model"`
	Properties       []byte        `json:"properties"`
}

// ---- prices ----
func (q *Queries) InsertPrice(ctx context.Context, arg InsertPriceParams) (Price, error) {
	row := q.db.QueryRow(ctx, insertPrice,
		arg.PlanID,
		arg.CatalogVersionID,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.MetricID,
		arg.ChargeModel,
		arg.Properties,
	)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.CatalogVersionID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.MetricID,
		&i.ChargeModel,
		&i.Properties,
	)
	return i, err
}

const insertSubscription = `-- name: InsertSubscription :one

INSERT INTO subscriptions (provider_id, environment_id, external_id, customer_account_id, catalog_version_id, plan_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider_id, environment_id, external_id, customer_account_id, catalog_version_id, plan_id, status, started_at, terminated_at
`

type InsertSubscriptionParams struct {
	ProviderID        uuid.UUID `json:"provider_id"`
	EnvironmentID     uuid.UUID `json:"environment_id"`
	ExternalID        string    `json:"external_id"`
	CustomerAccountID uuid.UUID `json:"customer_account_id"`
	CatalogVersionID  uuid.UUID `json:"catalog_version_id"`
	PlanID            uuid.UUID `json:"plan_id"`
}

// ---- subscriptions ----
func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, insertSubscription,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.ExternalID,
		arg.CustomerAccountID,
		arg.CatalogVersionID,
		arg.PlanID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.CustomerAccountID,
		&i.CatalogVersionID,
		&i.PlanID,
		&i.Status,
		&i.StartedAt,
		&i.TerminatedAt,
	)
	return i, err
}

const insertUsageEvent = `-- name: InsertUsageEvent :one

INSERT INTO usage_events (provider_id, environment_id, transaction_id, kind, metric_code,
    customer_account_id, subscription_id, event_timestamp, properties, payload_hash, reverses_id, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, provider_id, environment_id, transaction_id, kind, metric_code, customer_account_id, subscription_id, event_timestamp, properties, payload_hash, reverses_id, reason, created_at
`

type InsertUsageEventParams struct {
	ProviderID        uuid.UUID     `json:"provider_id"`
	EnvironmentID     uuid.UUID     `json:"environment_id"`
	TransactionID     string        `json:"transaction_id"`
	Kind              string        `json:"kind"`
	MetricCode        string        `json:"metric_code"`
	CustomerAccountID uuid.UUID     `json:"customer_account_id"`
	SubscriptionID    uuid.UUID     `json:"subscription_id"`
	EventTimestamp    time.Time     `json:"event_timestamp"`
	Properties        []byte        `json:"properties"`
	PayloadHash       string        `json:"payload_hash"`
	ReversesID        uuid.NullUUID `json:"reverses_id"`
	Reason            pgtype.Text   `json:"reason"`
}

// ---- usage events ----
func (q *Queries) InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, insertUsageEvent,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.TransactionID,
		arg.Kind,
		arg.MetricCode,
		arg.CustomerAccountID,
		arg.SubscriptionID,
		arg.EventTimestamp,
		arg.Properties,
		arg.PayloadHash,
		arg.ReversesID,
		arg.Reason,
	)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.TransactionID,
		&i.Kind,
		&i.MetricCode,
		&i.CustomerAccountID,
		&i.SubscriptionID,
		&i.EventTimestamp,
		&i.Properties,
		&i.PayloadHash,
		&i.ReversesID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listCatalogVersionsByProvider = `-- name: ListCatalogVersionsByProvider :many

SELECT cv.id, cv.environment_id, e.kind AS environment_kind, cv.version, cv.state,
    (SELECT count(*) FROM metrics m WHERE m.catalog_version_id = cv.id) AS metrics_count,
    (SELECT count(*) FROM plans p WHERE p.catalog_version_id = cv.id) AS plans_count,
    cv.created_at, cv.published_at
FROM catalog_versions cv
JOIN environments e ON e.id = cv.environment_id
WHERE cv.provider_id = $1
ORDER BY cv.created_at DESC
`

type ListCatalogVersionsByProviderRow struct {
	ID              uuid.UUID  `json:"id"`
	EnvironmentID   uuid.UUID  `json:"environment_id"`
	EnvironmentKind string     `json:"environment_kind"`
	Version         int32      `json:"version"`
	State           string     `json:"state"`
	MetricsCount    int64      `json:"metrics_count"`
	PlansCount      int64      `json:"plans_count"`
	CreatedAt       time.Time  `json:"created_at"`
	PublishedAt     *time.Time `json:"published_at"`
}

// ---- operator views (join across environments; operator context only) ----
func (q *Queries) ListCatalogVersionsByProvider(ctx context.Context, providerID uuid.UUID) ([]ListCatalogVersionsByProviderRow, error) {
	rows, err := q.db.Query(ctx, listCatalogVersionsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatalogVersionsByProviderRow
	for rows.Next() {
		var i ListCatalogVersionsByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.EnvironmentKind,
			&i.Version,
			&i.State,
			&i.MetricsCount,
			&i.PlansCount,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogVersionsByTenant = `-- name: ListCatalogVersionsByTenant :many
SELECT id, provider_id, environment_id, version, state, created_at, validated_at, published_at, retired_at FROM catalog_versions
WHERE provider_id = $1 AND environment_id = $2
ORDER BY version DESC
`

type ListCatalogVersionsByTenantParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListCatalogVersionsByTenant(ctx context.Context, arg ListCatalogVersionsByTenantParams) ([]CatalogVersion, error) {
	rows, err := q.db.Query(ctx, listCatalogVersionsByTenant, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogVersion
	for rows.Next() {
		var i CatalogVersion
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Version,
			&i.State,
			&i.CreatedAt,
			&i.ValidatedAt,
			&i.PublishedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerAccounts = `-- name: ListCustomerAccounts :many
SELECT id, provider_id, environment_id, external_id, account_type, display_name, created_at FROM customer_accounts
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListCustomerAccountsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListCustomerAccounts(ctx context.Context, arg ListCustomerAccountsParams) ([]CustomerAccount, error) {
	rows, err := q.db.Query(ctx, listCustomerAccounts, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerAccount
	for rows.Next() {
		var i CustomerAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.ExternalID,
			&i.AccountType,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByProvider = `-- name: ListCustomersByProvider :many
SELECT ca.id, ca.external_id, ca.account_type, ca.display_name, ca.environment_id,
    e.kind AS environment_kind, ca.created_at
FROM customer_accounts ca
JOIN environments e ON e.id = ca.environment_id
WHERE ca.provider_id = $1
ORDER BY ca.created_at DESC
`

type ListCustomersByProviderRow struct {
	ID              uuid.UUID `json:"id"`
	ExternalID      string    `json:"external_id"`
	AccountType     string    `json:"account_type"`
	DisplayName     string    `json:"display_name"`
	EnvironmentID   uuid.UUID `json:"environment_id"`
	EnvironmentKind string    `json:"environment_kind"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) ListCustomersByProvider(ctx context.Context, providerID uuid.UUID) ([]ListCustomersByProviderRow, error) {
	rows, err := q.db.Query(ctx, listCustomersByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersByProviderRow
	for rows.Next() {
		var i ListCustomersByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.AccountType,
			&i.DisplayName,
			&i.EnvironmentID,
			&i.EnvironmentKind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsByPlan = `-- name: ListGrantsByPlan :many
SELECT id, plan_id, catalog_version_id, provider_id, environment_id, key, value_type, value FROM entitlement_grants WHERE plan_id = $1
`

func (q *Queries) ListGrantsByPlan(ctx context.Context, planID uuid.UUID) ([]EntitlementGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntitlementGrant
	for rows.Next() {
		var i EntitlementGrant
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.CatalogVersionID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Key,
			&i.ValueType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsByVersion = `-- name: ListGrantsByVersion :many
SELECT id, plan_id, catalog_version_id, provider_id, environment_id, key, value_type, value FROM entitlement_grants WHERE catalog_version_id = $1 ORDER BY key
`

func (q *Queries) ListGrantsByVersion(ctx context.Context, catalogVersionID uuid.UUID) ([]EntitlementGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsByVersion, catalogVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntitlementGrant
	for rows.Next() {
		var i EntitlementGrant
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.CatalogVersionID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Key,
			&i.ValueType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceLinesByInvoice = `-- name: ListInvoiceLinesByInvoice :many
SELECT id, invoice_id, provider_id, environment_id, lago_fee_id, metric_code, item_type, item_name, units, precise_unit_amount, amount_cents, taxes_amount_cents, total_amount_cents, currency, event_transaction_id, from_date, to_date, created_at, metric_id, price_id FROM invoice_lines WHERE invoice_id = $1 AND provider_id = $2 AND environment_id = $3 ORDER BY created_at
`

type ListInvoiceLinesByInvoiceParams struct {
	InvoiceID     uuid.UUID `json:"invoice_id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListInvoiceLinesByInvoice(ctx context.Context, arg ListInvoiceLinesByInvoiceParams) ([]InvoiceLine, error) {
	rows, err := q.db.Query(ctx, listInvoiceLinesByInvoice, arg.InvoiceID, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceLine
	for rows.Next() {
		var i InvoiceLine
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.LagoFeeID,
			&i.MetricCode,
			&i.ItemType,
			&i.ItemName,
			&i.Units,
			&i.PreciseUnitAmount,
			&i.AmountCents,
			&i.TaxesAmountCents,
			&i.TotalAmountCents,
			&i.Currency,
			&i.EventTransactionID,
			&i.FromDate,
			&i.ToDate,
			&i.CreatedAt,
			&i.MetricID,
			&i.PriceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByProvider = `-- name: ListInvoicesByProvider :many
SELECT i.id, i.number, i.lago_id, i.issuing_date, i.invoice_type, i.status, i.payment_status,
       i.currency, i.total_amount_cents, i.customer_account_id, i.subscription_id, i.catalog_version_id,
       ca.external_id AS customer_external_id, i.environment_id, e.kind AS environment_kind
FROM invoices i
JOIN customer_accounts ca ON ca.id = i.customer_account_id
JOIN environments e ON e.id = i.environment_id
WHERE i.provider_id = $1
ORDER BY i.issuing_date DESC LIMIT 200
`

type ListInvoicesByProviderRow struct {
	ID                 uuid.UUID     `json:"id"`
	Number             string        `json:"number"`
	LagoID             string        `json:"lago_id"`
	IssuingDate        pgtype.Date   `json:"issuing_date"`
	InvoiceType        string        `json:"invoice_type"`
	Status             string        `json:"status"`
	PaymentStatus      string        `json:"payment_status"`
	Currency           string        `json:"currency"`
	TotalAmountCents   int64         `json:"total_amount_cents"`
	CustomerAccountID  uuid.UUID     `json:"customer_account_id"`
	SubscriptionID     uuid.NullUUID `json:"subscription_id"`
	CatalogVersionID   uuid.NullUUID `json:"catalog_version_id"`
	CustomerExternalID string        `json:"customer_external_id"`
	EnvironmentID      uuid.UUID     `json:"environment_id"`
	EnvironmentKind    string        `json:"environment_kind"`
}

func (q *Queries) ListInvoicesByProvider(ctx context.Context, providerID uuid.UUID) ([]ListInvoicesByProviderRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesByProviderRow
	for rows.Next() {
		var i ListInvoicesByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.LagoID,
			&i.IssuingDate,
			&i.InvoiceType,
			&i.Status,
			&i.PaymentStatus,
			&i.Currency,
			&i.TotalAmountCents,
			&i.CustomerAccountID,
			&i.SubscriptionID,
			&i.CatalogVersionID,
			&i.CustomerExternalID,
			&i.EnvironmentID,
			&i.EnvironmentKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByTenant = `-- name: ListInvoicesByTenant :many
SELECT id, provider_id, environment_id, lago_id, number, customer_account_id, subscription_id, catalog_version_id, issuing_date, invoice_type, status, payment_status, currency, fees_amount_cents, coupons_amount_cents, credit_notes_amount_cents, sub_total_excluding_taxes_amount_cents, taxes_amount_cents, sub_total_including_taxes_amount_cents, total_amount_cents, file_url, web_url, lago_created_at, synced_at, finalized_at, voided_at, created_at, updated_at FROM invoices WHERE provider_id = $1 AND environment_id = $2 ORDER BY issuing_date DESC LIMIT $3
`

type ListInvoicesByTenantParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListInvoicesByTenant(ctx context.Context, arg ListInvoicesByTenantParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByTenant, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.LagoID,
			&i.Number,
			&i.CustomerAccountID,
			&i.SubscriptionID,
			&i.CatalogVersionID,
			&i.IssuingDate,
			&i.InvoiceType,
			&i.Status,
			&i.PaymentStatus,
			&i.Currency,
			&i.FeesAmountCents,
			&i.CouponsAmountCents,
			&i.CreditNotesAmountCents,
			&i.SubTotalExcludingTaxesAmountCents,
			&i.TaxesAmountCents,
			&i.SubTotalIncludingTaxesAmountCents,
			&i.TotalAmountCents,
			&i.FileUrl,
			&i.WebUrl,
			&i.LagoCreatedAt,
			&i.SyncedAt,
			&i.FinalizedAt,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricsByVersion = `-- name: ListMetricsByVersion :many
SELECT id, catalog_version_id, provider_id, environment_id, code, name, aggregation_type, field_name, billable FROM metrics WHERE catalog_version_id = $1 ORDER BY code
`

func (q *Queries) ListMetricsByVersion(ctx context.Context, catalogVersionID uuid.UUID) ([]Metric, error) {
	rows, err := q.db.Query(ctx, listMetricsByVersion, catalogVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.CatalogVersionID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Code,
			&i.Name,
			&i.AggregationType,
			&i.FieldName,
			&i.Billable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverridesBySubscription = `-- name: ListOverridesBySubscription :many
SELECT id, provider_id, environment_id, subscription_id, key, value_type, value, expires_at, reason, created_at FROM entitlement_overrides WHERE subscription_id = $1 ORDER BY key
`

func (q *Queries) ListOverridesBySubscription(ctx context.Context, subscriptionID uuid.UUID) ([]EntitlementOverride, error) {
	rows, err := q.db.Query(ctx, listOverridesBySubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntitlementOverride
	for rows.Next() {
		var i EntitlementOverride
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.SubscriptionID,
			&i.Key,
			&i.ValueType,
			&i.Value,
			&i.ExpiresAt,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByVersion = `-- name: ListPlansByVersion :many
SELECT id, catalog_version_id, provider_id, environment_id, code, name, interval, currency FROM plans WHERE catalog_version_id = $1 ORDER BY code
`

func (q *Queries) ListPlansByVersion(ctx context.Context, catalogVersionID uuid.UUID) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByVersion, catalogVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.CatalogVersionID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Code,
			&i.Name,
			&i.Interval,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesByPlan = `-- name: ListPricesByPlan :many
SELECT id, plan_id, catalog_version_id, provider_id, environment_id, metric_id, charge_model, properties FROM prices WHERE plan_id = $1
`

func (q *Queries) ListPricesByPlan(ctx context.Context, planID uuid.UUID) ([]Price, error) {
	rows, err := q.db.Query(ctx, listPricesByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Price
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.CatalogVersionID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.MetricID,
			&i.ChargeModel,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesByVersion = `-- name: ListPricesByVersion :many
SELECT id, plan_id, catalog_version_id, provider_id, environment_id, metric_id, charge_model, properties FROM prices WHERE catalog_version_id = $1 ORDER BY id
`

func (q *Queries) ListPricesByVersion(ctx context.Context, catalogVersionID uuid.UUID) ([]Price, error) {
	rows, err := q.db.Query(ctx, listPricesByVersion, catalogVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Price
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.CatalogVersionID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.MetricID,
			&i.ChargeModel,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByProvider = `-- name: ListSubscriptionsByProvider :many
SELECT s.id, s.external_id, ca.external_id AS customer_external_id, p.code AS plan_code,
    s.catalog_version_id, s.status, e.kind AS environment_kind, s.started_at, s.terminated_at
FROM subscriptions s
JOIN customer_accounts ca ON ca.id = s.customer_account_id
JOIN plans p ON p.id = s.plan_id
JOIN environments e ON e.id = s.environment_id
WHERE s.provider_id = $1
ORDER BY s.started_at DESC
`

type ListSubscriptionsByProviderRow struct {
	ID                 uuid.UUID  `json:"id"`
	ExternalID         string     `json:"external_id"`
	CustomerExternalID string     `json:"customer_external_id"`
	PlanCode           string     `json:"plan_code"`
	CatalogVersionID   uuid.UUID  `json:"catalog_version_id"`
	Status             string     `json:"status"`
	EnvironmentKind    string     `json:"environment_kind"`
	StartedAt          time.Time  `json:"started_at"`
	TerminatedAt       *time.Time `json:"terminated_at"`
}

func (q *Queries) ListSubscriptionsByProvider(ctx context.Context, providerID uuid.UUID) ([]ListSubscriptionsByProviderRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsByProviderRow
	for rows.Next() {
		var i ListSubscriptionsByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.CustomerExternalID,
			&i.PlanCode,
			&i.CatalogVersionID,
			&i.Status,
			&i.EnvironmentKind,
			&i.StartedAt,
			&i.TerminatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByTenant = `-- name: ListSubscriptionsByTenant :many
SELECT id, provider_id, environment_id, external_id, customer_account_id, catalog_version_id, plan_id, status, started_at, terminated_at FROM subscriptions
WHERE provider_id = $1 AND environment_id = $2
ORDER BY started_at DESC
LIMIT $3
`

type ListSubscriptionsByTenantParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListSubscriptionsByTenant(ctx context.Context, arg ListSubscriptionsByTenantParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByTenant, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.ExternalID,
			&i.CustomerAccountID,
			&i.CatalogVersionID,
			&i.PlanID,
			&i.Status,
			&i.StartedAt,
			&i.TerminatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageEventsByProvider = `-- name: ListUsageEventsByProvider :many
SELECT ue.id, ue.transaction_id, ue.kind, ue.metric_code,
    ca.external_id AS customer_external_id, ue.environment_id, e.kind AS environment_kind,
    ue.event_timestamp, ue.created_at
FROM usage_events ue
JOIN customer_accounts ca ON ca.id = ue.customer_account_id
JOIN environments e ON e.id = ue.environment_id
WHERE ue.provider_id = $1
ORDER BY ue.created_at DESC
LIMIT 200
`

type ListUsageEventsByProviderRow struct {
	ID                 uuid.UUID `json:"id"`
	TransactionID      string    `json:"transaction_id"`
	Kind               string    `json:"kind"`
	MetricCode         string    `json:"metric_code"`
	CustomerExternalID string    `json:"customer_external_id"`
	EnvironmentID      uuid.UUID `json:"environment_id"`
	EnvironmentKind    string    `json:"environment_kind"`
	EventTimestamp     time.Time `json:"event_timestamp"`
	CreatedAt          time.Time `json:"created_at"`
}

func (q *Queries) ListUsageEventsByProvider(ctx context.Context, providerID uuid.UUID) ([]ListUsageEventsByProviderRow, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageEventsByProviderRow
	for rows.Next() {
		var i ListUsageEventsByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Kind,
			&i.MetricCode,
			&i.CustomerExternalID,
			&i.EnvironmentID,
			&i.EnvironmentKind,
			&i.EventTimestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageEventsByTenant = `-- name: ListUsageEventsByTenant :many
SELECT id, provider_id, environment_id, transaction_id, kind, metric_code, customer_account_id, subscription_id, event_timestamp, properties, payload_hash, reverses_id, reason, created_at FROM usage_events
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListUsageEventsByTenantParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListUsageEventsByTenant(ctx context.Context, arg ListUsageEventsByTenantParams) ([]UsageEvent, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByTenant, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageEvent
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.TransactionID,
			&i.Kind,
			&i.MetricCode,
			&i.CustomerAccountID,
			&i.SubscriptionID,
			&i.EventTimestamp,
			&i.Properties,
			&i.PayloadHash,
			&i.ReversesID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextCatalogVersionNumber = `-- name: NextCatalogVersionNumber :one


SELECT COALESCE(MAX(version), 0) + 1 FROM catalog_versions
WHERE provider_id = $1 AND environment_id = $2
`

type NextCatalogVersionNumberParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

// Phase 1 billing core queries. All statements run inside tenant-scoped
// (WithTenant) or operator (WithOperator) transactions; RLS enforces the
// provider/environment boundary.
// ---- catalog versions ----
func (q *Queries) NextCatalogVersionNumber(ctx context.Context, arg NextCatalogVersionNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextCatalogVersionNumber, arg.ProviderID, arg.EnvironmentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const terminateSubscription = `-- name: TerminateSubscription :one
UPDATE subscriptions
SET status = 'terminated', terminated_at = now()
WHERE id = $1
RETURNING id, provider_id, environment_id, external_id, customer_account_id, catalog_version_id, plan_id, status, started_at, terminated_at
`

func (q *Queries) TerminateSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, terminateSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.CustomerAccountID,
		&i.CatalogVersionID,
		&i.PlanID,
		&i.Status,
		&i.StartedAt,
		&i.TerminatedAt,
	)
	return i, err
}

const updateCatalogVersionState = `-- name: UpdateCatalogVersionState :one
UPDATE catalog_versions
SET state = $2,
    validated_at = CASE WHEN $2 = 'validated' THEN now() ELSE validated_at END,
    published_at = CASE WHEN $2 = 'published' THEN now() ELSE published_at END,
    retired_at   = CASE WHEN $2 = 'retired'   THEN now() ELSE retired_at END
WHERE id = $1
RETURNING id, provider_id, environment_id, version, state, created_at, validated_at, published_at, retired_at
`

type UpdateCatalogVersionStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) UpdateCatalogVersionState(ctx context.Context, arg UpdateCatalogVersionStateParams) (CatalogVersion, error) {
	row := q.db.QueryRow(ctx, updateCatalogVersionState, arg.ID, arg.State)
	var i CatalogVersion
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Version,
		&i.State,
		&i.CreatedAt,
		&i.ValidatedAt,
		&i.PublishedAt,
		&i.RetiredAt,
	)
	return i, err
}

const upsertEntitlementOverride = `-- name: UpsertEntitlementOverride :one

INSERT INTO entitlement_overrides (provider_id, environment_id, subscription_id, key, value_type, value, expires_at, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (subscription_id, key)
DO UPDATE SET value_type = EXCLUDED.value_type,
    value = EXCLUDED.value,
    expires_at = EXCLUDED.expires_at,
    reason = EXCLUDED.reason
RETURNING id, provider_id, environment_id, subscription_id, key, value_type, value, expires_at, reason, created_at
`

type UpsertEntitlementOverrideParams struct {
	ProviderID     uuid.UUID  `json:"provider_id"`
	EnvironmentID  uuid.UUID  `json:"environment_id"`
	SubscriptionID uuid.UUID  `json:"subscription_id"`
	Key            string     `json:"key"`
	ValueType      string     `json:"value_type"`
	Value          []byte     `json:"value"`
	ExpiresAt      *time.Time `json:"expires_at"`
	Reason         string     `json:"reason"`
}

// ---- entitlement overrides ----
func (q *Queries) UpsertEntitlementOverride(ctx context.Context, arg UpsertEntitlementOverrideParams) (EntitlementOverride, error) {
	row := q.db.QueryRow(ctx, upsertEntitlementOverride,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.SubscriptionID,
		arg.Key,
		arg.ValueType,
		arg.Value,
		arg.ExpiresAt,
		arg.Reason,
	)
	var i EntitlementOverride
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SubscriptionID,
		&i.Key,
		&i.ValueType,
		&i.Value,
		&i.ExpiresAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const upsertInvoice = `-- name: UpsertInvoice :one

INSERT INTO invoices (
    provider_id, environment_id, lago_id, number,
    customer_account_id, subscription_id, catalog_version_id,
    issuing_date, invoice_type, status, payment_status, currency,
    fees_amount_cents, coupons_amount_cents, credit_notes_amount_cents,
    sub_total_excluding_taxes_amount_cents, taxes_amount_cents,
    sub_total_including_taxes_amount_cents, total_amount_cents,
    file_url, web_url, lago_created_at, finalized_at, voided_at, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25
) ON CONFLICT (provider_id, environment_id, lago_id) DO UPDATE SET
    number = EXCLUDED.number,
    status = EXCLUDED.status,
    payment_status = EXCLUDED.payment_status,
    currency = EXCLUDED.currency,
    fees_amount_cents = EXCLUDED.fees_amount_cents,
    coupons_amount_cents = EXCLUDED.coupons_amount_cents,
    credit_notes_amount_cents = EXCLUDED.credit_notes_amount_cents,
    sub_total_excluding_taxes_amount_cents = EXCLUDED.sub_total_excluding_taxes_amount_cents,
    taxes_amount_cents = EXCLUDED.taxes_amount_cents,
    sub_total_including_taxes_amount_cents = EXCLUDED.sub_total_including_taxes_amount_cents,
    total_amount_cents = EXCLUDED.total_amount_cents,
    file_url = EXCLUDED.file_url,
    web_url = EXCLUDED.web_url,
    finalized_at = EXCLUDED.finalized_at,
    voided_at = EXCLUDED.voided_at,
    synced_at = EXCLUDED.synced_at
RETURNING id, provider_id, environment_id, lago_id, number, customer_account_id, subscription_id, catalog_version_id, issuing_date, invoice_type, status, payment_status, currency, fees_amount_cents, coupons_amount_cents, credit_notes_amount_cents, sub_total_excluding_taxes_amount_cents, taxes_amount_cents, sub_total_including_taxes_amount_cents, total_amount_cents, file_url, web_url, lago_created_at, synced_at, finalized_at, voided_at, created_at, updated_at
`

type UpsertInvoiceParams struct {
	ProviderID                        uuid.UUID     `json:"provider_id"`
	EnvironmentID                     uuid.UUID     `json:"environment_id"`
	LagoID                            string        `json:"lago_id"`
	Number                            string        `json:"number"`
	CustomerAccountID                 uuid.UUID     `json:"customer_account_id"`
	SubscriptionID                    uuid.NullUUID `json:"subscription_id"`
	CatalogVersionID                  uuid.NullUUID `json:"catalog_version_id"`
	IssuingDate                       pgtype.Date   `json:"issuing_date"`
	InvoiceType                       string        `json:"invoice_type"`
	Status                            string        `json:"status"`
	PaymentStatus                     string        `json:"payment_status"`
	Currency                          string        `json:"currency"`
	FeesAmountCents                   int64         `json:"fees_amount_cents"`
	CouponsAmountCents                int64         `json:"coupons_amount_cents"`
	CreditNotesAmountCents            int64         `json:"credit_notes_amount_cents"`
	SubTotalExcludingTaxesAmountCents int64         `json:"sub_total_excluding_taxes_amount_cents"`
	TaxesAmountCents                  int64         `json:"taxes_amount_cents"`
	SubTotalIncludingTaxesAmountCents int64         `json:"sub_total_including_taxes_amount_cents"`
	TotalAmountCents                  int64         `json:"total_amount_cents"`
	FileUrl                           pgtype.Text   `json:"file_url"`
	WebUrl                            pgtype.Text   `json:"web_url"`
	LagoCreatedAt                     *time.Time    `json:"lago_created_at"`
	FinalizedAt                       *time.Time    `json:"finalized_at"`
	VoidedAt                          *time.Time    `json:"voided_at"`
	SyncedAt                          time.Time     `json:"synced_at"`
}

// ---- invoices ----
func (q *Queries) UpsertInvoice(ctx context.Context, arg UpsertInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, upsertInvoice,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.LagoID,
		arg.Number,
		arg.CustomerAccountID,
		arg.SubscriptionID,
		arg.CatalogVersionID,
		arg.IssuingDate,
		arg.InvoiceType,
		arg.Status,
		arg.PaymentStatus,
		arg.Currency,
		arg.FeesAmountCents,
		arg.CouponsAmountCents,
		arg.CreditNotesAmountCents,
		arg.SubTotalExcludingTaxesAmountCents,
		arg.TaxesAmountCents,
		arg.SubTotalIncludingTaxesAmountCents,
		arg.TotalAmountCents,
		arg.FileUrl,
		arg.WebUrl,
		arg.LagoCreatedAt,
		arg.FinalizedAt,
		arg.VoidedAt,
		arg.SyncedAt,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.LagoID,
		&i.Number,
		&i.CustomerAccountID,
		&i.SubscriptionID,
		&i.CatalogVersionID,
		&i.IssuingDate,
		&i.InvoiceType,
		&i.Status,
		&i.PaymentStatus,
		&i.Currency,
		&i.FeesAmountCents,
		&i.CouponsAmountCents,
		&i.CreditNotesAmountCents,
		&i.SubTotalExcludingTaxesAmountCents,
		&i.TaxesAmountCents,
		&i.SubTotalIncludingTaxesAmountCents,
		&i.TotalAmountCents,
		&i.FileUrl,
		&i.WebUrl,
		&i.LagoCreatedAt,
		&i.SyncedAt,
		&i.FinalizedAt,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
