// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cell_failovers.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createCellFailover = `-- name: CreateCellFailover :one
INSERT INTO cell_failovers (provider_id, from_cell_id, to_cell_id, reason, initiated_by, fencing_token)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider_id, from_cell_id, to_cell_id, status, reason, initiated_by, fencing_token, replayed_usage, replayed_outbox, started_at, completed_at
`

type CreateCellFailoverParams struct {
	ProviderID   uuid.UUID `json:"provider_id"`
	FromCellID   uuid.UUID `json:"from_cell_id"`
	ToCellID     uuid.UUID `json:"to_cell_id"`
	Reason       string    `json:"reason"`
	InitiatedBy  string    `json:"initiated_by"`
	FencingToken string    `json:"fencing_token"`
}

func (q *Queries) CreateCellFailover(ctx context.Context, arg CreateCellFailoverParams) (CellFailover, error) {
	row := q.db.QueryRow(ctx, createCellFailover,
		arg.ProviderID,
		arg.FromCellID,
		arg.ToCellID,
		arg.Reason,
		arg.InitiatedBy,
		arg.FencingToken,
	)
	var i CellFailover
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.FromCellID,
		&i.ToCellID,
		&i.Status,
		&i.Reason,
		&i.InitiatedBy,
		&i.FencingToken,
		&i.ReplayedUsage,
		&i.ReplayedOutbox,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getActiveCellFailover = `-- name: GetActiveCellFailover :one
SELECT id, provider_id, from_cell_id, to_cell_id, status, reason, initiated_by, fencing_token, replayed_usage, replayed_outbox, started_at, completed_at FROM cell_failovers
WHERE provider_id = $1 AND status NOT IN ('completed', 'aborted')
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCellFailover(ctx context.Context, providerID uuid.UUID) (CellFailover, error) {
	row := q.db.QueryRow(ctx, getActiveCellFailover, providerID)
	var i CellFailover
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.FromCellID,
		&i.ToCellID,
		&i.Status,
		&i.Reason,
		&i.InitiatedBy,
		&i.FencingToken,
		&i.ReplayedUsage,
		&i.ReplayedOutbox,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCellFailoverByID = `-- name: GetCellFailoverByID :one
SELECT id, provider_id, from_cell_id, to_cell_id, status, reason, initiated_by, fencing_token, replayed_usage, replayed_outbox, started_at, completed_at FROM cell_failovers WHERE id = $1
`

func (q *Queries) GetCellFailoverByID(ctx context.Context, id uuid.UUID) (CellFailover, error) {
	row := q.db.QueryRow(ctx, getCellFailoverByID, id)
	var i CellFailover
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.FromCellID,
		&i.ToCellID,
		&i.Status,
		&i.Reason,
		&i.InitiatedBy,
		&i.FencingToken,
		&i.ReplayedUsage,
		&i.ReplayedOutbox,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCellFailoversByProvider = `-- name: ListCellFailoversByProvider :many
SELECT id, provider_id, from_cell_id, to_cell_id, status, reason, initiated_by, fencing_token, replayed_usage, replayed_outbox, started_at, completed_at FROM cell_failovers
WHERE provider_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListCellFailoversByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListCellFailoversByProvider(ctx context.Context, arg ListCellFailoversByProviderParams) ([]CellFailover, error) {
	rows, err := q.db.Query(ctx, listCellFailoversByProvider, arg.ProviderID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CellFailover
	for rows.Next() {
		var i CellFailover
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.FromCellID,
			&i.ToCellID,
			&i.Status,
			&i.Reason,
			&i.InitiatedBy,
			&i.FencingToken,
			&i.ReplayedUsage,
			&i.ReplayedOutbox,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCellFailoverReplay = `-- name: UpdateCellFailoverReplay :exec
UPDATE cell_failovers
SET replayed_usage = $2, replayed_outbox = $3
WHERE id = $1
`

type UpdateCellFailoverReplayParams struct {
	ID             uuid.UUID `json:"id"`
	ReplayedUsage  int32     `json:"replayed_usage"`
	ReplayedOutbox int32     `json:"replayed_outbox"`
}

func (q *Queries) UpdateCellFailoverReplay(ctx context.Context, arg UpdateCellFailoverReplayParams) error {
	_, err := q.db.Exec(ctx, updateCellFailoverReplay, arg.ID, arg.ReplayedUsage, arg.ReplayedOutbox)
	return err
}

const updateCellFailoverStatus = `-- name: UpdateCellFailoverStatus :one
UPDATE cell_failovers
SET status = $2, completed_at = CASE WHEN $2 IN ('completed', 'aborted') THEN now() ELSE completed_at END
WHERE id = $1
RETURNING id, provider_id, from_cell_id, to_cell_id, status, reason, initiated_by, fencing_token, replayed_usage, replayed_outbox, started_at, completed_at
`

type UpdateCellFailoverStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCellFailoverStatus(ctx context.Context, arg UpdateCellFailoverStatusParams) (CellFailover, error) {
	row := q.db.QueryRow(ctx, updateCellFailoverStatus, arg.ID, arg.Status)
	var i CellFailover
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.FromCellID,
		&i.ToCellID,
		&i.Status,
		&i.Reason,
		&i.InitiatedBy,
		&i.FencingToken,
		&i.ReplayedUsage,
		&i.ReplayedOutbox,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
