// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cell_migrations.sql

package storegen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCellMigration = `-- name: CreateCellMigration :one
INSERT INTO cell_migrations (provider_id, from_cell_id, to_cell_id, reason, initiated_by, scheduled_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider_id, from_cell_id, to_cell_id, status, scheduled_at, precheck_passed, data_integrity_hash, record_count, reason, initiated_by, started_at, completed_at, error_message, created_at, updated_at
`

type CreateCellMigrationParams struct {
	ProviderID  uuid.UUID  `json:"provider_id"`
	FromCellID  uuid.UUID  `json:"from_cell_id"`
	ToCellID    uuid.UUID  `json:"to_cell_id"`
	Reason      string     `json:"reason"`
	InitiatedBy string     `json:"initiated_by"`
	ScheduledAt *time.Time `json:"scheduled_at"`
}

func (q *Queries) CreateCellMigration(ctx context.Context, arg CreateCellMigrationParams) (CellMigration, error) {
	row := q.db.QueryRow(ctx, createCellMigration,
		arg.ProviderID,
		arg.FromCellID,
		arg.ToCellID,
		arg.Reason,
		arg.InitiatedBy,
		arg.ScheduledAt,
	)
	var i CellMigration
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.FromCellID,
		&i.ToCellID,
		&i.Status,
		&i.ScheduledAt,
		&i.PrecheckPassed,
		&i.DataIntegrityHash,
		&i.RecordCount,
		&i.Reason,
		&i.InitiatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCellMigration = `-- name: GetActiveCellMigration :one
SELECT id, provider_id, from_cell_id, to_cell_id, status, scheduled_at, precheck_passed, data_integrity_hash, record_count, reason, initiated_by, started_at, completed_at, error_message, created_at, updated_at FROM cell_migrations
WHERE provider_id = $1 AND status NOT IN ('completed', 'failed', 'cancelled')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCellMigration(ctx context.Context, providerID uuid.UUID) (CellMigration, error) {
	row := q.db.QueryRow(ctx, getActiveCellMigration, providerID)
	var i CellMigration
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.FromCellID,
		&i.ToCellID,
		&i.Status,
		&i.ScheduledAt,
		&i.PrecheckPassed,
		&i.DataIntegrityHash,
		&i.RecordCount,
		&i.Reason,
		&i.InitiatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCellMigrationByID = `-- name: GetCellMigrationByID :one
SELECT id, provider_id, from_cell_id, to_cell_id, status, scheduled_at, precheck_passed, data_integrity_hash, record_count, reason, initiated_by, started_at, completed_at, error_message, created_at, updated_at FROM cell_migrations WHERE id = $1
`

func (q *Queries) GetCellMigrationByID(ctx context.Context, id uuid.UUID) (CellMigration, error) {
	row := q.db.QueryRow(ctx, getCellMigrationByID, id)
	var i CellMigration
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.FromCellID,
		&i.ToCellID,
		&i.Status,
		&i.ScheduledAt,
		&i.PrecheckPassed,
		&i.DataIntegrityHash,
		&i.RecordCount,
		&i.Reason,
		&i.InitiatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCellMigrationsByProvider = `-- name: ListCellMigrationsByProvider :many
SELECT id, provider_id, from_cell_id, to_cell_id, status, scheduled_at, precheck_passed, data_integrity_hash, record_count, reason, initiated_by, started_at, completed_at, error_message, created_at, updated_at FROM cell_migrations
WHERE provider_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListCellMigrationsByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListCellMigrationsByProvider(ctx context.Context, arg ListCellMigrationsByProviderParams) ([]CellMigration, error) {
	rows, err := q.db.Query(ctx, listCellMigrationsByProvider, arg.ProviderID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CellMigration
	for rows.Next() {
		var i CellMigration
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.FromCellID,
			&i.ToCellID,
			&i.Status,
			&i.ScheduledAt,
			&i.PrecheckPassed,
			&i.DataIntegrityHash,
			&i.RecordCount,
			&i.Reason,
			&i.InitiatedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCellMigrationError = `-- name: SetCellMigrationError :exec
UPDATE cell_migrations
SET error_message = $2, updated_at = now()
WHERE id = $1
`

type SetCellMigrationErrorParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) SetCellMigrationError(ctx context.Context, arg SetCellMigrationErrorParams) error {
	_, err := q.db.Exec(ctx, setCellMigrationError, arg.ID, arg.ErrorMessage)
	return err
}

const setCellMigrationPrecheck = `-- name: SetCellMigrationPrecheck :exec
UPDATE cell_migrations
SET precheck_passed = $2, data_integrity_hash = $3, record_count = $4, updated_at = now()
WHERE id = $1
`

type SetCellMigrationPrecheckParams struct {
	ID                uuid.UUID   `json:"id"`
	PrecheckPassed    bool        `json:"precheck_passed"`
	DataIntegrityHash pgtype.Text `json:"data_integrity_hash"`
	RecordCount       int32       `json:"record_count"`
}

func (q *Queries) SetCellMigrationPrecheck(ctx context.Context, arg SetCellMigrationPrecheckParams) error {
	_, err := q.db.Exec(ctx, setCellMigrationPrecheck,
		arg.ID,
		arg.PrecheckPassed,
		arg.DataIntegrityHash,
		arg.RecordCount,
	)
	return err
}

const updateCellMigrationStatus = `-- name: UpdateCellMigrationStatus :one
UPDATE cell_migrations
SET status = $2,
    started_at = CASE WHEN $2 = 'migrating' THEN now() ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'cancelled') THEN now() ELSE completed_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, provider_id, from_cell_id, to_cell_id, status, scheduled_at, precheck_passed, data_integrity_hash, record_count, reason, initiated_by, started_at, completed_at, error_message, created_at, updated_at
`

type UpdateCellMigrationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCellMigrationStatus(ctx context.Context, arg UpdateCellMigrationStatusParams) (CellMigration, error) {
	row := q.db.QueryRow(ctx, updateCellMigrationStatus, arg.ID, arg.Status)
	var i CellMigration
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.FromCellID,
		&i.ToCellID,
		&i.Status,
		&i.ScheduledAt,
		&i.PrecheckPassed,
		&i.DataIntegrityHash,
		&i.RecordCount,
		&i.Reason,
		&i.InitiatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
