// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: credentials.sql

package storegen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (provider_id, environment_id, name, key_prefix, key_hash, scopes, allowed_cidrs, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, provider_id, environment_id, name, key_prefix, key_hash, scopes, allowed_cidrs, expires_at, revoked_at, last_used_at, created_at
`

type CreateCredentialParams struct {
	ProviderID    uuid.UUID  `json:"provider_id"`
	EnvironmentID uuid.UUID  `json:"environment_id"`
	Name          string     `json:"name"`
	KeyPrefix     string     `json:"key_prefix"`
	KeyHash       string     `json:"key_hash"`
	Scopes        []string   `json:"scopes"`
	AllowedCidrs  []string   `json:"allowed_cidrs"`
	ExpiresAt     *time.Time `json:"expires_at"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scopes,
		arg.AllowedCidrs,
		arg.ExpiresAt,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.AllowedCidrs,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, provider_id, environment_id, name, key_prefix, key_hash, scopes, allowed_cidrs, expires_at, revoked_at, last_used_at, created_at FROM credentials WHERE id = $1
`

func (q *Queries) GetCredentialByID(ctx context.Context, id uuid.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByID, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.AllowedCidrs,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCredentialsByEnvironment = `-- name: ListCredentialsByEnvironment :many
SELECT id, provider_id, environment_id, name, key_prefix, key_hash, scopes, allowed_cidrs, expires_at, revoked_at, last_used_at, created_at FROM credentials
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
`

type ListCredentialsByEnvironmentParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListCredentialsByEnvironment(ctx context.Context, arg ListCredentialsByEnvironmentParams) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByEnvironment, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.AllowedCidrs,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCredentialByKeyHash = `-- name: ResolveCredentialByKeyHash :one
SELECT c.id AS credential_id,
       c.provider_id,
       c.environment_id,
       c.name,
       c.key_prefix,
       c.scopes,
       c.allowed_cidrs,
       c.expires_at,
       c.revoked_at,
       p.slug AS provider_slug,
       p.lifecycle_state,
       e.kind AS environment_kind,
       e.issuer
FROM credentials c
JOIN providers p ON p.id = c.provider_id
JOIN environments e ON e.id = c.environment_id
WHERE c.key_hash = $1
`

type ResolveCredentialByKeyHashRow struct {
	CredentialID    uuid.UUID  `json:"credential_id"`
	ProviderID      uuid.UUID  `json:"provider_id"`
	EnvironmentID   uuid.UUID  `json:"environment_id"`
	Name            string     `json:"name"`
	KeyPrefix       string     `json:"key_prefix"`
	Scopes          []string   `json:"scopes"`
	AllowedCidrs    []string   `json:"allowed_cidrs"`
	ExpiresAt       *time.Time `json:"expires_at"`
	RevokedAt       *time.Time `json:"revoked_at"`
	ProviderSlug    string     `json:"provider_slug"`
	LifecycleState  string     `json:"lifecycle_state"`
	EnvironmentKind string     `json:"environment_kind"`
	Issuer          string     `json:"issuer"`
}

func (q *Queries) ResolveCredentialByKeyHash(ctx context.Context, keyHash string) (ResolveCredentialByKeyHashRow, error) {
	row := q.db.QueryRow(ctx, resolveCredentialByKeyHash, keyHash)
	var i ResolveCredentialByKeyHashRow
	err := row.Scan(
		&i.CredentialID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Name,
		&i.KeyPrefix,
		&i.Scopes,
		&i.AllowedCidrs,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ProviderSlug,
		&i.LifecycleState,
		&i.EnvironmentKind,
		&i.Issuer,
	)
	return i, err
}

const revokeCredential = `-- name: RevokeCredential :one
UPDATE credentials SET revoked_at = now() WHERE id = $1 RETURNING id, provider_id, environment_id, name, key_prefix, key_hash, scopes, allowed_cidrs, expires_at, revoked_at, last_used_at, created_at
`

func (q *Queries) RevokeCredential(ctx context.Context, id uuid.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, revokeCredential, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.AllowedCidrs,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchCredentialLastUsed = `-- name: TouchCredentialLastUsed :exec
UPDATE credentials SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchCredentialLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCredentialLastUsed, id)
	return err
}
