// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: custom_domains.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createCustomDomain = `-- name: CreateCustomDomain :one
INSERT INTO custom_domains (provider_id, environment_id, domain, verification_token)
VALUES ($1, $2, $3, $4)
RETURNING id, provider_id, environment_id, domain, verification_token, status, verified_at, revoked_at, created_at, updated_at
`

type CreateCustomDomainParams struct {
	ProviderID        uuid.UUID `json:"provider_id"`
	EnvironmentID     uuid.UUID `json:"environment_id"`
	Domain            string    `json:"domain"`
	VerificationToken string    `json:"verification_token"`
}

func (q *Queries) CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, createCustomDomain,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Domain,
		arg.VerificationToken,
	)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Domain,
		&i.VerificationToken,
		&i.Status,
		&i.VerifiedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomDomain = `-- name: DeleteCustomDomain :execrows
DELETE FROM custom_domains
WHERE provider_id = $1 AND environment_id = $2 AND id = $3 AND status != 'verified'
`

type DeleteCustomDomainParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) DeleteCustomDomain(ctx context.Context, arg DeleteCustomDomainParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomDomain, arg.ProviderID, arg.EnvironmentID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomDomainByHostname = `-- name: GetCustomDomainByHostname :one
SELECT id, provider_id, environment_id, domain, verification_token, status, verified_at, revoked_at, created_at, updated_at FROM custom_domains WHERE domain = $1 AND status = 'verified'
`

// Operator-only lookup for request routing (find which provider owns a hostname).
func (q *Queries) GetCustomDomainByHostname(ctx context.Context, domain string) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, getCustomDomainByHostname, domain)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Domain,
		&i.VerificationToken,
		&i.Status,
		&i.VerifiedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomDomainByID = `-- name: GetCustomDomainByID :one
SELECT id, provider_id, environment_id, domain, verification_token, status, verified_at, revoked_at, created_at, updated_at FROM custom_domains WHERE id = $1
`

func (q *Queries) GetCustomDomainByID(ctx context.Context, id uuid.UUID) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, getCustomDomainByID, id)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Domain,
		&i.VerificationToken,
		&i.Status,
		&i.VerifiedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomDomains = `-- name: ListCustomDomains :many
SELECT id, provider_id, environment_id, domain, verification_token, status, verified_at, revoked_at, created_at, updated_at FROM custom_domains
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
`

type ListCustomDomainsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListCustomDomains(ctx context.Context, arg ListCustomDomainsParams) ([]CustomDomain, error) {
	rows, err := q.db.Query(ctx, listCustomDomains, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomDomain
	for rows.Next() {
		var i CustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Domain,
			&i.VerificationToken,
			&i.Status,
			&i.VerifiedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCustomDomain = `-- name: RevokeCustomDomain :one
UPDATE custom_domains
SET status = 'revoked', revoked_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('pending', 'verified')
RETURNING id, provider_id, environment_id, domain, verification_token, status, verified_at, revoked_at, created_at, updated_at
`

func (q *Queries) RevokeCustomDomain(ctx context.Context, id uuid.UUID) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, revokeCustomDomain, id)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Domain,
		&i.VerificationToken,
		&i.Status,
		&i.VerifiedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyCustomDomain = `-- name: VerifyCustomDomain :one
UPDATE custom_domains
SET status = 'verified', verified_at = now(), updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, provider_id, environment_id, domain, verification_token, status, verified_at, revoked_at, created_at, updated_at
`

func (q *Queries) VerifyCustomDomain(ctx context.Context, id uuid.UUID) (CustomDomain, error) {
	row := q.db.QueryRow(ctx, verifyCustomDomain, id)
	var i CustomDomain
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Domain,
		&i.VerificationToken,
		&i.Status,
		&i.VerifiedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
