// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: data_exports.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeDataExport = `-- name: CompleteDataExport :one
UPDATE data_exports
SET status = 'completed', data_hash = $2, export_data = $3, record_count = $4, completed_at = now()
WHERE id = $1
RETURNING id, provider_id, environment_id, status, export_type, data_hash, export_data, record_count, error_message, created_at, completed_at
`

type CompleteDataExportParams struct {
	ID          uuid.UUID   `json:"id"`
	DataHash    pgtype.Text `json:"data_hash"`
	ExportData  []byte      `json:"export_data"`
	RecordCount int32       `json:"record_count"`
}

func (q *Queries) CompleteDataExport(ctx context.Context, arg CompleteDataExportParams) (DataExport, error) {
	row := q.db.QueryRow(ctx, completeDataExport,
		arg.ID,
		arg.DataHash,
		arg.ExportData,
		arg.RecordCount,
	)
	var i DataExport
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Status,
		&i.ExportType,
		&i.DataHash,
		&i.ExportData,
		&i.RecordCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createDataExport = `-- name: CreateDataExport :one
INSERT INTO data_exports (provider_id, environment_id, export_type)
VALUES ($1, $2, $3)
RETURNING id, provider_id, environment_id, status, export_type, data_hash, export_data, record_count, error_message, created_at, completed_at
`

type CreateDataExportParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ExportType    string    `json:"export_type"`
}

func (q *Queries) CreateDataExport(ctx context.Context, arg CreateDataExportParams) (DataExport, error) {
	row := q.db.QueryRow(ctx, createDataExport, arg.ProviderID, arg.EnvironmentID, arg.ExportType)
	var i DataExport
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Status,
		&i.ExportType,
		&i.DataHash,
		&i.ExportData,
		&i.RecordCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createDeletionProof = `-- name: CreateDeletionProof :one
INSERT INTO deletion_proofs (provider_id, environment_id, data_hash, record_count, proof_signature)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider_id, environment_id, data_hash, record_count, deleted_at, proof_signature, created_at
`

type CreateDeletionProofParams struct {
	ProviderID     uuid.UUID `json:"provider_id"`
	EnvironmentID  uuid.UUID `json:"environment_id"`
	DataHash       string    `json:"data_hash"`
	RecordCount    int32     `json:"record_count"`
	ProofSignature string    `json:"proof_signature"`
}

func (q *Queries) CreateDeletionProof(ctx context.Context, arg CreateDeletionProofParams) (DeletionProof, error) {
	row := q.db.QueryRow(ctx, createDeletionProof,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.DataHash,
		arg.RecordCount,
		arg.ProofSignature,
	)
	var i DeletionProof
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.DataHash,
		&i.RecordCount,
		&i.DeletedAt,
		&i.ProofSignature,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProviderData = `-- name: DeleteProviderData :execrows
DELETE FROM customer_accounts
WHERE provider_id = $1 AND environment_id = $2
`

type DeleteProviderDataParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

// Deletes customer data for the provider's environment. Other data
// (subscriptions, usage, invoices) should be handled by cascade or
// separate cleanup. The deletion proof provides cryptographic evidence.
func (q *Queries) DeleteProviderData(ctx context.Context, arg DeleteProviderDataParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderData, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failDataExport = `-- name: FailDataExport :one
UPDATE data_exports
SET status = 'failed', error_message = $2
WHERE id = $1
RETURNING id, provider_id, environment_id, status, export_type, data_hash, export_data, record_count, error_message, created_at, completed_at
`

type FailDataExportParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) FailDataExport(ctx context.Context, arg FailDataExportParams) (DataExport, error) {
	row := q.db.QueryRow(ctx, failDataExport, arg.ID, arg.ErrorMessage)
	var i DataExport
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Status,
		&i.ExportType,
		&i.DataHash,
		&i.ExportData,
		&i.RecordCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDataExportByID = `-- name: GetDataExportByID :one
SELECT id, provider_id, environment_id, status, export_type, data_hash, export_data, record_count, error_message, created_at, completed_at FROM data_exports WHERE id = $1
`

func (q *Queries) GetDataExportByID(ctx context.Context, id uuid.UUID) (DataExport, error) {
	row := q.db.QueryRow(ctx, getDataExportByID, id)
	var i DataExport
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Status,
		&i.ExportType,
		&i.DataHash,
		&i.ExportData,
		&i.RecordCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDeletionProofByID = `-- name: GetDeletionProofByID :one
SELECT id, provider_id, environment_id, data_hash, record_count, deleted_at, proof_signature, created_at FROM deletion_proofs WHERE id = $1
`

func (q *Queries) GetDeletionProofByID(ctx context.Context, id uuid.UUID) (DeletionProof, error) {
	row := q.db.QueryRow(ctx, getDeletionProofByID, id)
	var i DeletionProof
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.DataHash,
		&i.RecordCount,
		&i.DeletedAt,
		&i.ProofSignature,
		&i.CreatedAt,
	)
	return i, err
}

const listDataExports = `-- name: ListDataExports :many
SELECT id, provider_id, environment_id, status, export_type, data_hash, export_data, record_count, error_message, created_at, completed_at FROM data_exports
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListDataExportsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListDataExports(ctx context.Context, arg ListDataExportsParams) ([]DataExport, error) {
	rows, err := q.db.Query(ctx, listDataExports, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataExport
	for rows.Next() {
		var i DataExport
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Status,
			&i.ExportType,
			&i.DataHash,
			&i.ExportData,
			&i.RecordCount,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletionProofs = `-- name: ListDeletionProofs :many
SELECT id, provider_id, environment_id, data_hash, record_count, deleted_at, proof_signature, created_at FROM deletion_proofs
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListDeletionProofsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListDeletionProofs(ctx context.Context, arg ListDeletionProofsParams) ([]DeletionProof, error) {
	rows, err := q.db.Query(ctx, listDeletionProofs, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeletionProof
	for rows.Next() {
		var i DeletionProof
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.DataHash,
			&i.RecordCount,
			&i.DeletedAt,
			&i.ProofSignature,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDataExportProcessing = `-- name: SetDataExportProcessing :exec
UPDATE data_exports SET status = 'processing' WHERE id = $1
`

func (q *Queries) SetDataExportProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setDataExportProcessing, id)
	return err
}
