// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environments.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (provider_id, kind, issuer)
VALUES ($1, $2, $3)
RETURNING id, provider_id, kind, status, issuer, created_at
`

type CreateEnvironmentParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Kind       string    `json:"kind"`
	Issuer     string    `json:"issuer"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.ProviderID, arg.Kind, arg.Issuer)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Kind,
		&i.Status,
		&i.Issuer,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, provider_id, kind, status, issuer, created_at FROM environments WHERE id = $1
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Kind,
		&i.Status,
		&i.Issuer,
		&i.CreatedAt,
	)
	return i, err
}

const listEnvironmentsByProvider = `-- name: ListEnvironmentsByProvider :many
SELECT id, provider_id, kind, status, issuer, created_at FROM environments WHERE provider_id = $1 ORDER BY created_at
`

func (q *Queries) ListEnvironmentsByProvider(ctx context.Context, providerID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Kind,
			&i.Status,
			&i.Issuer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
