// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: idempotency.sql

package storegen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :execrows
UPDATE idempotency_keys
SET status = 'completed', response_status = $2, content_type = $3, response_body = $4
WHERE id = $1 AND status = 'in_progress'
`

type CompleteIdempotencyKeyParams struct {
	ID             uuid.UUID   `json:"id"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ContentType    pgtype.Text `json:"content_type"`
	ResponseBody   []byte      `json:"response_body"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ID,
		arg.ResponseStatus,
		arg.ContentType,
		arg.ResponseBody,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :execrows
DELETE FROM idempotency_keys WHERE id = $1
`

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdempotencyKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, scope, key_hash, method, path, status, response_status, content_type, response_body, request_id, created_at, expires_at FROM idempotency_keys
WHERE scope = $1 AND key_hash = $2 AND method = $3 AND path = $4
`

type GetIdempotencyKeyParams struct {
	Scope   string `json:"scope"`
	KeyHash []byte `json:"key_hash"`
	Method  string `json:"method"`
	Path    string `json:"path"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey,
		arg.Scope,
		arg.KeyHash,
		arg.Method,
		arg.Path,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.KeyHash,
		&i.Method,
		&i.Path,
		&i.Status,
		&i.ResponseStatus,
		&i.ContentType,
		&i.ResponseBody,
		&i.RequestID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (scope, key_hash, method, path, request_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (scope, key_hash, method, path) DO NOTHING
RETURNING id, scope, key_hash, method, path, status, response_status, content_type, response_body, request_id, created_at, expires_at
`

type InsertIdempotencyKeyParams struct {
	Scope     string    `json:"scope"`
	KeyHash   []byte    `json:"key_hash"`
	Method    string    `json:"method"`
	Path      string    `json:"path"`
	RequestID string    `json:"request_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.Scope,
		arg.KeyHash,
		arg.Method,
		arg.Path,
		arg.RequestID,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.KeyHash,
		&i.Method,
		&i.Path,
		&i.Status,
		&i.ResponseStatus,
		&i.ContentType,
		&i.ResponseBody,
		&i.RequestID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
