// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: metered_billing.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBudgetAlert = `-- name: CreateBudgetAlert :one
INSERT INTO budget_alerts (provider_id, environment_id, subscription_id, metric_code, budget_cents, threshold_pct)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider_id, environment_id, subscription_id, metric_code, budget_cents, threshold_pct, current_spend_cents, alert_status, last_alerted_at, created_at, updated_at
`

type CreateBudgetAlertParams struct {
	ProviderID     uuid.UUID     `json:"provider_id"`
	EnvironmentID  uuid.UUID     `json:"environment_id"`
	SubscriptionID uuid.NullUUID `json:"subscription_id"`
	MetricCode     pgtype.Text   `json:"metric_code"`
	BudgetCents    int64         `json:"budget_cents"`
	ThresholdPct   float64       `json:"threshold_pct"`
}

func (q *Queries) CreateBudgetAlert(ctx context.Context, arg CreateBudgetAlertParams) (BudgetAlert, error) {
	row := q.db.QueryRow(ctx, createBudgetAlert,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.SubscriptionID,
		arg.MetricCode,
		arg.BudgetCents,
		arg.ThresholdPct,
	)
	var i BudgetAlert
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SubscriptionID,
		&i.MetricCode,
		&i.BudgetCents,
		&i.ThresholdPct,
		&i.CurrentSpendCents,
		&i.AlertStatus,
		&i.LastAlertedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudgetAlert = `-- name: DeleteBudgetAlert :execrows
DELETE FROM budget_alerts
WHERE provider_id = $1 AND environment_id = $2 AND id = $3
`

type DeleteBudgetAlertParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) DeleteBudgetAlert(ctx context.Context, arg DeleteBudgetAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBudgetAlert, arg.ProviderID, arg.EnvironmentID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMeteredPricingRule = `-- name: DeleteMeteredPricingRule :execrows
DELETE FROM metered_pricing_rules
WHERE provider_id = $1 AND environment_id = $2 AND metric_code = $3
`

type DeleteMeteredPricingRuleParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	MetricCode    string    `json:"metric_code"`
}

func (q *Queries) DeleteMeteredPricingRule(ctx context.Context, arg DeleteMeteredPricingRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMeteredPricingRule, arg.ProviderID, arg.EnvironmentID, arg.MetricCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBudgetAlertByID = `-- name: GetBudgetAlertByID :one
SELECT id, provider_id, environment_id, subscription_id, metric_code, budget_cents, threshold_pct, current_spend_cents, alert_status, last_alerted_at, created_at, updated_at FROM budget_alerts WHERE id = $1
`

func (q *Queries) GetBudgetAlertByID(ctx context.Context, id uuid.UUID) (BudgetAlert, error) {
	row := q.db.QueryRow(ctx, getBudgetAlertByID, id)
	var i BudgetAlert
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SubscriptionID,
		&i.MetricCode,
		&i.BudgetCents,
		&i.ThresholdPct,
		&i.CurrentSpendCents,
		&i.AlertStatus,
		&i.LastAlertedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeteredPricingRule = `-- name: GetMeteredPricingRule :one
SELECT id, provider_id, environment_id, metric_code, pricing_model, base_price_cents, tier_config, minimum_spend_cents, enabled, created_at, updated_at FROM metered_pricing_rules
WHERE provider_id = $1 AND environment_id = $2 AND metric_code = $3
`

type GetMeteredPricingRuleParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	MetricCode    string    `json:"metric_code"`
}

func (q *Queries) GetMeteredPricingRule(ctx context.Context, arg GetMeteredPricingRuleParams) (MeteredPricingRule, error) {
	row := q.db.QueryRow(ctx, getMeteredPricingRule, arg.ProviderID, arg.EnvironmentID, arg.MetricCode)
	var i MeteredPricingRule
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.MetricCode,
		&i.PricingModel,
		&i.BasePriceCents,
		&i.TierConfig,
		&i.MinimumSpendCents,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgetAlerts = `-- name: ListBudgetAlerts :many
SELECT id, provider_id, environment_id, subscription_id, metric_code, budget_cents, threshold_pct, current_spend_cents, alert_status, last_alerted_at, created_at, updated_at FROM budget_alerts
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListBudgetAlertsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListBudgetAlerts(ctx context.Context, arg ListBudgetAlertsParams) ([]BudgetAlert, error) {
	rows, err := q.db.Query(ctx, listBudgetAlerts, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetAlert
	for rows.Next() {
		var i BudgetAlert
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.SubscriptionID,
			&i.MetricCode,
			&i.BudgetCents,
			&i.ThresholdPct,
			&i.CurrentSpendCents,
			&i.AlertStatus,
			&i.LastAlertedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeteredPricingRules = `-- name: ListMeteredPricingRules :many
SELECT id, provider_id, environment_id, metric_code, pricing_model, base_price_cents, tier_config, minimum_spend_cents, enabled, created_at, updated_at FROM metered_pricing_rules
WHERE provider_id = $1 AND environment_id = $2 AND enabled = true
ORDER BY metric_code
`

type ListMeteredPricingRulesParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListMeteredPricingRules(ctx context.Context, arg ListMeteredPricingRulesParams) ([]MeteredPricingRule, error) {
	rows, err := q.db.Query(ctx, listMeteredPricingRules, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeteredPricingRule
	for rows.Next() {
		var i MeteredPricingRule
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.MetricCode,
			&i.PricingModel,
			&i.BasePriceCents,
			&i.TierConfig,
			&i.MinimumSpendCents,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudgetAlertSpend = `-- name: UpdateBudgetAlertSpend :exec
UPDATE budget_alerts
SET current_spend_cents = $2, alert_status = CASE
    WHEN $2 >= budget_cents THEN 'exceeded'
    WHEN $2 >= (budget_cents * threshold_pct / 100) THEN 'warning'
    ELSE 'ok'
END, last_alerted_at = CASE
    WHEN $2 >= (budget_cents * threshold_pct / 100) THEN now()
    ELSE last_alerted_at
END, updated_at = now()
WHERE id = $1
`

type UpdateBudgetAlertSpendParams struct {
	ID                uuid.UUID `json:"id"`
	CurrentSpendCents int64     `json:"current_spend_cents"`
}

func (q *Queries) UpdateBudgetAlertSpend(ctx context.Context, arg UpdateBudgetAlertSpendParams) error {
	_, err := q.db.Exec(ctx, updateBudgetAlertSpend, arg.ID, arg.CurrentSpendCents)
	return err
}

const upsertMeteredPricingRule = `-- name: UpsertMeteredPricingRule :one
INSERT INTO metered_pricing_rules (provider_id, environment_id, metric_code, pricing_model, base_price_cents, tier_config, minimum_spend_cents, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (provider_id, environment_id, metric_code) DO UPDATE
SET pricing_model = EXCLUDED.pricing_model, base_price_cents = EXCLUDED.base_price_cents,
    tier_config = EXCLUDED.tier_config, minimum_spend_cents = EXCLUDED.minimum_spend_cents,
    enabled = EXCLUDED.enabled, updated_at = now()
RETURNING id, provider_id, environment_id, metric_code, pricing_model, base_price_cents, tier_config, minimum_spend_cents, enabled, created_at, updated_at
`

type UpsertMeteredPricingRuleParams struct {
	ProviderID        uuid.UUID `json:"provider_id"`
	EnvironmentID     uuid.UUID `json:"environment_id"`
	MetricCode        string    `json:"metric_code"`
	PricingModel      string    `json:"pricing_model"`
	BasePriceCents    int64     `json:"base_price_cents"`
	TierConfig        []byte    `json:"tier_config"`
	MinimumSpendCents int64     `json:"minimum_spend_cents"`
	Enabled           bool      `json:"enabled"`
}

func (q *Queries) UpsertMeteredPricingRule(ctx context.Context, arg UpsertMeteredPricingRuleParams) (MeteredPricingRule, error) {
	row := q.db.QueryRow(ctx, upsertMeteredPricingRule,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.MetricCode,
		arg.PricingModel,
		arg.BasePriceCents,
		arg.TierConfig,
		arg.MinimumSpendCents,
		arg.Enabled,
	)
	var i MeteredPricingRule
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.MetricCode,
		&i.PricingModel,
		&i.BasePriceCents,
		&i.TierConfig,
		&i.MinimumSpendCents,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
