// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: migration.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeMigrationJob = `-- name: CompleteMigrationJob :one
UPDATE migration_jobs
SET status = 'completed', completed_at = now(), updated_at = now()
WHERE id = $1 AND status = 'importing'
RETURNING id, provider_id, environment_id, source_system, status, dry_run, total_records, processed_records, failed_records, cutover_locked, started_at, completed_at, error_summary, created_by, created_at, updated_at
`

func (q *Queries) CompleteMigrationJob(ctx context.Context, id uuid.UUID) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, completeMigrationJob, id)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SourceSystem,
		&i.Status,
		&i.DryRun,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.FailedRecords,
		&i.CutoverLocked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorSummary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countMigrationRecordsByStatus = `-- name: CountMigrationRecordsByStatus :one
SELECT
    COUNT(*) FILTER (WHERE status = 'pending') AS pending,
    COUNT(*) FILTER (WHERE status = 'valid') AS valid,
    COUNT(*) FILTER (WHERE status = 'invalid') AS invalid,
    COUNT(*) FILTER (WHERE status = 'imported') AS imported,
    COUNT(*) FILTER (WHERE status = 'failed') AS failed
FROM migration_records
WHERE migration_job_id = $1
`

type CountMigrationRecordsByStatusRow struct {
	Pending  int64 `json:"pending"`
	Valid    int64 `json:"valid"`
	Invalid  int64 `json:"invalid"`
	Imported int64 `json:"imported"`
	Failed   int64 `json:"failed"`
}

func (q *Queries) CountMigrationRecordsByStatus(ctx context.Context, migrationJobID uuid.UUID) (CountMigrationRecordsByStatusRow, error) {
	row := q.db.QueryRow(ctx, countMigrationRecordsByStatus, migrationJobID)
	var i CountMigrationRecordsByStatusRow
	err := row.Scan(
		&i.Pending,
		&i.Valid,
		&i.Invalid,
		&i.Imported,
		&i.Failed,
	)
	return i, err
}

const createMigrationJob = `-- name: CreateMigrationJob :one
INSERT INTO migration_jobs (provider_id, environment_id, source_system, dry_run, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider_id, environment_id, source_system, status, dry_run, total_records, processed_records, failed_records, cutover_locked, started_at, completed_at, error_summary, created_by, created_at, updated_at
`

type CreateMigrationJobParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	SourceSystem  string    `json:"source_system"`
	DryRun        bool      `json:"dry_run"`
	CreatedBy     string    `json:"created_by"`
}

func (q *Queries) CreateMigrationJob(ctx context.Context, arg CreateMigrationJobParams) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, createMigrationJob,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.SourceSystem,
		arg.DryRun,
		arg.CreatedBy,
	)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SourceSystem,
		&i.Status,
		&i.DryRun,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.FailedRecords,
		&i.CutoverLocked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorSummary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMigrationRecord = `-- name: CreateMigrationRecord :one
INSERT INTO migration_records (migration_job_id, record_type, external_id, source_data)
VALUES ($1, $2, $3, $4)
ON CONFLICT (migration_job_id, record_type, external_id) DO NOTHING
RETURNING id, migration_job_id, record_type, external_id, status, source_data, target_id, error_message, created_at, updated_at
`

type CreateMigrationRecordParams struct {
	MigrationJobID uuid.UUID `json:"migration_job_id"`
	RecordType     string    `json:"record_type"`
	ExternalID     string    `json:"external_id"`
	SourceData     []byte    `json:"source_data"`
}

func (q *Queries) CreateMigrationRecord(ctx context.Context, arg CreateMigrationRecordParams) (MigrationRecord, error) {
	row := q.db.QueryRow(ctx, createMigrationRecord,
		arg.MigrationJobID,
		arg.RecordType,
		arg.ExternalID,
		arg.SourceData,
	)
	var i MigrationRecord
	err := row.Scan(
		&i.ID,
		&i.MigrationJobID,
		&i.RecordType,
		&i.ExternalID,
		&i.Status,
		&i.SourceData,
		&i.TargetID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failMigrationJob = `-- name: FailMigrationJob :one
UPDATE migration_jobs
SET status = 'failed', error_summary = $2, updated_at = now()
WHERE id = $1
RETURNING id, provider_id, environment_id, source_system, status, dry_run, total_records, processed_records, failed_records, cutover_locked, started_at, completed_at, error_summary, created_by, created_at, updated_at
`

type FailMigrationJobParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorSummary pgtype.Text `json:"error_summary"`
}

func (q *Queries) FailMigrationJob(ctx context.Context, arg FailMigrationJobParams) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, failMigrationJob, arg.ID, arg.ErrorSummary)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SourceSystem,
		&i.Status,
		&i.DryRun,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.FailedRecords,
		&i.CutoverLocked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorSummary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMigrationJobByID = `-- name: GetMigrationJobByID :one
SELECT id, provider_id, environment_id, source_system, status, dry_run, total_records, processed_records, failed_records, cutover_locked, started_at, completed_at, error_summary, created_by, created_at, updated_at FROM migration_jobs WHERE id = $1
`

func (q *Queries) GetMigrationJobByID(ctx context.Context, id uuid.UUID) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, getMigrationJobByID, id)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SourceSystem,
		&i.Status,
		&i.DryRun,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.FailedRecords,
		&i.CutoverLocked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorSummary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMigrationJobByIDForTenant = `-- name: GetMigrationJobByIDForTenant :one
SELECT id, provider_id, environment_id, source_system, status, dry_run, total_records, processed_records, failed_records, cutover_locked, started_at, completed_at, error_summary, created_by, created_at, updated_at FROM migration_jobs
WHERE id = $1 AND provider_id = $2 AND environment_id = $3
`

type GetMigrationJobByIDForTenantParams struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) GetMigrationJobByIDForTenant(ctx context.Context, arg GetMigrationJobByIDForTenantParams) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, getMigrationJobByIDForTenant, arg.ID, arg.ProviderID, arg.EnvironmentID)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SourceSystem,
		&i.Status,
		&i.DryRun,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.FailedRecords,
		&i.CutoverLocked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorSummary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMigrationRecordByExternalID = `-- name: GetMigrationRecordByExternalID :one
SELECT id, migration_job_id, record_type, external_id, status, source_data, target_id, error_message, created_at, updated_at FROM migration_records
WHERE migration_job_id = $1 AND record_type = $2 AND external_id = $3
`

type GetMigrationRecordByExternalIDParams struct {
	MigrationJobID uuid.UUID `json:"migration_job_id"`
	RecordType     string    `json:"record_type"`
	ExternalID     string    `json:"external_id"`
}

func (q *Queries) GetMigrationRecordByExternalID(ctx context.Context, arg GetMigrationRecordByExternalIDParams) (MigrationRecord, error) {
	row := q.db.QueryRow(ctx, getMigrationRecordByExternalID, arg.MigrationJobID, arg.RecordType, arg.ExternalID)
	var i MigrationRecord
	err := row.Scan(
		&i.ID,
		&i.MigrationJobID,
		&i.RecordType,
		&i.ExternalID,
		&i.Status,
		&i.SourceData,
		&i.TargetID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveCutoverLock = `-- name: HasActiveCutoverLock :one
SELECT EXISTS (
    SELECT 1 FROM migration_jobs
    WHERE provider_id = $1 AND environment_id = $2
        AND cutover_locked = true
        AND status NOT IN ('rolled_back')
) AS locked
`

type HasActiveCutoverLockParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) HasActiveCutoverLock(ctx context.Context, arg HasActiveCutoverLockParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveCutoverLock, arg.ProviderID, arg.EnvironmentID)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}

const listInvalidMigrationRecords = `-- name: ListInvalidMigrationRecords :many
SELECT id, migration_job_id, record_type, external_id, status, source_data, target_id, error_message, created_at, updated_at FROM migration_records
WHERE migration_job_id = $1 AND status = 'invalid'
ORDER BY created_at ASC
LIMIT $2
`

type ListInvalidMigrationRecordsParams struct {
	MigrationJobID uuid.UUID `json:"migration_job_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListInvalidMigrationRecords(ctx context.Context, arg ListInvalidMigrationRecordsParams) ([]MigrationRecord, error) {
	rows, err := q.db.Query(ctx, listInvalidMigrationRecords, arg.MigrationJobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationRecord
	for rows.Next() {
		var i MigrationRecord
		if err := rows.Scan(
			&i.ID,
			&i.MigrationJobID,
			&i.RecordType,
			&i.ExternalID,
			&i.Status,
			&i.SourceData,
			&i.TargetID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigrationJobs = `-- name: ListMigrationJobs :many
SELECT id, provider_id, environment_id, source_system, status, dry_run, total_records, processed_records, failed_records, cutover_locked, started_at, completed_at, error_summary, created_by, created_at, updated_at FROM migration_jobs
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListMigrationJobsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListMigrationJobs(ctx context.Context, arg ListMigrationJobsParams) ([]MigrationJob, error) {
	rows, err := q.db.Query(ctx, listMigrationJobs, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationJob
	for rows.Next() {
		var i MigrationJob
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.SourceSystem,
			&i.Status,
			&i.DryRun,
			&i.TotalRecords,
			&i.ProcessedRecords,
			&i.FailedRecords,
			&i.CutoverLocked,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorSummary,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigrationRecords = `-- name: ListMigrationRecords :many
SELECT id, migration_job_id, record_type, external_id, status, source_data, target_id, error_message, created_at, updated_at FROM migration_records
WHERE migration_job_id = $1
ORDER BY created_at ASC
LIMIT $2
`

type ListMigrationRecordsParams struct {
	MigrationJobID uuid.UUID `json:"migration_job_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListMigrationRecords(ctx context.Context, arg ListMigrationRecordsParams) ([]MigrationRecord, error) {
	rows, err := q.db.Query(ctx, listMigrationRecords, arg.MigrationJobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationRecord
	for rows.Next() {
		var i MigrationRecord
		if err := rows.Scan(
			&i.ID,
			&i.MigrationJobID,
			&i.RecordType,
			&i.ExternalID,
			&i.Status,
			&i.SourceData,
			&i.TargetID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMigrationRecords = `-- name: ListPendingMigrationRecords :many
SELECT id, migration_job_id, record_type, external_id, status, source_data, target_id, error_message, created_at, updated_at FROM migration_records
WHERE migration_job_id = $1 AND status IN ('pending', 'valid')
ORDER BY created_at ASC
LIMIT $2
`

type ListPendingMigrationRecordsParams struct {
	MigrationJobID uuid.UUID `json:"migration_job_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListPendingMigrationRecords(ctx context.Context, arg ListPendingMigrationRecordsParams) ([]MigrationRecord, error) {
	rows, err := q.db.Query(ctx, listPendingMigrationRecords, arg.MigrationJobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MigrationRecord
	for rows.Next() {
		var i MigrationRecord
		if err := rows.Scan(
			&i.ID,
			&i.MigrationJobID,
			&i.RecordType,
			&i.ExternalID,
			&i.Status,
			&i.SourceData,
			&i.TargetID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollbackMigrationJob = `-- name: RollbackMigrationJob :one
UPDATE migration_jobs
SET status = 'rolled_back', updated_at = now()
WHERE id = $1 AND status IN ('importing', 'completed', 'failed')
RETURNING id, provider_id, environment_id, source_system, status, dry_run, total_records, processed_records, failed_records, cutover_locked, started_at, completed_at, error_summary, created_by, created_at, updated_at
`

func (q *Queries) RollbackMigrationJob(ctx context.Context, id uuid.UUID) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, rollbackMigrationJob, id)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SourceSystem,
		&i.Status,
		&i.DryRun,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.FailedRecords,
		&i.CutoverLocked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorSummary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rollbackMigrationRecords = `-- name: RollbackMigrationRecords :execrows
UPDATE migration_records
SET status = 'rolled_back', updated_at = now()
WHERE migration_job_id = $1 AND status = 'imported'
`

func (q *Queries) RollbackMigrationRecords(ctx context.Context, migrationJobID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, rollbackMigrationRecords, migrationJobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCutoverLock = `-- name: SetCutoverLock :one
UPDATE migration_jobs
SET cutover_locked = $2, updated_at = now()
WHERE id = $1
RETURNING id, provider_id, environment_id, source_system, status, dry_run, total_records, processed_records, failed_records, cutover_locked, started_at, completed_at, error_summary, created_by, created_at, updated_at
`

type SetCutoverLockParams struct {
	ID            uuid.UUID `json:"id"`
	CutoverLocked bool      `json:"cutover_locked"`
}

func (q *Queries) SetCutoverLock(ctx context.Context, arg SetCutoverLockParams) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, setCutoverLock, arg.ID, arg.CutoverLocked)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SourceSystem,
		&i.Status,
		&i.DryRun,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.FailedRecords,
		&i.CutoverLocked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorSummary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setMigrationJobStarted = `-- name: SetMigrationJobStarted :one
UPDATE migration_jobs
SET status = 'importing', started_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('validated', 'importing')
RETURNING id, provider_id, environment_id, source_system, status, dry_run, total_records, processed_records, failed_records, cutover_locked, started_at, completed_at, error_summary, created_by, created_at, updated_at
`

func (q *Queries) SetMigrationJobStarted(ctx context.Context, id uuid.UUID) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, setMigrationJobStarted, id)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SourceSystem,
		&i.Status,
		&i.DryRun,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.FailedRecords,
		&i.CutoverLocked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorSummary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setMigrationJobTotalRecords = `-- name: SetMigrationJobTotalRecords :exec
UPDATE migration_jobs
SET total_records = total_records + $2, updated_at = now()
WHERE id = $1
`

type SetMigrationJobTotalRecordsParams struct {
	ID           uuid.UUID `json:"id"`
	TotalRecords int32     `json:"total_records"`
}

func (q *Queries) SetMigrationJobTotalRecords(ctx context.Context, arg SetMigrationJobTotalRecordsParams) error {
	_, err := q.db.Exec(ctx, setMigrationJobTotalRecords, arg.ID, arg.TotalRecords)
	return err
}

const setMigrationRecordImported = `-- name: SetMigrationRecordImported :one
UPDATE migration_records
SET status = 'imported', target_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, migration_job_id, record_type, external_id, status, source_data, target_id, error_message, created_at, updated_at
`

type SetMigrationRecordImportedParams struct {
	ID       uuid.UUID     `json:"id"`
	TargetID uuid.NullUUID `json:"target_id"`
}

func (q *Queries) SetMigrationRecordImported(ctx context.Context, arg SetMigrationRecordImportedParams) (MigrationRecord, error) {
	row := q.db.QueryRow(ctx, setMigrationRecordImported, arg.ID, arg.TargetID)
	var i MigrationRecord
	err := row.Scan(
		&i.ID,
		&i.MigrationJobID,
		&i.RecordType,
		&i.ExternalID,
		&i.Status,
		&i.SourceData,
		&i.TargetID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setMigrationRecordStatus = `-- name: SetMigrationRecordStatus :one
UPDATE migration_records
SET status = $2, error_message = $3, updated_at = now()
WHERE id = $1
RETURNING id, migration_job_id, record_type, external_id, status, source_data, target_id, error_message, created_at, updated_at
`

type SetMigrationRecordStatusParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) SetMigrationRecordStatus(ctx context.Context, arg SetMigrationRecordStatusParams) (MigrationRecord, error) {
	row := q.db.QueryRow(ctx, setMigrationRecordStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i MigrationRecord
	err := row.Scan(
		&i.ID,
		&i.MigrationJobID,
		&i.RecordType,
		&i.ExternalID,
		&i.Status,
		&i.SourceData,
		&i.TargetID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMigrationJobProgress = `-- name: UpdateMigrationJobProgress :exec
UPDATE migration_jobs
SET processed_records = $2, failed_records = $3, updated_at = now()
WHERE id = $1
`

type UpdateMigrationJobProgressParams struct {
	ID               uuid.UUID `json:"id"`
	ProcessedRecords int32     `json:"processed_records"`
	FailedRecords    int32     `json:"failed_records"`
}

func (q *Queries) UpdateMigrationJobProgress(ctx context.Context, arg UpdateMigrationJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateMigrationJobProgress, arg.ID, arg.ProcessedRecords, arg.FailedRecords)
	return err
}

const updateMigrationJobStatus = `-- name: UpdateMigrationJobStatus :one
UPDATE migration_jobs
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, provider_id, environment_id, source_system, status, dry_run, total_records, processed_records, failed_records, cutover_locked, started_at, completed_at, error_summary, created_by, created_at, updated_at
`

type UpdateMigrationJobStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateMigrationJobStatus(ctx context.Context, arg UpdateMigrationJobStatusParams) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, updateMigrationJobStatus, arg.ID, arg.Status)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SourceSystem,
		&i.Status,
		&i.DryRun,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.FailedRecords,
		&i.CutoverLocked,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorSummary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
