// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storegen

import (
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID            int64         `json:"id"`
	ProviderID    uuid.NullUUID `json:"provider_id"`
	EnvironmentID uuid.NullUUID `json:"environment_id"`
	ActorType     string        `json:"actor_type"`
	ActorID       string        `json:"actor_id"`
	Action        string        `json:"action"`
	TargetType    pgtype.Text   `json:"target_type"`
	TargetID      pgtype.Text   `json:"target_id"`
	Metadata      []byte        `json:"metadata"`
	RequestID     pgtype.Text   `json:"request_id"`
	CreatedAt     time.Time     `json:"created_at"`
}

type CatalogVersion struct {
	ID            uuid.UUID  `json:"id"`
	ProviderID    uuid.UUID  `json:"provider_id"`
	EnvironmentID uuid.UUID  `json:"environment_id"`
	Version       int32      `json:"version"`
	State         string     `json:"state"`
	CreatedAt     time.Time  `json:"created_at"`
	ValidatedAt   *time.Time `json:"validated_at"`
	PublishedAt   *time.Time `json:"published_at"`
	RetiredAt     *time.Time `json:"retired_at"`
}

type Cell struct {
	ID             uuid.UUID `json:"id"`
	RegionID       uuid.UUID `json:"region_id"`
	Code           string    `json:"code"`
	CellType       string    `json:"cell_type"`
	Status         string    `json:"status"`
	CapacityLimits []byte    `json:"capacity_limits"`
	CreatedAt      time.Time `json:"created_at"`
}

type CommerceAccount struct {
	ID            uuid.UUID     `json:"id"`
	Domain        string        `json:"domain"`
	ProviderID    uuid.NullUUID `json:"provider_id"`
	EnvironmentID uuid.NullUUID `json:"environment_id"`
	DisplayName   string        `json:"display_name"`
	CreatedAt     time.Time     `json:"created_at"`
}

type Credential struct {
	ID            uuid.UUID  `json:"id"`
	ProviderID    uuid.UUID  `json:"provider_id"`
	EnvironmentID uuid.UUID  `json:"environment_id"`
	Name          string     `json:"name"`
	KeyPrefix     string     `json:"key_prefix"`
	KeyHash       string     `json:"key_hash"`
	Scopes        []string   `json:"scopes"`
	AllowedCidrs  []string   `json:"allowed_cidrs"`
	ExpiresAt     *time.Time `json:"expires_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
	LastUsedAt    *time.Time `json:"last_used_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

type CustomerAccount struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ExternalID    string    `json:"external_id"`
	AccountType   string    `json:"account_type"`
	DisplayName   string    `json:"display_name"`
	CreatedAt     time.Time `json:"created_at"`
}

type EntitlementGrant struct {
	ID               uuid.UUID `json:"id"`
	PlanID           uuid.UUID `json:"plan_id"`
	CatalogVersionID uuid.UUID `json:"catalog_version_id"`
	ProviderID       uuid.UUID `json:"provider_id"`
	EnvironmentID    uuid.UUID `json:"environment_id"`
	Key              string    `json:"key"`
	ValueType        string    `json:"value_type"`
	Value            []byte    `json:"value"`
}

type EntitlementOverride struct {
	ID             uuid.UUID  `json:"id"`
	ProviderID     uuid.UUID  `json:"provider_id"`
	EnvironmentID  uuid.UUID  `json:"environment_id"`
	SubscriptionID uuid.UUID  `json:"subscription_id"`
	Key            string     `json:"key"`
	ValueType      string     `json:"value_type"`
	Value          []byte     `json:"value"`
	ExpiresAt      *time.Time `json:"expires_at"`
	Reason         string     `json:"reason"`
	CreatedAt      time.Time  `json:"created_at"`
}

type EntitlementSnapshot struct {
	ID                uuid.UUID `json:"id"`
	ProviderID        uuid.UUID `json:"provider_id"`
	EnvironmentID     uuid.UUID `json:"environment_id"`
	CustomerAccountID uuid.UUID `json:"customer_account_id"`
	SubscriptionID    uuid.UUID `json:"subscription_id"`
	CatalogVersionID  uuid.UUID `json:"catalog_version_id"`
	Payload           []byte    `json:"payload"`
	ComputedAt        time.Time `json:"computed_at"`
}

type Environment struct {
	ID         uuid.UUID `json:"id"`
	ProviderID uuid.UUID `json:"provider_id"`
	Kind       string    `json:"kind"`
	Status     string    `json:"status"`
	Issuer     string    `json:"issuer"`
	CreatedAt  time.Time `json:"created_at"`
}

type InboxEvent struct {
	ID              uuid.UUID  `json:"id"`
	ProviderID      uuid.UUID  `json:"provider_id"`
	EnvironmentID   uuid.UUID  `json:"environment_id"`
	Source          string     `json:"source"`
	ExternalEventID string     `json:"external_event_id"`
	Payload         []byte     `json:"payload"`
	ReceivedAt      time.Time  `json:"received_at"`
	ProcessedAt     *time.Time `json:"processed_at"`
}

type Invoice struct {
	ID                                uuid.UUID     `json:"id"`
	ProviderID                        uuid.UUID     `json:"provider_id"`
	EnvironmentID                     uuid.UUID     `json:"environment_id"`
	LagoID                            string        `json:"lago_id"`
	Number                            string        `json:"number"`
	CustomerAccountID                 uuid.UUID     `json:"customer_account_id"`
	SubscriptionID                    uuid.NullUUID `json:"subscription_id"`
	CatalogVersionID                  uuid.NullUUID `json:"catalog_version_id"`
	IssuingDate                       pgtype.Date   `json:"issuing_date"`
	InvoiceType                       string        `json:"invoice_type"`
	Status                            string        `json:"status"`
	PaymentStatus                     string        `json:"payment_status"`
	Currency                          string        `json:"currency"`
	FeesAmountCents                   int64         `json:"fees_amount_cents"`
	CouponsAmountCents                int64         `json:"coupons_amount_cents"`
	CreditNotesAmountCents            int64         `json:"credit_notes_amount_cents"`
	SubTotalExcludingTaxesAmountCents int64         `json:"sub_total_excluding_taxes_amount_cents"`
	TaxesAmountCents                  int64         `json:"taxes_amount_cents"`
	SubTotalIncludingTaxesAmountCents int64         `json:"sub_total_including_taxes_amount_cents"`
	TotalAmountCents                  int64         `json:"total_amount_cents"`
	FileUrl                           pgtype.Text   `json:"file_url"`
	WebUrl                            pgtype.Text   `json:"web_url"`
	LagoCreatedAt                     *time.Time    `json:"lago_created_at"`
	SyncedAt                          time.Time     `json:"synced_at"`
	FinalizedAt                       *time.Time    `json:"finalized_at"`
	VoidedAt                          *time.Time    `json:"voided_at"`
	CreatedAt                         time.Time     `json:"created_at"`
	UpdatedAt                         time.Time     `json:"updated_at"`
}

type InvoiceLine struct {
	ID                 uuid.UUID     `json:"id"`
	InvoiceID          uuid.UUID     `json:"invoice_id"`
	ProviderID         uuid.UUID     `json:"provider_id"`
	EnvironmentID      uuid.UUID     `json:"environment_id"`
	LagoFeeID          string        `json:"lago_fee_id"`
	MetricCode         string        `json:"metric_code"`
	ItemType           string        `json:"item_type"`
	ItemName           string        `json:"item_name"`
	Units              string        `json:"units"`
	PreciseUnitAmount  string        `json:"precise_unit_amount"`
	AmountCents        int64         `json:"amount_cents"`
	TaxesAmountCents   int64         `json:"taxes_amount_cents"`
	TotalAmountCents   int64         `json:"total_amount_cents"`
	Currency           string        `json:"currency"`
	EventTransactionID pgtype.Text   `json:"event_transaction_id"`
	FromDate           *time.Time    `json:"from_date"`
	ToDate             *time.Time    `json:"to_date"`
	CreatedAt          time.Time     `json:"created_at"`
	MetricID           uuid.NullUUID `json:"metric_id"`
	PriceID            uuid.NullUUID `json:"price_id"`
}

type Metric struct {
	ID               uuid.UUID   `json:"id"`
	CatalogVersionID uuid.UUID   `json:"catalog_version_id"`
	ProviderID       uuid.UUID   `json:"provider_id"`
	EnvironmentID    uuid.UUID   `json:"environment_id"`
	Code             string      `json:"code"`
	Name             string      `json:"name"`
	AggregationType  string      `json:"aggregation_type"`
	FieldName        pgtype.Text `json:"field_name"`
	Billable         bool        `json:"billable"`
}

type OutboxEvent struct {
	ID            uuid.UUID  `json:"id"`
	ProviderID    uuid.UUID  `json:"provider_id"`
	EnvironmentID uuid.UUID  `json:"environment_id"`
	AggregateType string     `json:"aggregate_type"`
	AggregateID   string     `json:"aggregate_id"`
	EventType     string     `json:"event_type"`
	Payload       []byte     `json:"payload"`
	PayloadHash   string     `json:"payload_hash"`
	TransactionID string     `json:"transaction_id"`
	Status        string     `json:"status"`
	Attempts      int32      `json:"attempts"`
	CreatedAt     time.Time  `json:"created_at"`
	PublishedAt   *time.Time `json:"published_at"`
	NextAttemptAt *time.Time `json:"next_attempt_at"`
}

type Plan struct {
	ID               uuid.UUID `json:"id"`
	CatalogVersionID uuid.UUID `json:"catalog_version_id"`
	ProviderID       uuid.UUID `json:"provider_id"`
	EnvironmentID    uuid.UUID `json:"environment_id"`
	Code             string    `json:"code"`
	Name             string    `json:"name"`
	Interval         string    `json:"interval"`
	Currency         string    `json:"currency"`
}

type Price struct {
	ID               uuid.UUID     `json:"id"`
	PlanID           uuid.UUID     `json:"plan_id"`
	CatalogVersionID uuid.UUID     `json:"catalog_version_id"`
	ProviderID       uuid.UUID     `json:"provider_id"`
	EnvironmentID    uuid.UUID     `json:"environment_id"`
	MetricID         uuid.NullUUID `json:"metric_id"`
	ChargeModel      string        `json:"charge_model"`
	Properties       []byte        `json:"properties"`
}

type Provider struct {
	ID             uuid.UUID     `json:"id"`
	Slug           string        `json:"slug"`
	Name           string        `json:"name"`
	HomeRegionID   uuid.UUID     `json:"home_region_id"`
	CellID         uuid.NullUUID `json:"cell_id"`
	LifecycleState string        `json:"lifecycle_state"`
	SlaTier        string        `json:"sla_tier"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type ProviderCapability struct {
	ID         uuid.UUID  `json:"id"`
	ProviderID uuid.UUID  `json:"provider_id"`
	Capability string     `json:"capability"`
	Status     string     `json:"status"`
	GrantedAt  *time.Time `json:"granted_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	GrantedBy  string     `json:"granted_by"`
	Reason     string     `json:"reason"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type PspCredential struct {
	ID                     uuid.UUID   `json:"id"`
	ProviderID             uuid.UUID   `json:"provider_id"`
	EnvironmentID          uuid.UUID   `json:"environment_id"`
	PspType                string      `json:"psp_type"`
	Label                  string      `json:"label"`
	EncryptedApiKey        string      `json:"encrypted_api_key"`
	EncryptedWebhookSecret pgtype.Text `json:"encrypted_webhook_secret"`
	KeyVersion             int32       `json:"key_version"`
	Active                 bool        `json:"active"`
	CreatedAt              time.Time   `json:"created_at"`
	RotatedAt              *time.Time  `json:"rotated_at"`
	RevokedAt              *time.Time  `json:"revoked_at"`
}

type ReconciliationResult struct {
	ID            uuid.UUID `json:"id"`
	CheckName     string    `json:"check_name"`
	Status        string    `json:"status"`
	ExpectedCount int64     `json:"expected_count"`
	ActualCount   int64     `json:"actual_count"`
	DriftCount    int64     `json:"drift_count"`
	Details       []byte    `json:"details"`
	CheckedAt     time.Time `json:"checked_at"`
}

type Region struct {
	ID           uuid.UUID `json:"id"`
	Code         string    `json:"code"`
	Jurisdiction string    `json:"jurisdiction"`
	CreatedAt    time.Time `json:"created_at"`
}

type Subscription struct {
	ID                uuid.UUID  `json:"id"`
	ProviderID        uuid.UUID  `json:"provider_id"`
	EnvironmentID     uuid.UUID  `json:"environment_id"`
	ExternalID        string     `json:"external_id"`
	CustomerAccountID uuid.UUID  `json:"customer_account_id"`
	CatalogVersionID  uuid.UUID  `json:"catalog_version_id"`
	PlanID            uuid.UUID  `json:"plan_id"`
	Status            string     `json:"status"`
	StartedAt         time.Time  `json:"started_at"`
	TerminatedAt      *time.Time `json:"terminated_at"`
}

type UsageEvent struct {
	ID                uuid.UUID     `json:"id"`
	ProviderID        uuid.UUID     `json:"provider_id"`
	EnvironmentID     uuid.UUID     `json:"environment_id"`
	TransactionID     string        `json:"transaction_id"`
	Kind              string        `json:"kind"`
	MetricCode        string        `json:"metric_code"`
	CustomerAccountID uuid.UUID     `json:"customer_account_id"`
	SubscriptionID    uuid.UUID     `json:"subscription_id"`
	EventTimestamp    time.Time     `json:"event_timestamp"`
	Properties        []byte        `json:"properties"`
	PayloadHash       string        `json:"payload_hash"`
	ReversesID        uuid.NullUUID `json:"reverses_id"`
	Reason            pgtype.Text   `json:"reason"`
	CreatedAt         time.Time     `json:"created_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID   `json:"id"`
	EndpointID     uuid.UUID   `json:"endpoint_id"`
	OutboxEventID  uuid.UUID   `json:"outbox_event_id"`
	ProviderID     uuid.UUID   `json:"provider_id"`
	EnvironmentID  uuid.UUID   `json:"environment_id"`
	Status         string      `json:"status"`
	Attempts       int32       `json:"attempts"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ResponseBody   pgtype.Text `json:"response_body"`
	NextAttemptAt  *time.Time  `json:"next_attempt_at"`
	DeliveredAt    *time.Time  `json:"delivered_at"`
	CreatedAt      time.Time   `json:"created_at"`
}

type WebhookEndpoint struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Url           string    `json:"url"`
	Secret        string    `json:"secret"`
	Enabled       bool      `json:"enabled"`
	Events        []string  `json:"events"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
