// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storegen

import (
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID            int64         `json:"id"`
	ProviderID    uuid.NullUUID `json:"provider_id"`
	EnvironmentID uuid.NullUUID `json:"environment_id"`
	ActorType     string        `json:"actor_type"`
	ActorID       string        `json:"actor_id"`
	Action        string        `json:"action"`
	TargetType    pgtype.Text   `json:"target_type"`
	TargetID      pgtype.Text   `json:"target_id"`
	Metadata      []byte        `json:"metadata"`
	RequestID     pgtype.Text   `json:"request_id"`
	CreatedAt     time.Time     `json:"created_at"`
}

type Cell struct {
	ID             uuid.UUID `json:"id"`
	RegionID       uuid.UUID `json:"region_id"`
	Code           string    `json:"code"`
	CellType       string    `json:"cell_type"`
	Status         string    `json:"status"`
	CapacityLimits []byte    `json:"capacity_limits"`
	CreatedAt      time.Time `json:"created_at"`
}

type CommerceAccount struct {
	ID            uuid.UUID     `json:"id"`
	Domain        string        `json:"domain"`
	ProviderID    uuid.NullUUID `json:"provider_id"`
	EnvironmentID uuid.NullUUID `json:"environment_id"`
	DisplayName   string        `json:"display_name"`
	CreatedAt     time.Time     `json:"created_at"`
}

type Credential struct {
	ID            uuid.UUID  `json:"id"`
	ProviderID    uuid.UUID  `json:"provider_id"`
	EnvironmentID uuid.UUID  `json:"environment_id"`
	Name          string     `json:"name"`
	KeyPrefix     string     `json:"key_prefix"`
	KeyHash       string     `json:"key_hash"`
	Scopes        []string   `json:"scopes"`
	AllowedCidrs  []string   `json:"allowed_cidrs"`
	ExpiresAt     *time.Time `json:"expires_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
	LastUsedAt    *time.Time `json:"last_used_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

type Environment struct {
	ID         uuid.UUID `json:"id"`
	ProviderID uuid.UUID `json:"provider_id"`
	Kind       string    `json:"kind"`
	Status     string    `json:"status"`
	Issuer     string    `json:"issuer"`
	CreatedAt  time.Time `json:"created_at"`
}

type InboxEvent struct {
	ID              uuid.UUID  `json:"id"`
	ProviderID      uuid.UUID  `json:"provider_id"`
	EnvironmentID   uuid.UUID  `json:"environment_id"`
	Source          string     `json:"source"`
	ExternalEventID string     `json:"external_event_id"`
	Payload         []byte     `json:"payload"`
	ReceivedAt      time.Time  `json:"received_at"`
	ProcessedAt     *time.Time `json:"processed_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID  `json:"id"`
	ProviderID    uuid.UUID  `json:"provider_id"`
	EnvironmentID uuid.UUID  `json:"environment_id"`
	AggregateType string     `json:"aggregate_type"`
	AggregateID   string     `json:"aggregate_id"`
	EventType     string     `json:"event_type"`
	Payload       []byte     `json:"payload"`
	PayloadHash   string     `json:"payload_hash"`
	TransactionID string     `json:"transaction_id"`
	Status        string     `json:"status"`
	Attempts      int32      `json:"attempts"`
	CreatedAt     time.Time  `json:"created_at"`
	PublishedAt   *time.Time `json:"published_at"`
}

type Provider struct {
	ID             uuid.UUID     `json:"id"`
	Slug           string        `json:"slug"`
	Name           string        `json:"name"`
	HomeRegionID   uuid.UUID     `json:"home_region_id"`
	CellID         uuid.NullUUID `json:"cell_id"`
	LifecycleState string        `json:"lifecycle_state"`
	SlaTier        string        `json:"sla_tier"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type Region struct {
	ID           uuid.UUID `json:"id"`
	Code         string    `json:"code"`
	Jurisdiction string    `json:"jurisdiction"`
	CreatedAt    time.Time `json:"created_at"`
}
