// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storegen

import (
	"encoding/json"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AnalyticsChurn struct {
	ProviderID            uuid.UUID       `json:"provider_id"`
	ChurnMonth            pgtype.Interval `json:"churn_month"`
	ChurnedSubscriptions  int64           `json:"churned_subscriptions"`
	RetainedSubscriptions int64           `json:"retained_subscriptions"`
}

type AnalyticsConversion struct {
	ProviderID                uuid.UUID       `json:"provider_id"`
	SignupMonth               pgtype.Interval `json:"signup_month"`
	NewCustomers              int64           `json:"new_customers"`
	CustomersWithSubscription int64           `json:"customers_with_subscription"`
	ActiveSubscriptions       int64           `json:"active_subscriptions"`
}

type AnalyticsMau struct {
	ProviderID       uuid.UUID       `json:"provider_id"`
	Month            pgtype.Interval `json:"month"`
	ActiveCustomers  int64           `json:"active_customers"`
	UniqueMetrics    int64           `json:"unique_metrics"`
	TotalUsageEvents int64           `json:"total_usage_events"`
}

type AnalyticsRevenueSummary struct {
	ProviderID          uuid.UUID       `json:"provider_id"`
	ProviderName        string          `json:"provider_name"`
	Month               pgtype.Interval `json:"month"`
	InvoiceCount        int64           `json:"invoice_count"`
	SubscriptionCount   int64           `json:"subscription_count"`
	TotalRevenueCents   int64           `json:"total_revenue_cents"`
	AvgInvoiceLineCents float64         `json:"avg_invoice_line_cents"`
}

type AnalyticsUsageAnomaly struct {
	ProviderID uuid.UUID       `json:"provider_id"`
	MetricCode string          `json:"metric_code"`
	Day        pgtype.Interval `json:"day"`
	EventCount int64           `json:"event_count"`
	Avg7d      float64         `json:"avg_7d"`
	IsAnomaly  bool            `json:"is_anomaly"`
}

type AnalyticsUsageBreakdown struct {
	ProviderID    uuid.UUID       `json:"provider_id"`
	MetricCode    string          `json:"metric_code"`
	Day           pgtype.Interval `json:"day"`
	EventCount    int64           `json:"event_count"`
	TotalQuantity int64           `json:"total_quantity"`
}

type AuditChainAnchor struct {
	ID          int64       `json:"id"`
	TailEventID int64       `json:"tail_event_id"`
	TailHash    string      `json:"tail_hash"`
	Operator    string      `json:"operator"`
	CreatedAt   time.Time   `json:"created_at"`
	PublishedAt *time.Time  `json:"published_at"`
	ObjectKey   pgtype.Text `json:"object_key"`
}

type AuditChainTail struct {
	ID              int32       `json:"id"`
	TailHash        pgtype.Text `json:"tail_hash"`
	TailEventID     pgtype.Int8 `json:"tail_event_id"`
	PrunedThroughID pgtype.Int8 `json:"pruned_through_id"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type AuditEvent struct {
	ID            int64         `json:"id"`
	ProviderID    uuid.NullUUID `json:"provider_id"`
	EnvironmentID uuid.NullUUID `json:"environment_id"`
	ActorType     string        `json:"actor_type"`
	ActorID       string        `json:"actor_id"`
	Action        string        `json:"action"`
	TargetType    pgtype.Text   `json:"target_type"`
	TargetID      pgtype.Text   `json:"target_id"`
	Metadata      []byte        `json:"metadata"`
	RequestID     pgtype.Text   `json:"request_id"`
	CreatedAt     time.Time     `json:"created_at"`
	PrevHash      pgtype.Text   `json:"prev_hash"`
	EventHash     pgtype.Text   `json:"event_hash"`
}

type AuthSessionVault struct {
	ID           string    `json:"id"`
	UserSub      string    `json:"user_sub"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	Roles        []byte    `json:"roles"`
	WorkspaceID  string    `json:"workspace_id"`
	Env          string    `json:"env"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	TokenExp     int64     `json:"token_exp"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type BudgetAlert struct {
	ID                uuid.UUID     `json:"id"`
	ProviderID        uuid.UUID     `json:"provider_id"`
	EnvironmentID     uuid.UUID     `json:"environment_id"`
	SubscriptionID    uuid.NullUUID `json:"subscription_id"`
	MetricCode        pgtype.Text   `json:"metric_code"`
	BudgetCents       int64         `json:"budget_cents"`
	ThresholdPct      float64       `json:"threshold_pct"`
	CurrentSpendCents int64         `json:"current_spend_cents"`
	AlertStatus       string        `json:"alert_status"`
	LastAlertedAt     *time.Time    `json:"last_alerted_at"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type CatalogVersion struct {
	ID            uuid.UUID  `json:"id"`
	ProviderID    uuid.UUID  `json:"provider_id"`
	EnvironmentID uuid.UUID  `json:"environment_id"`
	Version       int32      `json:"version"`
	State         string     `json:"state"`
	CreatedAt     time.Time  `json:"created_at"`
	ValidatedAt   *time.Time `json:"validated_at"`
	PublishedAt   *time.Time `json:"published_at"`
	RetiredAt     *time.Time `json:"retired_at"`
}

type Cell struct {
	ID             uuid.UUID `json:"id"`
	RegionID       uuid.UUID `json:"region_id"`
	Code           string    `json:"code"`
	CellType       string    `json:"cell_type"`
	Status         string    `json:"status"`
	CapacityLimits []byte    `json:"capacity_limits"`
	CreatedAt      time.Time `json:"created_at"`
}

type CellFailover struct {
	ID             uuid.UUID  `json:"id"`
	ProviderID     uuid.UUID  `json:"provider_id"`
	FromCellID     uuid.UUID  `json:"from_cell_id"`
	ToCellID       uuid.UUID  `json:"to_cell_id"`
	Status         string     `json:"status"`
	Reason         string     `json:"reason"`
	InitiatedBy    string     `json:"initiated_by"`
	FencingToken   string     `json:"fencing_token"`
	ReplayedUsage  int32      `json:"replayed_usage"`
	ReplayedOutbox int32      `json:"replayed_outbox"`
	StartedAt      time.Time  `json:"started_at"`
	CompletedAt    *time.Time `json:"completed_at"`
}

type CellMigration struct {
	ID                uuid.UUID   `json:"id"`
	ProviderID        uuid.UUID   `json:"provider_id"`
	FromCellID        uuid.UUID   `json:"from_cell_id"`
	ToCellID          uuid.UUID   `json:"to_cell_id"`
	Status            string      `json:"status"`
	ScheduledAt       *time.Time  `json:"scheduled_at"`
	PrecheckPassed    bool        `json:"precheck_passed"`
	DataIntegrityHash pgtype.Text `json:"data_integrity_hash"`
	RecordCount       int32       `json:"record_count"`
	Reason            string      `json:"reason"`
	InitiatedBy       string      `json:"initiated_by"`
	StartedAt         *time.Time  `json:"started_at"`
	CompletedAt       *time.Time  `json:"completed_at"`
	ErrorMessage      pgtype.Text `json:"error_message"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type CommerceAccount struct {
	ID            uuid.UUID     `json:"id"`
	Domain        string        `json:"domain"`
	ProviderID    uuid.NullUUID `json:"provider_id"`
	EnvironmentID uuid.NullUUID `json:"environment_id"`
	DisplayName   string        `json:"display_name"`
	CreatedAt     time.Time     `json:"created_at"`
}

type Credential struct {
	ID            uuid.UUID  `json:"id"`
	ProviderID    uuid.UUID  `json:"provider_id"`
	EnvironmentID uuid.UUID  `json:"environment_id"`
	Name          string     `json:"name"`
	KeyPrefix     string     `json:"key_prefix"`
	KeyHash       string     `json:"key_hash"`
	Scopes        []string   `json:"scopes"`
	AllowedCidrs  []string   `json:"allowed_cidrs"`
	ExpiresAt     *time.Time `json:"expires_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
	LastUsedAt    *time.Time `json:"last_used_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

type CustomDomain struct {
	ID                uuid.UUID  `json:"id"`
	ProviderID        uuid.UUID  `json:"provider_id"`
	EnvironmentID     uuid.UUID  `json:"environment_id"`
	Domain            string     `json:"domain"`
	VerificationToken string     `json:"verification_token"`
	Status            string     `json:"status"`
	VerifiedAt        *time.Time `json:"verified_at"`
	RevokedAt         *time.Time `json:"revoked_at"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

type CustomerAccount struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ExternalID    string    `json:"external_id"`
	AccountType   string    `json:"account_type"`
	DisplayName   string    `json:"display_name"`
	CreatedAt     time.Time `json:"created_at"`
}

type DataExport struct {
	ID            uuid.UUID   `json:"id"`
	ProviderID    uuid.UUID   `json:"provider_id"`
	EnvironmentID uuid.UUID   `json:"environment_id"`
	Status        string      `json:"status"`
	ExportType    string      `json:"export_type"`
	DataHash      pgtype.Text `json:"data_hash"`
	ExportData    []byte      `json:"export_data"`
	RecordCount   int32       `json:"record_count"`
	ErrorMessage  pgtype.Text `json:"error_message"`
	CreatedAt     time.Time   `json:"created_at"`
	CompletedAt   *time.Time  `json:"completed_at"`
}

type DeletionProof struct {
	ID             uuid.UUID `json:"id"`
	ProviderID     uuid.UUID `json:"provider_id"`
	EnvironmentID  uuid.UUID `json:"environment_id"`
	DataHash       string    `json:"data_hash"`
	RecordCount    int32     `json:"record_count"`
	DeletedAt      time.Time `json:"deleted_at"`
	ProofSignature string    `json:"proof_signature"`
	CreatedAt      time.Time `json:"created_at"`
}

type EntitlementGrant struct {
	ID               uuid.UUID       `json:"id"`
	PlanID           uuid.UUID       `json:"plan_id"`
	CatalogVersionID uuid.UUID       `json:"catalog_version_id"`
	ProviderID       uuid.UUID       `json:"provider_id"`
	EnvironmentID    uuid.UUID       `json:"environment_id"`
	Key              string          `json:"key"`
	ValueType        string          `json:"value_type"`
	Value            json.RawMessage `json:"value"`
}

type EntitlementOverride struct {
	ID             uuid.UUID       `json:"id"`
	ProviderID     uuid.UUID       `json:"provider_id"`
	EnvironmentID  uuid.UUID       `json:"environment_id"`
	SubscriptionID uuid.UUID       `json:"subscription_id"`
	Key            string          `json:"key"`
	ValueType      string          `json:"value_type"`
	Value          json.RawMessage `json:"value"`
	ExpiresAt      *time.Time      `json:"expires_at"`
	Reason         string          `json:"reason"`
	CreatedAt      time.Time       `json:"created_at"`
}

type EntitlementSnapshot struct {
	ID                uuid.UUID `json:"id"`
	ProviderID        uuid.UUID `json:"provider_id"`
	EnvironmentID     uuid.UUID `json:"environment_id"`
	CustomerAccountID uuid.UUID `json:"customer_account_id"`
	SubscriptionID    uuid.UUID `json:"subscription_id"`
	CatalogVersionID  uuid.UUID `json:"catalog_version_id"`
	Payload           []byte    `json:"payload"`
	ComputedAt        time.Time `json:"computed_at"`
}

type Environment struct {
	ID         uuid.UUID `json:"id"`
	ProviderID uuid.UUID `json:"provider_id"`
	Kind       string    `json:"kind"`
	Status     string    `json:"status"`
	Issuer     string    `json:"issuer"`
	CreatedAt  time.Time `json:"created_at"`
}

type IdempotencyKey struct {
	ID             uuid.UUID   `json:"id"`
	Scope          string      `json:"scope"`
	KeyHash        []byte      `json:"key_hash"`
	Method         string      `json:"method"`
	Path           string      `json:"path"`
	Status         string      `json:"status"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ContentType    pgtype.Text `json:"content_type"`
	ResponseBody   []byte      `json:"response_body"`
	RequestID      string      `json:"request_id"`
	CreatedAt      time.Time   `json:"created_at"`
	ExpiresAt      time.Time   `json:"expires_at"`
}

type InboxEvent struct {
	ID              uuid.UUID  `json:"id"`
	ProviderID      uuid.UUID  `json:"provider_id"`
	EnvironmentID   uuid.UUID  `json:"environment_id"`
	Source          string     `json:"source"`
	ExternalEventID string     `json:"external_event_id"`
	Payload         []byte     `json:"payload"`
	ReceivedAt      time.Time  `json:"received_at"`
	ProcessedAt     *time.Time `json:"processed_at"`
}

type Invoice struct {
	ID                                uuid.UUID     `json:"id"`
	ProviderID                        uuid.UUID     `json:"provider_id"`
	EnvironmentID                     uuid.UUID     `json:"environment_id"`
	LagoID                            string        `json:"lago_id"`
	Number                            string        `json:"number"`
	CustomerAccountID                 uuid.UUID     `json:"customer_account_id"`
	SubscriptionID                    uuid.NullUUID `json:"subscription_id"`
	CatalogVersionID                  uuid.NullUUID `json:"catalog_version_id"`
	IssuingDate                       pgtype.Date   `json:"issuing_date"`
	InvoiceType                       string        `json:"invoice_type"`
	Status                            string        `json:"status"`
	PaymentStatus                     string        `json:"payment_status"`
	Currency                          string        `json:"currency"`
	FeesAmountCents                   int64         `json:"fees_amount_cents"`
	CouponsAmountCents                int64         `json:"coupons_amount_cents"`
	CreditNotesAmountCents            int64         `json:"credit_notes_amount_cents"`
	SubTotalExcludingTaxesAmountCents int64         `json:"sub_total_excluding_taxes_amount_cents"`
	TaxesAmountCents                  int64         `json:"taxes_amount_cents"`
	SubTotalIncludingTaxesAmountCents int64         `json:"sub_total_including_taxes_amount_cents"`
	TotalAmountCents                  int64         `json:"total_amount_cents"`
	FileUrl                           pgtype.Text   `json:"file_url"`
	WebUrl                            pgtype.Text   `json:"web_url"`
	LagoCreatedAt                     *time.Time    `json:"lago_created_at"`
	SyncedAt                          time.Time     `json:"synced_at"`
	FinalizedAt                       *time.Time    `json:"finalized_at"`
	VoidedAt                          *time.Time    `json:"voided_at"`
	CreatedAt                         time.Time     `json:"created_at"`
	UpdatedAt                         time.Time     `json:"updated_at"`
}

type InvoiceLine struct {
	ID                 uuid.UUID     `json:"id"`
	InvoiceID          uuid.UUID     `json:"invoice_id"`
	ProviderID         uuid.UUID     `json:"provider_id"`
	EnvironmentID      uuid.UUID     `json:"environment_id"`
	LagoFeeID          string        `json:"lago_fee_id"`
	MetricCode         string        `json:"metric_code"`
	ItemType           string        `json:"item_type"`
	ItemName           string        `json:"item_name"`
	Units              string        `json:"units"`
	PreciseUnitAmount  string        `json:"precise_unit_amount"`
	AmountCents        int64         `json:"amount_cents"`
	TaxesAmountCents   int64         `json:"taxes_amount_cents"`
	TotalAmountCents   int64         `json:"total_amount_cents"`
	Currency           string        `json:"currency"`
	EventTransactionID pgtype.Text   `json:"event_transaction_id"`
	FromDate           *time.Time    `json:"from_date"`
	ToDate             *time.Time    `json:"to_date"`
	CreatedAt          time.Time     `json:"created_at"`
	MetricID           uuid.NullUUID `json:"metric_id"`
	PriceID            uuid.NullUUID `json:"price_id"`
}

type MeteredPricingRule struct {
	ID                uuid.UUID `json:"id"`
	ProviderID        uuid.UUID `json:"provider_id"`
	EnvironmentID     uuid.UUID `json:"environment_id"`
	MetricCode        string    `json:"metric_code"`
	PricingModel      string    `json:"pricing_model"`
	BasePriceCents    int64     `json:"base_price_cents"`
	TierConfig        []byte    `json:"tier_config"`
	MinimumSpendCents int64     `json:"minimum_spend_cents"`
	Enabled           bool      `json:"enabled"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Metric struct {
	ID               uuid.UUID   `json:"id"`
	CatalogVersionID uuid.UUID   `json:"catalog_version_id"`
	ProviderID       uuid.UUID   `json:"provider_id"`
	EnvironmentID    uuid.UUID   `json:"environment_id"`
	Code             string      `json:"code"`
	Name             string      `json:"name"`
	AggregationType  string      `json:"aggregation_type"`
	FieldName        pgtype.Text `json:"field_name"`
	Billable         bool        `json:"billable"`
}

type MigrationJob struct {
	ID               uuid.UUID   `json:"id"`
	ProviderID       uuid.UUID   `json:"provider_id"`
	EnvironmentID    uuid.UUID   `json:"environment_id"`
	SourceSystem     string      `json:"source_system"`
	Status           string      `json:"status"`
	DryRun           bool        `json:"dry_run"`
	TotalRecords     int32       `json:"total_records"`
	ProcessedRecords int32       `json:"processed_records"`
	FailedRecords    int32       `json:"failed_records"`
	CutoverLocked    bool        `json:"cutover_locked"`
	StartedAt        *time.Time  `json:"started_at"`
	CompletedAt      *time.Time  `json:"completed_at"`
	ErrorSummary     pgtype.Text `json:"error_summary"`
	CreatedBy        string      `json:"created_by"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type MigrationRecord struct {
	ID             uuid.UUID     `json:"id"`
	MigrationJobID uuid.UUID     `json:"migration_job_id"`
	RecordType     string        `json:"record_type"`
	ExternalID     string        `json:"external_id"`
	Status         string        `json:"status"`
	SourceData     []byte        `json:"source_data"`
	TargetID       uuid.NullUUID `json:"target_id"`
	ErrorMessage   pgtype.Text   `json:"error_message"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type NotificationConfig struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Channel       string    `json:"channel"`
	ProviderType  string    `json:"provider_type"`
	ConfigEnc     []byte    `json:"config_enc"`
	FromAddress   string    `json:"from_address"`
	Enabled       bool      `json:"enabled"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID   `json:"id"`
	ProviderID    uuid.UUID   `json:"provider_id"`
	EnvironmentID uuid.UUID   `json:"environment_id"`
	AggregateType string      `json:"aggregate_type"`
	AggregateID   string      `json:"aggregate_id"`
	EventType     string      `json:"event_type"`
	Payload       []byte      `json:"payload"`
	PayloadHash   string      `json:"payload_hash"`
	TransactionID string      `json:"transaction_id"`
	Status        string      `json:"status"`
	Attempts      int32       `json:"attempts"`
	CreatedAt     time.Time   `json:"created_at"`
	PublishedAt   *time.Time  `json:"published_at"`
	NextAttemptAt *time.Time  `json:"next_attempt_at"`
	LastError     pgtype.Text `json:"last_error"`
}

type Plan struct {
	ID               uuid.UUID `json:"id"`
	CatalogVersionID uuid.UUID `json:"catalog_version_id"`
	ProviderID       uuid.UUID `json:"provider_id"`
	EnvironmentID    uuid.UUID `json:"environment_id"`
	Code             string    `json:"code"`
	Name             string    `json:"name"`
	Interval         string    `json:"interval"`
	Currency         string    `json:"currency"`
}

type Price struct {
	ID               uuid.UUID       `json:"id"`
	PlanID           uuid.UUID       `json:"plan_id"`
	CatalogVersionID uuid.UUID       `json:"catalog_version_id"`
	ProviderID       uuid.UUID       `json:"provider_id"`
	EnvironmentID    uuid.UUID       `json:"environment_id"`
	MetricID         uuid.NullUUID   `json:"metric_id"`
	ChargeModel      string          `json:"charge_model"`
	Properties       json.RawMessage `json:"properties"`
}

type Provider struct {
	ID             uuid.UUID     `json:"id"`
	Slug           string        `json:"slug"`
	Name           string        `json:"name"`
	HomeRegionID   uuid.NullUUID `json:"home_region_id"`
	CellID         uuid.NullUUID `json:"cell_id"`
	LifecycleState string        `json:"lifecycle_state"`
	SlaTier        string        `json:"sla_tier"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type ProviderAuthConfig struct {
	ID                  uuid.UUID `json:"id"`
	ProviderID          uuid.UUID `json:"provider_id"`
	EnvironmentID       uuid.UUID `json:"environment_id"`
	ZitadelProjectID    string    `json:"zitadel_project_id"`
	ZitadelAppID        string    `json:"zitadel_app_id"`
	ZitadelClientID     string    `json:"zitadel_client_id"`
	ZitadelClientSecret string    `json:"zitadel_client_secret"`
	Enabled             bool      `json:"enabled"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
	RedirectUris        []byte    `json:"redirect_uris"`
	Name                string    `json:"name"`
}

type ProviderCapability struct {
	ID         uuid.UUID  `json:"id"`
	ProviderID uuid.UUID  `json:"provider_id"`
	Capability string     `json:"capability"`
	Status     string     `json:"status"`
	GrantedAt  *time.Time `json:"granted_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	GrantedBy  string     `json:"granted_by"`
	Reason     string     `json:"reason"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type ProviderRiskReview struct {
	ID         uuid.UUID `json:"id"`
	ProviderID uuid.UUID `json:"provider_id"`
	RiskScore  int16     `json:"risk_score"`
	Checks     []byte    `json:"checks"`
	Decision   string    `json:"decision"`
	Reason     string    `json:"reason"`
	ReviewedBy string    `json:"reviewed_by"`
	ReviewedAt time.Time `json:"reviewed_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type PspCredential struct {
	ID                     uuid.UUID   `json:"id"`
	ProviderID             uuid.UUID   `json:"provider_id"`
	EnvironmentID          uuid.UUID   `json:"environment_id"`
	PspType                string      `json:"psp_type"`
	Label                  string      `json:"label"`
	EncryptedApiKey        string      `json:"encrypted_api_key"`
	EncryptedWebhookSecret pgtype.Text `json:"encrypted_webhook_secret"`
	KeyVersion             int32       `json:"key_version"`
	Active                 bool        `json:"active"`
	CreatedAt              time.Time   `json:"created_at"`
	RotatedAt              *time.Time  `json:"rotated_at"`
	RevokedAt              *time.Time  `json:"revoked_at"`
}

type QuotaLimit struct {
	ID             uuid.UUID `json:"id"`
	ProviderID     uuid.UUID `json:"provider_id"`
	EnvironmentID  uuid.UUID `json:"environment_id"`
	SubscriptionID uuid.UUID `json:"subscription_id"`
	QuotaKey       string    `json:"quota_key"`
	LimitValue     int64     `json:"limit_value"`
	PeriodType     string    `json:"period_type"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type QuotaReservation struct {
	ID             uuid.UUID  `json:"id"`
	ProviderID     uuid.UUID  `json:"provider_id"`
	EnvironmentID  uuid.UUID  `json:"environment_id"`
	SubscriptionID uuid.UUID  `json:"subscription_id"`
	QuotaKey       string     `json:"quota_key"`
	Amount         int64      `json:"amount"`
	Status         string     `json:"status"`
	ReservationID  string     `json:"reservation_id"`
	ExpiresAt      *time.Time `json:"expires_at"`
	CreatedAt      time.Time  `json:"created_at"`
	CommittedAt    *time.Time `json:"committed_at"`
	ReleasedAt     *time.Time `json:"released_at"`
}

type ReconciliationResult struct {
	ID            uuid.UUID `json:"id"`
	CheckName     string    `json:"check_name"`
	Status        string    `json:"status"`
	ExpectedCount int64     `json:"expected_count"`
	ActualCount   int64     `json:"actual_count"`
	DriftCount    int64     `json:"drift_count"`
	Details       []byte    `json:"details"`
	CheckedAt     time.Time `json:"checked_at"`
}

type Region struct {
	ID           uuid.UUID `json:"id"`
	Code         string    `json:"code"`
	Jurisdiction string    `json:"jurisdiction"`
	CreatedAt    time.Time `json:"created_at"`
}

type ScimGroup struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ExternalID    string    `json:"external_id"`
	DisplayName   string    `json:"display_name"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ScimGroupMember struct {
	ID        uuid.UUID `json:"id"`
	GroupID   uuid.UUID `json:"group_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ScimUser struct {
	ID            uuid.UUID     `json:"id"`
	ProviderID    uuid.UUID     `json:"provider_id"`
	EnvironmentID uuid.UUID     `json:"environment_id"`
	ExternalID    string        `json:"external_id"`
	DisplayName   string        `json:"display_name"`
	Email         string        `json:"email"`
	Active        bool          `json:"active"`
	CustomerID    uuid.NullUUID `json:"customer_id"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

type SlaTier struct {
	ID               uuid.UUID `json:"id"`
	ProviderID       uuid.UUID `json:"provider_id"`
	EnvironmentID    uuid.UUID `json:"environment_id"`
	Code             string    `json:"code"`
	Name             string    `json:"name"`
	UptimeSla        float64   `json:"uptime_sla"`
	PriorityLevel    int32     `json:"priority_level"`
	ReservedCapacity []byte    `json:"reserved_capacity"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Subscription struct {
	ID                uuid.UUID  `json:"id"`
	ProviderID        uuid.UUID  `json:"provider_id"`
	EnvironmentID     uuid.UUID  `json:"environment_id"`
	ExternalID        string     `json:"external_id"`
	CustomerAccountID uuid.UUID  `json:"customer_account_id"`
	CatalogVersionID  uuid.UUID  `json:"catalog_version_id"`
	PlanID            uuid.UUID  `json:"plan_id"`
	Status            string     `json:"status"`
	StartedAt         time.Time  `json:"started_at"`
	TerminatedAt      *time.Time `json:"terminated_at"`
}

type SupportSession struct {
	ID              uuid.UUID   `json:"id"`
	ProviderID      uuid.UUID   `json:"provider_id"`
	EnvironmentID   uuid.UUID   `json:"environment_id"`
	AccessType      string      `json:"access_type"`
	Status          string      `json:"status"`
	RequestedBy     string      `json:"requested_by"`
	Reason          string      `json:"reason"`
	RequestedScopes []string    `json:"requested_scopes"`
	ApprovedBy      pgtype.Text `json:"approved_by"`
	SecondApprover  pgtype.Text `json:"second_approver"`
	GrantedAt       *time.Time  `json:"granted_at"`
	ExpiresAt       time.Time   `json:"expires_at"`
	RevokedAt       *time.Time  `json:"revoked_at"`
	RevokedBy       pgtype.Text `json:"revoked_by"`
	RevokeReason    pgtype.Text `json:"revoke_reason"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type TeamMember struct {
	ID            uuid.UUID     `json:"id"`
	ProviderID    uuid.UUID     `json:"provider_id"`
	EnvironmentID uuid.UUID     `json:"environment_id"`
	Email         string        `json:"email"`
	DisplayName   string        `json:"display_name"`
	Role          string        `json:"role"`
	Status        string        `json:"status"`
	CredentialID  uuid.NullUUID `json:"credential_id"`
	InvitedBy     string        `json:"invited_by"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

type UsageEvent struct {
	ID                uuid.UUID     `json:"id"`
	ProviderID        uuid.UUID     `json:"provider_id"`
	EnvironmentID     uuid.UUID     `json:"environment_id"`
	TransactionID     string        `json:"transaction_id"`
	Kind              string        `json:"kind"`
	MetricCode        string        `json:"metric_code"`
	CustomerAccountID uuid.UUID     `json:"customer_account_id"`
	SubscriptionID    uuid.UUID     `json:"subscription_id"`
	EventTimestamp    time.Time     `json:"event_timestamp"`
	Properties        []byte        `json:"properties"`
	PayloadHash       string        `json:"payload_hash"`
	ReversesID        uuid.NullUUID `json:"reverses_id"`
	Reason            pgtype.Text   `json:"reason"`
	CreatedAt         time.Time     `json:"created_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID   `json:"id"`
	EndpointID     uuid.UUID   `json:"endpoint_id"`
	OutboxEventID  uuid.UUID   `json:"outbox_event_id"`
	ProviderID     uuid.UUID   `json:"provider_id"`
	EnvironmentID  uuid.UUID   `json:"environment_id"`
	Status         string      `json:"status"`
	Attempts       int32       `json:"attempts"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ResponseBody   pgtype.Text `json:"response_body"`
	NextAttemptAt  *time.Time  `json:"next_attempt_at"`
	DeliveredAt    *time.Time  `json:"delivered_at"`
	CreatedAt      time.Time   `json:"created_at"`
}

type WebhookEndpoint struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Url           string    `json:"url"`
	Secret        string    `json:"secret"`
	Enabled       bool      `json:"enabled"`
	Events        []string  `json:"events"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Workspace struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedBy string    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WorkspaceMember struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserSub     string    `json:"user_sub"`
	Role        string    `json:"role"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
