// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notifications.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
)

const deleteNotificationConfig = `-- name: DeleteNotificationConfig :execrows
DELETE FROM notification_configs
WHERE provider_id = $1 AND environment_id = $2 AND channel = $3
`

type DeleteNotificationConfigParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Channel       string    `json:"channel"`
}

func (q *Queries) DeleteNotificationConfig(ctx context.Context, arg DeleteNotificationConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationConfig, arg.ProviderID, arg.EnvironmentID, arg.Channel)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationConfig = `-- name: GetNotificationConfig :one
SELECT id, provider_id, environment_id, channel, provider_type, config_enc, from_address, enabled, created_at, updated_at FROM notification_configs
WHERE provider_id = $1 AND environment_id = $2 AND channel = $3
`

type GetNotificationConfigParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Channel       string    `json:"channel"`
}

func (q *Queries) GetNotificationConfig(ctx context.Context, arg GetNotificationConfigParams) (NotificationConfig, error) {
	row := q.db.QueryRow(ctx, getNotificationConfig, arg.ProviderID, arg.EnvironmentID, arg.Channel)
	var i NotificationConfig
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Channel,
		&i.ProviderType,
		&i.ConfigEnc,
		&i.FromAddress,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllNotificationConfigCiphertexts = `-- name: ListAllNotificationConfigCiphertexts :many
SELECT id, config_enc FROM notification_configs
ORDER BY id
LIMIT $1
`

type ListAllNotificationConfigCiphertextsRow struct {
	ID        uuid.UUID `json:"id"`
	ConfigEnc []byte    `json:"config_enc"`
}

// Operator-only view used by the re-encryption worker.
func (q *Queries) ListAllNotificationConfigCiphertexts(ctx context.Context, limit int32) ([]ListAllNotificationConfigCiphertextsRow, error) {
	rows, err := q.db.Query(ctx, listAllNotificationConfigCiphertexts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllNotificationConfigCiphertextsRow
	for rows.Next() {
		var i ListAllNotificationConfigCiphertextsRow
		if err := rows.Scan(&i.ID, &i.ConfigEnc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationConfigs = `-- name: ListNotificationConfigs :many
SELECT id, provider_id, environment_id, channel, provider_type, config_enc, from_address, enabled, created_at, updated_at FROM notification_configs
WHERE provider_id = $1 AND environment_id = $2
ORDER BY channel
`

type ListNotificationConfigsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListNotificationConfigs(ctx context.Context, arg ListNotificationConfigsParams) ([]NotificationConfig, error) {
	rows, err := q.db.Query(ctx, listNotificationConfigs, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationConfig
	for rows.Next() {
		var i NotificationConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Channel,
			&i.ProviderType,
			&i.ConfigEnc,
			&i.FromAddress,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationConfigCiphertext = `-- name: UpdateNotificationConfigCiphertext :exec
UPDATE notification_configs SET config_enc = $2, updated_at = now()
WHERE id = $1
`

type UpdateNotificationConfigCiphertextParams struct {
	ID        uuid.UUID `json:"id"`
	ConfigEnc []byte    `json:"config_enc"`
}

func (q *Queries) UpdateNotificationConfigCiphertext(ctx context.Context, arg UpdateNotificationConfigCiphertextParams) error {
	_, err := q.db.Exec(ctx, updateNotificationConfigCiphertext, arg.ID, arg.ConfigEnc)
	return err
}

const upsertNotificationConfig = `-- name: UpsertNotificationConfig :one
INSERT INTO notification_configs (provider_id, environment_id, channel, provider_type, config_enc, from_address, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider_id, environment_id, channel) DO UPDATE
SET provider_type = EXCLUDED.provider_type, config_enc = EXCLUDED.config_enc,
    from_address = EXCLUDED.from_address, enabled = EXCLUDED.enabled, updated_at = now()
RETURNING id, provider_id, environment_id, channel, provider_type, config_enc, from_address, enabled, created_at, updated_at
`

type UpsertNotificationConfigParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Channel       string    `json:"channel"`
	ProviderType  string    `json:"provider_type"`
	ConfigEnc     []byte    `json:"config_enc"`
	FromAddress   string    `json:"from_address"`
	Enabled       bool      `json:"enabled"`
}

func (q *Queries) UpsertNotificationConfig(ctx context.Context, arg UpsertNotificationConfigParams) (NotificationConfig, error) {
	row := q.db.QueryRow(ctx, upsertNotificationConfig,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Channel,
		arg.ProviderType,
		arg.ConfigEnc,
		arg.FromAddress,
		arg.Enabled,
	)
	var i NotificationConfig
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Channel,
		&i.ProviderType,
		&i.ConfigEnc,
		&i.FromAddress,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
