// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: outbox.sql

package storegen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const claimDueOutboxEvents = `-- name: ClaimDueOutboxEvents :many
UPDATE outbox_events
SET next_attempt_at = now() + interval '120 seconds'
WHERE id IN (
    SELECT id FROM outbox_events
    WHERE (status = 'pending' AND (next_attempt_at IS NULL OR next_attempt_at <= now()))
       OR (status = 'failed' AND next_attempt_at IS NOT NULL AND next_attempt_at <= now())
    ORDER BY created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id, status, attempts, created_at, published_at, next_attempt_at
`

// Atomically claims and leases a batch: sets next_attempt_at 120s ahead so
// concurrent relay instances skip these rows (SKIP LOCKED + lease). The
// caller delivers events OUTSIDE this transaction and then marks each
// event's outcome (published / retry / dead-letter) in a separate short
// transaction. If the relay crashes, the 120s lease expires and another
// instance re-claims — at-least-once delivery.
func (q *Queries) ClaimDueOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimDueOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.PayloadHash,
			&i.TransactionID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox_events (provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id, status, attempts, created_at, published_at, next_attempt_at
`

type InsertOutboxEventParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	PayloadHash   string    `json:"payload_hash"`
	TransactionID string    `json:"transaction_id"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.PayloadHash,
		arg.TransactionID,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.PayloadHash,
		&i.TransactionID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const insertOutboxEventIdempotent = `-- name: InsertOutboxEventIdempotent :exec
INSERT INTO outbox_events (provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (provider_id, environment_id, transaction_id) DO NOTHING
`

type InsertOutboxEventIdempotentParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	PayloadHash   string    `json:"payload_hash"`
	TransactionID string    `json:"transaction_id"`
}

func (q *Queries) InsertOutboxEventIdempotent(ctx context.Context, arg InsertOutboxEventIdempotentParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEventIdempotent,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.PayloadHash,
		arg.TransactionID,
	)
	return err
}

const listOutboxEventsByTenant = `-- name: ListOutboxEventsByTenant :many
SELECT id, provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id, status, attempts, created_at, published_at, next_attempt_at FROM outbox_events
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListOutboxEventsByTenantParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListOutboxEventsByTenant(ctx context.Context, arg ListOutboxEventsByTenantParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listOutboxEventsByTenant, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.PayloadHash,
			&i.TransactionID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventDeadLetter = `-- name: MarkOutboxEventDeadLetter :exec
UPDATE outbox_events SET status = 'failed', attempts = attempts + 1, next_attempt_at = NULL WHERE id = $1
`

func (q *Queries) MarkOutboxEventDeadLetter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventDeadLetter, id)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events SET status = 'failed', attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, id)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events SET status = 'published', published_at = now(), next_attempt_at = NULL WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const markOutboxEventRetry = `-- name: MarkOutboxEventRetry :exec
UPDATE outbox_events SET status = 'failed', attempts = attempts + 1, next_attempt_at = $2 WHERE id = $1
`

type MarkOutboxEventRetryParams struct {
	ID            uuid.UUID  `json:"id"`
	NextAttemptAt *time.Time `json:"next_attempt_at"`
}

func (q *Queries) MarkOutboxEventRetry(ctx context.Context, arg MarkOutboxEventRetryParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventRetry, arg.ID, arg.NextAttemptAt)
	return err
}
