// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: outbox.sql

package storegen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueOutboxEvents = `-- name: ClaimDueOutboxEvents :many
UPDATE outbox_events
SET next_attempt_at = now() + interval '120 seconds'
WHERE id IN (
    SELECT id FROM outbox_events
    WHERE (status = 'pending' AND (next_attempt_at IS NULL OR next_attempt_at <= now()))
       OR (status = 'failed' AND next_attempt_at IS NOT NULL AND next_attempt_at <= now())
    ORDER BY created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id, status, attempts, created_at, published_at, next_attempt_at, last_error
`

// Atomically claims and leases a batch: sets next_attempt_at 120s ahead so
// concurrent relay instances skip these rows (SKIP LOCKED + lease). The
// caller delivers events OUTSIDE this transaction and then marks each
// event's outcome (published / retry / dead-letter) in a separate short
// transaction. If the relay crashes, the 120s lease expires and another
// instance re-claims — at-least-once delivery. Terminal dead-lettered rows
// (status='dead_letter') are never claimed.
func (q *Queries) ClaimDueOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimDueOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.PayloadHash,
			&i.TransactionID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.NextAttemptAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOutboxEventsByStatus = `-- name: CountOutboxEventsByStatus :many
SELECT status, COUNT(*)::bigint AS count
FROM outbox_events
GROUP BY status
`

type CountOutboxEventsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Backlog gauge for Prometheus: total outbox_events rows grouped by
// delivery status (pending / failed / published / dead_letter). Refreshed
// periodically by the metrics backlog reporter.
func (q *Queries) CountOutboxEventsByStatus(ctx context.Context) ([]CountOutboxEventsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countOutboxEventsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOutboxEventsByStatusRow
	for rows.Next() {
		var i CountOutboxEventsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnconfirmedOutbox = `-- name: CountUnconfirmedOutbox :one
SELECT COUNT(*) FROM outbox_events
WHERE provider_id = $1 AND status IN ('pending', 'failed')
`

// Counts outbox events that are pending or failed (not yet delivered)
// for a provider. Used by CompleteFailover to report replay counts
// (spec Section 14: "切换后重放未确认 Outbox"). Dead-lettered events are
// terminal and deliberately excluded from replay.
func (q *Queries) CountUnconfirmedOutbox(ctx context.Context, providerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnconfirmedOutbox, providerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredOutboxEvents = `-- name: DeleteExpiredOutboxEvents :execrows
DELETE FROM outbox_events
WHERE created_at < $1
  AND (status = 'published'
    OR status = 'dead_letter'
    OR (status = 'failed' AND next_attempt_at IS NULL))
`

// Retention policy: delete outbox events that have left the delivery pipeline
// (published, or terminal dead-lettered, or failed with retries exhausted —
// next_attempt_at NULL) older than the retention cutoff. Pending events and
// failed events still inside their retry window (next_attempt_at set) are never
// deleted: the relay may still claim and deliver them. Terminal webhook
// deliveries referencing these events are swept first by
// DeleteExpiredWebhookDeliveries.
func (q *Queries) DeleteExpiredOutboxEvents(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOutboxEvents, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox_events (provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id, status, attempts, created_at, published_at, next_attempt_at, last_error
`

type InsertOutboxEventParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	PayloadHash   string    `json:"payload_hash"`
	TransactionID string    `json:"transaction_id"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.PayloadHash,
		arg.TransactionID,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.PayloadHash,
		&i.TransactionID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.NextAttemptAt,
		&i.LastError,
	)
	return i, err
}

const insertOutboxEventIdempotent = `-- name: InsertOutboxEventIdempotent :exec
INSERT INTO outbox_events (provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (provider_id, environment_id, transaction_id) DO NOTHING
`

type InsertOutboxEventIdempotentParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	PayloadHash   string    `json:"payload_hash"`
	TransactionID string    `json:"transaction_id"`
}

func (q *Queries) InsertOutboxEventIdempotent(ctx context.Context, arg InsertOutboxEventIdempotentParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEventIdempotent,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.PayloadHash,
		arg.TransactionID,
	)
	return err
}

const listOutboxEventsByTenant = `-- name: ListOutboxEventsByTenant :many
SELECT id, provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id, status, attempts, created_at, published_at, next_attempt_at, last_error FROM outbox_events
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListOutboxEventsByTenantParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListOutboxEventsByTenant(ctx context.Context, arg ListOutboxEventsByTenantParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listOutboxEventsByTenant, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.PayloadHash,
			&i.TransactionID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.NextAttemptAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxEventsFiltered = `-- name: ListOutboxEventsFiltered :many
SELECT id, provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id, status, attempts, created_at, published_at, next_attempt_at, last_error FROM outbox_events
WHERE ($1::text = '' OR status = $1)
ORDER BY created_at DESC, id DESC
LIMIT $2::int
`

type ListOutboxEventsFilteredParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
}

// Operator queue board: recent events across all providers, optional status filter.
func (q *Queries) ListOutboxEventsFiltered(ctx context.Context, arg ListOutboxEventsFilteredParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listOutboxEventsFiltered, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.PayloadHash,
			&i.TransactionID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.NextAttemptAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventDeadLetter = `-- name: MarkOutboxEventDeadLetter :exec
UPDATE outbox_events
SET status = 'dead_letter',
    attempts = attempts + 1,
    next_attempt_at = NULL,
    last_error = $2
WHERE id = $1
`

type MarkOutboxEventDeadLetterParams struct {
	ID        uuid.UUID   `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

// Terminal failure: permanently fails an event (max attempts reached or an
// unparseable payload). status='dead_letter' is a true terminal state — the
// relay never re-claims dead-lettered rows (see ClaimDueOutboxEvents) and the
// reconciliation check CountDeadLetterOutbox surfaces them. last_error records
// the final failure cause for operator visibility.
func (q *Queries) MarkOutboxEventDeadLetter(ctx context.Context, arg MarkOutboxEventDeadLetterParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventDeadLetter, arg.ID, arg.LastError)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events SET status = 'failed', attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, id)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events SET status = 'published', published_at = now(), next_attempt_at = NULL WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const markOutboxEventRetry = `-- name: MarkOutboxEventRetry :exec
UPDATE outbox_events SET status = 'failed', attempts = attempts + 1, next_attempt_at = $2 WHERE id = $1
`

type MarkOutboxEventRetryParams struct {
	ID            uuid.UUID  `json:"id"`
	NextAttemptAt *time.Time `json:"next_attempt_at"`
}

func (q *Queries) MarkOutboxEventRetry(ctx context.Context, arg MarkOutboxEventRetryParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventRetry, arg.ID, arg.NextAttemptAt)
	return err
}

const streamOutboxEvents = `-- name: StreamOutboxEvents :many
SELECT oe.id, oe.provider_id, oe.environment_id, oe.aggregate_type, oe.aggregate_id, oe.event_type, oe.payload, oe.payload_hash, oe.transaction_id, oe.status, oe.attempts, oe.created_at, oe.published_at, oe.next_attempt_at, oe.last_error FROM outbox_events oe
WHERE oe.provider_id = $1 AND oe.environment_id = $2
    AND ($3::uuid = '00000000-0000-0000-0000-000000000000' OR (oe.created_at, oe.id) > (
        SELECT oe2.created_at, oe2.id FROM outbox_events oe2 WHERE oe2.id = $3
    ))
    AND ($4::text = '' OR oe.event_type = $4)
    AND ($5::text = '' OR oe.aggregate_type = $5)
ORDER BY oe.created_at ASC, oe.id ASC
LIMIT $6
`

type StreamOutboxEventsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Column3       uuid.UUID `json:"column_3"`
	Column4       string    `json:"column_4"`
	Column5       string    `json:"column_5"`
	Limit         int32     `json:"limit"`
}

// Cursor-based forward pagination for the Enterprise Event Stream API.
// The cursor is the last event ID the consumer processed. Uses tuple
// comparison (created_at, id) to handle same-timestamp events within a
// single transaction correctly. Optional filters by event_type and
// aggregate_type allow consumers to subscribe to specific event categories.
// Pass uuid.Nil (all-zeros) as the cursor to start from the beginning.
// Pass empty strings for event_type/aggregate_type to skip filtering.
func (q *Queries) StreamOutboxEvents(ctx context.Context, arg StreamOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, streamOutboxEvents,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.PayloadHash,
			&i.TransactionID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.NextAttemptAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
