// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: providers.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (slug, name, home_region_id, cell_id, lifecycle_state)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, name, home_region_id, cell_id, lifecycle_state, sla_tier, created_at, updated_at
`

type CreateProviderParams struct {
	Slug           string        `json:"slug"`
	Name           string        `json:"name"`
	HomeRegionID   uuid.UUID     `json:"home_region_id"`
	CellID         uuid.NullUUID `json:"cell_id"`
	LifecycleState string        `json:"lifecycle_state"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Slug,
		arg.Name,
		arg.HomeRegionID,
		arg.CellID,
		arg.LifecycleState,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HomeRegionID,
		&i.CellID,
		&i.LifecycleState,
		&i.SlaTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, slug, name, home_region_id, cell_id, lifecycle_state, sla_tier, created_at, updated_at FROM providers WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HomeRegionID,
		&i.CellID,
		&i.LifecycleState,
		&i.SlaTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, slug, name, home_region_id, cell_id, lifecycle_state, sla_tier, created_at, updated_at FROM providers ORDER BY created_at DESC
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.HomeRegionID,
			&i.CellID,
			&i.LifecycleState,
			&i.SlaTier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderCell = `-- name: UpdateProviderCell :exec
UPDATE providers SET cell_id = $2, updated_at = now() WHERE id = $1
`

type UpdateProviderCellParams struct {
	ID     uuid.UUID     `json:"id"`
	CellID uuid.NullUUID `json:"cell_id"`
}

func (q *Queries) UpdateProviderCell(ctx context.Context, arg UpdateProviderCellParams) error {
	_, err := q.db.Exec(ctx, updateProviderCell, arg.ID, arg.CellID)
	return err
}

const updateProviderLifecycle = `-- name: UpdateProviderLifecycle :one
UPDATE providers
SET lifecycle_state = $2, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, home_region_id, cell_id, lifecycle_state, sla_tier, created_at, updated_at
`

type UpdateProviderLifecycleParams struct {
	ID             uuid.UUID `json:"id"`
	LifecycleState string    `json:"lifecycle_state"`
}

func (q *Queries) UpdateProviderLifecycle(ctx context.Context, arg UpdateProviderLifecycleParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderLifecycle, arg.ID, arg.LifecycleState)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HomeRegionID,
		&i.CellID,
		&i.LifecycleState,
		&i.SlaTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
