// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: psp.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPSPCredentialsByType = `-- name: CountPSPCredentialsByType :one
SELECT count(*)::bigint FROM psp_credentials
WHERE provider_id = $1 AND environment_id = $2 AND psp_type = $3 AND active = true
`

type CountPSPCredentialsByTypeParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	PspType       string    `json:"psp_type"`
}

func (q *Queries) CountPSPCredentialsByType(ctx context.Context, arg CountPSPCredentialsByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPSPCredentialsByType, arg.ProviderID, arg.EnvironmentID, arg.PspType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPSPCredential = `-- name: CreatePSPCredential :one
INSERT INTO psp_credentials (
    provider_id, environment_id, psp_type, label,
    encrypted_api_key, encrypted_webhook_secret, key_version
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider_id, environment_id, psp_type, label, encrypted_api_key, encrypted_webhook_secret, key_version, active, created_at, rotated_at, revoked_at
`

type CreatePSPCredentialParams struct {
	ProviderID             uuid.UUID   `json:"provider_id"`
	EnvironmentID          uuid.UUID   `json:"environment_id"`
	PspType                string      `json:"psp_type"`
	Label                  string      `json:"label"`
	EncryptedApiKey        string      `json:"encrypted_api_key"`
	EncryptedWebhookSecret pgtype.Text `json:"encrypted_webhook_secret"`
	KeyVersion             int32       `json:"key_version"`
}

func (q *Queries) CreatePSPCredential(ctx context.Context, arg CreatePSPCredentialParams) (PspCredential, error) {
	row := q.db.QueryRow(ctx, createPSPCredential,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.PspType,
		arg.Label,
		arg.EncryptedApiKey,
		arg.EncryptedWebhookSecret,
		arg.KeyVersion,
	)
	var i PspCredential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.PspType,
		&i.Label,
		&i.EncryptedApiKey,
		&i.EncryptedWebhookSecret,
		&i.KeyVersion,
		&i.Active,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActivePSPByType = `-- name: GetActivePSPByType :one
SELECT id, provider_id, environment_id, psp_type, label, encrypted_api_key, encrypted_webhook_secret, key_version, active, created_at, rotated_at, revoked_at FROM psp_credentials
WHERE provider_id = $1 AND environment_id = $2 AND psp_type = $3 AND active = true
`

type GetActivePSPByTypeParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	PspType       string    `json:"psp_type"`
}

func (q *Queries) GetActivePSPByType(ctx context.Context, arg GetActivePSPByTypeParams) (PspCredential, error) {
	row := q.db.QueryRow(ctx, getActivePSPByType, arg.ProviderID, arg.EnvironmentID, arg.PspType)
	var i PspCredential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.PspType,
		&i.Label,
		&i.EncryptedApiKey,
		&i.EncryptedWebhookSecret,
		&i.KeyVersion,
		&i.Active,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPSPCredentialByID = `-- name: GetPSPCredentialByID :one
SELECT id, provider_id, environment_id, psp_type, label, encrypted_api_key, encrypted_webhook_secret, key_version, active, created_at, rotated_at, revoked_at FROM psp_credentials
WHERE id = $1 AND provider_id = $2 AND environment_id = $3
`

type GetPSPCredentialByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) GetPSPCredentialByID(ctx context.Context, arg GetPSPCredentialByIDParams) (PspCredential, error) {
	row := q.db.QueryRow(ctx, getPSPCredentialByID, arg.ID, arg.ProviderID, arg.EnvironmentID)
	var i PspCredential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.PspType,
		&i.Label,
		&i.EncryptedApiKey,
		&i.EncryptedWebhookSecret,
		&i.KeyVersion,
		&i.Active,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAllPSPCredentialCiphertexts = `-- name: ListAllPSPCredentialCiphertexts :many
SELECT id, encrypted_api_key, encrypted_webhook_secret FROM psp_credentials
ORDER BY id
LIMIT $1
`

type ListAllPSPCredentialCiphertextsRow struct {
	ID                     uuid.UUID   `json:"id"`
	EncryptedApiKey        string      `json:"encrypted_api_key"`
	EncryptedWebhookSecret pgtype.Text `json:"encrypted_webhook_secret"`
}

// Operator-only view used by the re-encryption worker: every row's encrypted
// fields across all tenants, so ciphertext sealed under a rotated-out master
// key can be re-sealed with the active key.
func (q *Queries) ListAllPSPCredentialCiphertexts(ctx context.Context, limit int32) ([]ListAllPSPCredentialCiphertextsRow, error) {
	rows, err := q.db.Query(ctx, listAllPSPCredentialCiphertexts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPSPCredentialCiphertextsRow
	for rows.Next() {
		var i ListAllPSPCredentialCiphertextsRow
		if err := rows.Scan(&i.ID, &i.EncryptedApiKey, &i.EncryptedWebhookSecret); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPSPCredentials = `-- name: ListPSPCredentials :many
SELECT id, provider_id, environment_id, psp_type, label, encrypted_api_key, encrypted_webhook_secret, key_version, active, created_at, rotated_at, revoked_at FROM psp_credentials
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
`

type ListPSPCredentialsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListPSPCredentials(ctx context.Context, arg ListPSPCredentialsParams) ([]PspCredential, error) {
	rows, err := q.db.Query(ctx, listPSPCredentials, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PspCredential
	for rows.Next() {
		var i PspCredential
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.PspType,
			&i.Label,
			&i.EncryptedApiKey,
			&i.EncryptedWebhookSecret,
			&i.KeyVersion,
			&i.Active,
			&i.CreatedAt,
			&i.RotatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePSPCredential = `-- name: RevokePSPCredential :exec
UPDATE psp_credentials SET active = false, revoked_at = now()
WHERE id = $1 AND provider_id = $2 AND environment_id = $3
`

type RevokePSPCredentialParams struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) RevokePSPCredential(ctx context.Context, arg RevokePSPCredentialParams) error {
	_, err := q.db.Exec(ctx, revokePSPCredential, arg.ID, arg.ProviderID, arg.EnvironmentID)
	return err
}

const updatePSPCredentialCiphertexts = `-- name: UpdatePSPCredentialCiphertexts :exec
UPDATE psp_credentials
SET encrypted_api_key = $2, encrypted_webhook_secret = NULLIF($3, '')
WHERE id = $1
`

type UpdatePSPCredentialCiphertextsParams struct {
	ID              uuid.UUID   `json:"id"`
	EncryptedApiKey string      `json:"encrypted_api_key"`
	Column3         interface{} `json:"column_3"`
}

// NULLIF keeps NULL webhook secrets NULL: sqlc reads a NULL as "" so a
// re-write must map "" back to NULL to stay byte-identical otherwise.
func (q *Queries) UpdatePSPCredentialCiphertexts(ctx context.Context, arg UpdatePSPCredentialCiphertextsParams) error {
	_, err := q.db.Exec(ctx, updatePSPCredentialCiphertexts, arg.ID, arg.EncryptedApiKey, arg.Column3)
	return err
}
