// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: quota.sql

package storegen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const commitQuotaReservation = `-- name: CommitQuotaReservation :one
UPDATE quota_reservations
SET status = 'committed', committed_at = now()
WHERE id = $1 AND status = 'reserved'
RETURNING id, provider_id, environment_id, subscription_id, quota_key, amount, status, reservation_id, expires_at, created_at, committed_at, released_at
`

func (q *Queries) CommitQuotaReservation(ctx context.Context, id uuid.UUID) (QuotaReservation, error) {
	row := q.db.QueryRow(ctx, commitQuotaReservation, id)
	var i QuotaReservation
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SubscriptionID,
		&i.QuotaKey,
		&i.Amount,
		&i.Status,
		&i.ReservationID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const deleteQuotaLimit = `-- name: DeleteQuotaLimit :execrows
DELETE FROM quota_limits
WHERE provider_id = $1 AND environment_id = $2 AND subscription_id = $3 AND quota_key = $4
`

type DeleteQuotaLimitParams struct {
	ProviderID     uuid.UUID `json:"provider_id"`
	EnvironmentID  uuid.UUID `json:"environment_id"`
	SubscriptionID uuid.UUID `json:"subscription_id"`
	QuotaKey       string    `json:"quota_key"`
}

func (q *Queries) DeleteQuotaLimit(ctx context.Context, arg DeleteQuotaLimitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuotaLimit,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.SubscriptionID,
		arg.QuotaKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireQuotaReservations = `-- name: ExpireQuotaReservations :execrows
UPDATE quota_reservations
SET status = 'expired'
WHERE status = 'reserved' AND expires_at IS NOT NULL AND expires_at <= now()
`

func (q *Queries) ExpireQuotaReservations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireQuotaReservations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQuotaLimit = `-- name: GetQuotaLimit :one
SELECT id, provider_id, environment_id, subscription_id, quota_key, limit_value, period_type, created_at, updated_at FROM quota_limits
WHERE subscription_id = $1 AND quota_key = $2
`

type GetQuotaLimitParams struct {
	SubscriptionID uuid.UUID `json:"subscription_id"`
	QuotaKey       string    `json:"quota_key"`
}

func (q *Queries) GetQuotaLimit(ctx context.Context, arg GetQuotaLimitParams) (QuotaLimit, error) {
	row := q.db.QueryRow(ctx, getQuotaLimit, arg.SubscriptionID, arg.QuotaKey)
	var i QuotaLimit
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SubscriptionID,
		&i.QuotaKey,
		&i.LimitValue,
		&i.PeriodType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotaReservationByID = `-- name: GetQuotaReservationByID :one
SELECT id, provider_id, environment_id, subscription_id, quota_key, amount, status, reservation_id, expires_at, created_at, committed_at, released_at FROM quota_reservations WHERE id = $1
`

func (q *Queries) GetQuotaReservationByID(ctx context.Context, id uuid.UUID) (QuotaReservation, error) {
	row := q.db.QueryRow(ctx, getQuotaReservationByID, id)
	var i QuotaReservation
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SubscriptionID,
		&i.QuotaKey,
		&i.Amount,
		&i.Status,
		&i.ReservationID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getQuotaReservationByTxID = `-- name: GetQuotaReservationByTxID :one
SELECT id, provider_id, environment_id, subscription_id, quota_key, amount, status, reservation_id, expires_at, created_at, committed_at, released_at FROM quota_reservations
WHERE provider_id = $1 AND environment_id = $2 AND reservation_id = $3
`

type GetQuotaReservationByTxIDParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ReservationID string    `json:"reservation_id"`
}

func (q *Queries) GetQuotaReservationByTxID(ctx context.Context, arg GetQuotaReservationByTxIDParams) (QuotaReservation, error) {
	row := q.db.QueryRow(ctx, getQuotaReservationByTxID, arg.ProviderID, arg.EnvironmentID, arg.ReservationID)
	var i QuotaReservation
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SubscriptionID,
		&i.QuotaKey,
		&i.Amount,
		&i.Status,
		&i.ReservationID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getQuotaUsage = `-- name: GetQuotaUsage :one
SELECT
    COALESCE(SUM(CASE WHEN status = 'committed' THEN amount ELSE 0 END), 0)::bigint AS committed,
    COALESCE(SUM(CASE WHEN status = 'reserved' THEN amount ELSE 0 END), 0)::bigint AS reserved
FROM quota_reservations
WHERE subscription_id = $1 AND quota_key = $2
    AND status IN ('reserved', 'committed')
`

type GetQuotaUsageParams struct {
	SubscriptionID uuid.UUID `json:"subscription_id"`
	QuotaKey       string    `json:"quota_key"`
}

type GetQuotaUsageRow struct {
	Committed int64 `json:"committed"`
	Reserved  int64 `json:"reserved"`
}

func (q *Queries) GetQuotaUsage(ctx context.Context, arg GetQuotaUsageParams) (GetQuotaUsageRow, error) {
	row := q.db.QueryRow(ctx, getQuotaUsage, arg.SubscriptionID, arg.QuotaKey)
	var i GetQuotaUsageRow
	err := row.Scan(&i.Committed, &i.Reserved)
	return i, err
}

const listQuotaLimitsBySubscription = `-- name: ListQuotaLimitsBySubscription :many
SELECT id, provider_id, environment_id, subscription_id, quota_key, limit_value, period_type, created_at, updated_at FROM quota_limits
WHERE provider_id = $1 AND environment_id = $2 AND subscription_id = $3
ORDER BY quota_key
`

type ListQuotaLimitsBySubscriptionParams struct {
	ProviderID     uuid.UUID `json:"provider_id"`
	EnvironmentID  uuid.UUID `json:"environment_id"`
	SubscriptionID uuid.UUID `json:"subscription_id"`
}

func (q *Queries) ListQuotaLimitsBySubscription(ctx context.Context, arg ListQuotaLimitsBySubscriptionParams) ([]QuotaLimit, error) {
	rows, err := q.db.Query(ctx, listQuotaLimitsBySubscription, arg.ProviderID, arg.EnvironmentID, arg.SubscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaLimit
	for rows.Next() {
		var i QuotaLimit
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.SubscriptionID,
			&i.QuotaKey,
			&i.LimitValue,
			&i.PeriodType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotaReservationsBySubscription = `-- name: ListQuotaReservationsBySubscription :many
SELECT id, provider_id, environment_id, subscription_id, quota_key, amount, status, reservation_id, expires_at, created_at, committed_at, released_at FROM quota_reservations
WHERE provider_id = $1 AND environment_id = $2 AND subscription_id = $3
    AND status IN ('reserved', 'committed')
ORDER BY created_at DESC
LIMIT $4
`

type ListQuotaReservationsBySubscriptionParams struct {
	ProviderID     uuid.UUID `json:"provider_id"`
	EnvironmentID  uuid.UUID `json:"environment_id"`
	SubscriptionID uuid.UUID `json:"subscription_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListQuotaReservationsBySubscription(ctx context.Context, arg ListQuotaReservationsBySubscriptionParams) ([]QuotaReservation, error) {
	rows, err := q.db.Query(ctx, listQuotaReservationsBySubscription,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.SubscriptionID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaReservation
	for rows.Next() {
		var i QuotaReservation
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.SubscriptionID,
			&i.QuotaKey,
			&i.Amount,
			&i.Status,
			&i.ReservationID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.CommittedAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseQuotaReservation = `-- name: ReleaseQuotaReservation :one
UPDATE quota_reservations
SET status = 'released', released_at = now()
WHERE id = $1 AND status = 'reserved'
RETURNING id, provider_id, environment_id, subscription_id, quota_key, amount, status, reservation_id, expires_at, created_at, committed_at, released_at
`

func (q *Queries) ReleaseQuotaReservation(ctx context.Context, id uuid.UUID) (QuotaReservation, error) {
	row := q.db.QueryRow(ctx, releaseQuotaReservation, id)
	var i QuotaReservation
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SubscriptionID,
		&i.QuotaKey,
		&i.Amount,
		&i.Status,
		&i.ReservationID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const reserveQuota = `-- name: ReserveQuota :one
WITH current_usage AS (
    SELECT COALESCE(SUM(amount), 0)::bigint AS total
    FROM quota_reservations
    WHERE subscription_id = $1 AND quota_key = $2
        AND status IN ('reserved', 'committed')
),
ql AS (
    SELECT limit_value FROM quota_limits
    WHERE subscription_id = $1 AND quota_key = $2
)
INSERT INTO quota_reservations (
    provider_id, environment_id, subscription_id, quota_key,
    amount, reservation_id, expires_at
)
SELECT $3, $4, $1, $2, $5, $6, $7
FROM current_usage, ql
WHERE current_usage.total + $5 <= ql.limit_value
RETURNING id, provider_id, environment_id, subscription_id, quota_key, amount, status, reservation_id, expires_at, created_at, committed_at, released_at
`

type ReserveQuotaParams struct {
	SubscriptionID uuid.UUID  `json:"subscription_id"`
	QuotaKey       string     `json:"quota_key"`
	ProviderID     uuid.UUID  `json:"provider_id"`
	EnvironmentID  uuid.UUID  `json:"environment_id"`
	Amount         int64      `json:"amount"`
	ReservationID  string     `json:"reservation_id"`
	ExpiresAt      *time.Time `json:"expires_at"`
}

// Atomic check-and-insert: the CTE computes current usage (reserved + committed)
// and only inserts if usage + amount <= limit. Returns no rows when exceeded
// (pgx.ErrNoRows → service translates to ErrQuotaExceeded).
func (q *Queries) ReserveQuota(ctx context.Context, arg ReserveQuotaParams) (QuotaReservation, error) {
	row := q.db.QueryRow(ctx, reserveQuota,
		arg.SubscriptionID,
		arg.QuotaKey,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Amount,
		arg.ReservationID,
		arg.ExpiresAt,
	)
	var i QuotaReservation
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SubscriptionID,
		&i.QuotaKey,
		&i.Amount,
		&i.Status,
		&i.ReservationID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const upsertQuotaLimit = `-- name: UpsertQuotaLimit :one
INSERT INTO quota_limits (provider_id, environment_id, subscription_id, quota_key, limit_value, period_type)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (subscription_id, quota_key) DO UPDATE
SET limit_value = EXCLUDED.limit_value, period_type = EXCLUDED.period_type, updated_at = now()
RETURNING id, provider_id, environment_id, subscription_id, quota_key, limit_value, period_type, created_at, updated_at
`

type UpsertQuotaLimitParams struct {
	ProviderID     uuid.UUID `json:"provider_id"`
	EnvironmentID  uuid.UUID `json:"environment_id"`
	SubscriptionID uuid.UUID `json:"subscription_id"`
	QuotaKey       string    `json:"quota_key"`
	LimitValue     int64     `json:"limit_value"`
	PeriodType     string    `json:"period_type"`
}

func (q *Queries) UpsertQuotaLimit(ctx context.Context, arg UpsertQuotaLimitParams) (QuotaLimit, error) {
	row := q.db.QueryRow(ctx, upsertQuotaLimit,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.SubscriptionID,
		arg.QuotaKey,
		arg.LimitValue,
		arg.PeriodType,
	)
	var i QuotaLimit
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.SubscriptionID,
		&i.QuotaKey,
		&i.LimitValue,
		&i.PeriodType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
