// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reconciliation.sql

package storegen

import (
	"context"
)

const countActiveSubsWithoutSnapshot = `-- name: CountActiveSubsWithoutSnapshot :one
SELECT count(*)::bigint FROM subscriptions s
WHERE s.status = 'active'
AND NOT EXISTS (
    SELECT 1 FROM entitlement_snapshots es
    WHERE es.subscription_id = s.id
    AND es.computed_at > now() - interval '24 hours'
)
`

func (q *Queries) CountActiveSubsWithoutSnapshot(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubsWithoutSnapshot)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countDeadLetterOutbox = `-- name: CountDeadLetterOutbox :one
SELECT count(*)::bigint FROM outbox_events WHERE status = 'dead_letter'
`

func (q *Queries) CountDeadLetterOutbox(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDeadLetterOutbox)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvoiceAmountMismatches = `-- name: CountInvoiceAmountMismatches :one
SELECT count(*)::bigint FROM invoices
WHERE status IN ('finalized', 'voided')
AND (
    sub_total_including_taxes_amount_cents <> sub_total_excluding_taxes_amount_cents + taxes_amount_cents
    OR total_amount_cents <> sub_total_including_taxes_amount_cents - credit_notes_amount_cents
    OR (invoice_type <> 'credit' AND total_amount_cents < 0)
)
`

// Finalized/voided invoices whose financial fields violate Lago's arithmetic
// invariants: sub_total_including = sub_total_excluding + taxes, and
// total = sub_total_including - credit_notes. Credit invoices carry a
// negative total, so they are excluded from the non-negative check.
func (q *Queries) CountInvoiceAmountMismatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceAmountMismatches)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvoiceLinesTotalMismatch = `-- name: CountInvoiceLinesTotalMismatch :one
SELECT count(*)::bigint FROM (
    SELECT i.id
    FROM invoices i
    JOIN invoice_lines il ON il.invoice_id = i.id
    WHERE i.status IN ('finalized', 'voided')
    GROUP BY i.id, i.total_amount_cents
    HAVING sum(il.total_amount_cents) <> i.total_amount_cents
) mismatches
`

// Finalized/voided invoices whose line totals do not sum to the invoice
// header total. Line rows are immutable once the invoice is finalized, so
// any mismatch is a financial integrity violation.
func (q *Queries) CountInvoiceLinesTotalMismatch(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceLinesTotalMismatch)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvoicesWithoutCatalogVersion = `-- name: CountInvoicesWithoutCatalogVersion :one
SELECT count(*)::bigint FROM invoices
WHERE subscription_id IS NOT NULL
AND catalog_version_id IS NULL
`

func (q *Queries) CountInvoicesWithoutCatalogVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoicesWithoutCatalogVersion)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOrphanedUsageEvents = `-- name: CountOrphanedUsageEvents :one
SELECT count(*)::bigint FROM usage_events ue
WHERE NOT EXISTS (
    SELECT 1 FROM customer_accounts ca WHERE ca.id = ue.customer_account_id
)
`

func (q *Queries) CountOrphanedUsageEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrphanedUsageEvents)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countStuckUsageOutbox = `-- name: CountStuckUsageOutbox :one
SELECT count(*)::bigint FROM outbox_events
WHERE event_type = 'usage.accepted'
AND status = 'failed'
AND (next_attempt_at IS NULL OR next_attempt_at < now() - interval '1 hour')
`

func (q *Queries) CountStuckUsageOutbox(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStuckUsageOutbox)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnpaidFinalizedOverdue = `-- name: CountUnpaidFinalizedOverdue :one
SELECT count(*)::bigint FROM invoices
WHERE status = 'finalized'
AND payment_status <> 'succeeded'
AND finalized_at IS NOT NULL
AND finalized_at < now() - interval '7 days'
`

// Finalized invoices not marked paid within 7 days. Signals collection risk
// and payment-status divergence from the Lago billing system.
func (q *Queries) CountUnpaidFinalizedOverdue(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnpaidFinalizedOverdue)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertReconciliationResult = `-- name: InsertReconciliationResult :exec
INSERT INTO reconciliation_results (check_name, status, expected_count, actual_count, drift_count, details)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertReconciliationResultParams struct {
	CheckName     string `json:"check_name"`
	Status        string `json:"status"`
	ExpectedCount int64  `json:"expected_count"`
	ActualCount   int64  `json:"actual_count"`
	DriftCount    int64  `json:"drift_count"`
	Details       []byte `json:"details"`
}

func (q *Queries) InsertReconciliationResult(ctx context.Context, arg InsertReconciliationResultParams) error {
	_, err := q.db.Exec(ctx, insertReconciliationResult,
		arg.CheckName,
		arg.Status,
		arg.ExpectedCount,
		arg.ActualCount,
		arg.DriftCount,
		arg.Details,
	)
	return err
}

const listRecentReconciliationResults = `-- name: ListRecentReconciliationResults :many
SELECT id, check_name, status, expected_count, actual_count, drift_count, details, checked_at FROM reconciliation_results ORDER BY checked_at DESC LIMIT $1
`

func (q *Queries) ListRecentReconciliationResults(ctx context.Context, limit int32) ([]ReconciliationResult, error) {
	rows, err := q.db.Query(ctx, listRecentReconciliationResults, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReconciliationResult
	for rows.Next() {
		var i ReconciliationResult
		if err := rows.Scan(
			&i.ID,
			&i.CheckName,
			&i.Status,
			&i.ExpectedCount,
			&i.ActualCount,
			&i.DriftCount,
			&i.Details,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
