// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: risk_reviews.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createProviderRiskReview = `-- name: CreateProviderRiskReview :one
INSERT INTO provider_risk_reviews (
    provider_id, risk_score, checks, decision, reason, reviewed_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, provider_id, risk_score, checks, decision, reason, reviewed_by, reviewed_at, created_at
`

type CreateProviderRiskReviewParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	RiskScore  int16     `json:"risk_score"`
	Checks     []byte    `json:"checks"`
	Decision   string    `json:"decision"`
	Reason     string    `json:"reason"`
	ReviewedBy string    `json:"reviewed_by"`
}

func (q *Queries) CreateProviderRiskReview(ctx context.Context, arg CreateProviderRiskReviewParams) (ProviderRiskReview, error) {
	row := q.db.QueryRow(ctx, createProviderRiskReview,
		arg.ProviderID,
		arg.RiskScore,
		arg.Checks,
		arg.Decision,
		arg.Reason,
		arg.ReviewedBy,
	)
	var i ProviderRiskReview
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.RiskScore,
		&i.Checks,
		&i.Decision,
		&i.Reason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const latestProviderRiskReview = `-- name: LatestProviderRiskReview :one
SELECT id, provider_id, risk_score, checks, decision, reason, reviewed_by, reviewed_at, created_at
FROM provider_risk_reviews
WHERE provider_id = $1
ORDER BY reviewed_at DESC, id DESC
LIMIT 1
`

func (q *Queries) LatestProviderRiskReview(ctx context.Context, providerID uuid.UUID) (ProviderRiskReview, error) {
	row := q.db.QueryRow(ctx, latestProviderRiskReview, providerID)
	var i ProviderRiskReview
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.RiskScore,
		&i.Checks,
		&i.Decision,
		&i.Reason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLatestProviderRiskReviews = `-- name: ListLatestProviderRiskReviews :many
SELECT DISTINCT ON (provider_id) id, provider_id, risk_score, checks, decision, reason, reviewed_by, reviewed_at, created_at
FROM provider_risk_reviews
ORDER BY provider_id, reviewed_at DESC, id DESC
`

// Operator review queue: one row per provider (newest review).
func (q *Queries) ListLatestProviderRiskReviews(ctx context.Context) ([]ProviderRiskReview, error) {
	rows, err := q.db.Query(ctx, listLatestProviderRiskReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderRiskReview
	for rows.Next() {
		var i ProviderRiskReview
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.RiskScore,
			&i.Checks,
			&i.Decision,
			&i.Reason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderRiskReviews = `-- name: ListProviderRiskReviews :many
SELECT id, provider_id, risk_score, checks, decision, reason, reviewed_by, reviewed_at, created_at
FROM provider_risk_reviews
WHERE provider_id = $1
ORDER BY reviewed_at DESC, id DESC
`

func (q *Queries) ListProviderRiskReviews(ctx context.Context, providerID uuid.UUID) ([]ProviderRiskReview, error) {
	rows, err := q.db.Query(ctx, listProviderRiskReviews, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderRiskReview
	for rows.Next() {
		var i ProviderRiskReview
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.RiskScore,
			&i.Checks,
			&i.Decision,
			&i.Reason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
