// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: scim_groups.sql

package storegen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const addSCIMGroupMember = `-- name: AddSCIMGroupMember :one
INSERT INTO scim_group_members (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT (group_id, user_id) DO NOTHING
RETURNING id, group_id, user_id, created_at
`

type AddSCIMGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) AddSCIMGroupMember(ctx context.Context, arg AddSCIMGroupMemberParams) (ScimGroupMember, error) {
	row := q.db.QueryRow(ctx, addSCIMGroupMember, arg.GroupID, arg.UserID)
	var i ScimGroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const clearSCIMGroupMembers = `-- name: ClearSCIMGroupMembers :execrows
DELETE FROM scim_group_members WHERE group_id = $1
`

func (q *Queries) ClearSCIMGroupMembers(ctx context.Context, groupID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearSCIMGroupMembers, groupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSCIMGroups = `-- name: CountSCIMGroups :one
SELECT COUNT(*) FROM scim_groups
WHERE provider_id = $1 AND environment_id = $2
`

type CountSCIMGroupsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) CountSCIMGroups(ctx context.Context, arg CountSCIMGroupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSCIMGroups, arg.ProviderID, arg.EnvironmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSCIMGroup = `-- name: CreateSCIMGroup :one
INSERT INTO scim_groups (provider_id, environment_id, external_id, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, provider_id, environment_id, external_id, display_name, created_at, updated_at
`

type CreateSCIMGroupParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ExternalID    string    `json:"external_id"`
	DisplayName   string    `json:"display_name"`
}

func (q *Queries) CreateSCIMGroup(ctx context.Context, arg CreateSCIMGroupParams) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, createSCIMGroup,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.ExternalID,
		arg.DisplayName,
	)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSCIMGroup = `-- name: DeleteSCIMGroup :execrows
DELETE FROM scim_groups
WHERE provider_id = $1 AND environment_id = $2 AND id = $3
`

type DeleteSCIMGroupParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) DeleteSCIMGroup(ctx context.Context, arg DeleteSCIMGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSCIMGroup, arg.ProviderID, arg.EnvironmentID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSCIMGroupByExternalID = `-- name: GetSCIMGroupByExternalID :one
SELECT id, provider_id, environment_id, external_id, display_name, created_at, updated_at FROM scim_groups
WHERE provider_id = $1 AND environment_id = $2 AND external_id = $3
`

type GetSCIMGroupByExternalIDParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ExternalID    string    `json:"external_id"`
}

func (q *Queries) GetSCIMGroupByExternalID(ctx context.Context, arg GetSCIMGroupByExternalIDParams) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, getSCIMGroupByExternalID, arg.ProviderID, arg.EnvironmentID, arg.ExternalID)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSCIMGroupByID = `-- name: GetSCIMGroupByID :one
SELECT id, provider_id, environment_id, external_id, display_name, created_at, updated_at FROM scim_groups WHERE id = $1
`

func (q *Queries) GetSCIMGroupByID(ctx context.Context, id uuid.UUID) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, getSCIMGroupByID, id)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSCIMGroupMembers = `-- name: ListSCIMGroupMembers :many
SELECT m.id, m.group_id, m.user_id, m.created_at, u.external_id AS user_external_id, u.display_name AS user_display_name, u.email AS user_email, u.active AS user_active
FROM scim_group_members m
JOIN scim_users u ON u.id = m.user_id
WHERE m.group_id = $1
`

type ListSCIMGroupMembersRow struct {
	ID              uuid.UUID `json:"id"`
	GroupID         uuid.UUID `json:"group_id"`
	UserID          uuid.UUID `json:"user_id"`
	CreatedAt       time.Time `json:"created_at"`
	UserExternalID  string    `json:"user_external_id"`
	UserDisplayName string    `json:"user_display_name"`
	UserEmail       string    `json:"user_email"`
	UserActive      bool      `json:"user_active"`
}

func (q *Queries) ListSCIMGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListSCIMGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listSCIMGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSCIMGroupMembersRow
	for rows.Next() {
		var i ListSCIMGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.CreatedAt,
			&i.UserExternalID,
			&i.UserDisplayName,
			&i.UserEmail,
			&i.UserActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMGroups = `-- name: ListSCIMGroups :many
SELECT id, provider_id, environment_id, external_id, display_name, created_at, updated_at FROM scim_groups
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at ASC
LIMIT $3
`

type ListSCIMGroupsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListSCIMGroups(ctx context.Context, arg ListSCIMGroupsParams) ([]ScimGroup, error) {
	rows, err := q.db.Query(ctx, listSCIMGroups, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimGroup
	for rows.Next() {
		var i ScimGroup
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.ExternalID,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchSCIMGroupDisplayName = `-- name: PatchSCIMGroupDisplayName :exec
UPDATE scim_groups SET display_name = $2, updated_at = now() WHERE id = $1
`

type PatchSCIMGroupDisplayNameParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) PatchSCIMGroupDisplayName(ctx context.Context, arg PatchSCIMGroupDisplayNameParams) error {
	_, err := q.db.Exec(ctx, patchSCIMGroupDisplayName, arg.ID, arg.DisplayName)
	return err
}

const patchSCIMUserActive = `-- name: PatchSCIMUserActive :exec
UPDATE scim_users SET active = $2, updated_at = now() WHERE id = $1
`

type PatchSCIMUserActiveParams struct {
	ID     uuid.UUID `json:"id"`
	Active bool      `json:"active"`
}

func (q *Queries) PatchSCIMUserActive(ctx context.Context, arg PatchSCIMUserActiveParams) error {
	_, err := q.db.Exec(ctx, patchSCIMUserActive, arg.ID, arg.Active)
	return err
}

const patchSCIMUserDisplayName = `-- name: PatchSCIMUserDisplayName :exec
UPDATE scim_users SET display_name = $2, updated_at = now() WHERE id = $1
`

type PatchSCIMUserDisplayNameParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) PatchSCIMUserDisplayName(ctx context.Context, arg PatchSCIMUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, patchSCIMUserDisplayName, arg.ID, arg.DisplayName)
	return err
}

const patchSCIMUserEmail = `-- name: PatchSCIMUserEmail :exec
UPDATE scim_users SET email = $2, updated_at = now() WHERE id = $1
`

type PatchSCIMUserEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) PatchSCIMUserEmail(ctx context.Context, arg PatchSCIMUserEmailParams) error {
	_, err := q.db.Exec(ctx, patchSCIMUserEmail, arg.ID, arg.Email)
	return err
}

const removeSCIMGroupMember = `-- name: RemoveSCIMGroupMember :execrows
DELETE FROM scim_group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveSCIMGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveSCIMGroupMember(ctx context.Context, arg RemoveSCIMGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSCIMGroupMember, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSCIMGroup = `-- name: UpdateSCIMGroup :one
UPDATE scim_groups
SET display_name = $2, updated_at = now()
WHERE id = $1
RETURNING id, provider_id, environment_id, external_id, display_name, created_at, updated_at
`

type UpdateSCIMGroupParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) UpdateSCIMGroup(ctx context.Context, arg UpdateSCIMGroupParams) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, updateSCIMGroup, arg.ID, arg.DisplayName)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
