// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: scim_users.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
)

const countSCIMUsers = `-- name: CountSCIMUsers :one
SELECT COUNT(*) FROM scim_users
WHERE provider_id = $1 AND environment_id = $2
`

type CountSCIMUsersParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) CountSCIMUsers(ctx context.Context, arg CountSCIMUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSCIMUsers, arg.ProviderID, arg.EnvironmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSCIMUser = `-- name: CreateSCIMUser :one
INSERT INTO scim_users (provider_id, environment_id, external_id, display_name, email, active, customer_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider_id, environment_id, external_id, display_name, email, active, customer_id, created_at, updated_at
`

type CreateSCIMUserParams struct {
	ProviderID    uuid.UUID     `json:"provider_id"`
	EnvironmentID uuid.UUID     `json:"environment_id"`
	ExternalID    string        `json:"external_id"`
	DisplayName   string        `json:"display_name"`
	Email         string        `json:"email"`
	Active        bool          `json:"active"`
	CustomerID    uuid.NullUUID `json:"customer_id"`
}

func (q *Queries) CreateSCIMUser(ctx context.Context, arg CreateSCIMUserParams) (ScimUser, error) {
	row := q.db.QueryRow(ctx, createSCIMUser,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.ExternalID,
		arg.DisplayName,
		arg.Email,
		arg.Active,
		arg.CustomerID,
	)
	var i ScimUser
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.DisplayName,
		&i.Email,
		&i.Active,
		&i.CustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSCIMUser = `-- name: DeleteSCIMUser :execrows
DELETE FROM scim_users
WHERE provider_id = $1 AND environment_id = $2 AND id = $3
`

type DeleteSCIMUserParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) DeleteSCIMUser(ctx context.Context, arg DeleteSCIMUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSCIMUser, arg.ProviderID, arg.EnvironmentID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSCIMUserByExternalID = `-- name: GetSCIMUserByExternalID :one
SELECT id, provider_id, environment_id, external_id, display_name, email, active, customer_id, created_at, updated_at FROM scim_users
WHERE provider_id = $1 AND environment_id = $2 AND external_id = $3
`

type GetSCIMUserByExternalIDParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ExternalID    string    `json:"external_id"`
}

func (q *Queries) GetSCIMUserByExternalID(ctx context.Context, arg GetSCIMUserByExternalIDParams) (ScimUser, error) {
	row := q.db.QueryRow(ctx, getSCIMUserByExternalID, arg.ProviderID, arg.EnvironmentID, arg.ExternalID)
	var i ScimUser
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.DisplayName,
		&i.Email,
		&i.Active,
		&i.CustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSCIMUserByID = `-- name: GetSCIMUserByID :one
SELECT id, provider_id, environment_id, external_id, display_name, email, active, customer_id, created_at, updated_at FROM scim_users WHERE id = $1
`

func (q *Queries) GetSCIMUserByID(ctx context.Context, id uuid.UUID) (ScimUser, error) {
	row := q.db.QueryRow(ctx, getSCIMUserByID, id)
	var i ScimUser
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.DisplayName,
		&i.Email,
		&i.Active,
		&i.CustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSCIMUsers = `-- name: ListSCIMUsers :many
SELECT id, provider_id, environment_id, external_id, display_name, email, active, customer_id, created_at, updated_at FROM scim_users
WHERE provider_id = $1 AND environment_id = $2
    AND ($3::int = 2 OR active = ($3::int = 1))
ORDER BY created_at ASC
LIMIT $4
`

type ListSCIMUsersParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Column3       int32     `json:"column_3"`
	Limit         int32     `json:"limit"`
}

// activeFilter: 0 = inactive only, 1 = active only, 2 = all.
func (q *Queries) ListSCIMUsers(ctx context.Context, arg ListSCIMUsersParams) ([]ScimUser, error) {
	rows, err := q.db.Query(ctx, listSCIMUsers,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimUser
	for rows.Next() {
		var i ScimUser
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.ExternalID,
			&i.DisplayName,
			&i.Email,
			&i.Active,
			&i.CustomerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSCIMUserCustomer = `-- name: SetSCIMUserCustomer :exec
UPDATE scim_users SET customer_id = $2, updated_at = now() WHERE id = $1
`

type SetSCIMUserCustomerParams struct {
	ID         uuid.UUID     `json:"id"`
	CustomerID uuid.NullUUID `json:"customer_id"`
}

func (q *Queries) SetSCIMUserCustomer(ctx context.Context, arg SetSCIMUserCustomerParams) error {
	_, err := q.db.Exec(ctx, setSCIMUserCustomer, arg.ID, arg.CustomerID)
	return err
}

const updateSCIMUser = `-- name: UpdateSCIMUser :one
UPDATE scim_users
SET display_name = $2, email = $3, active = $4, updated_at = now()
WHERE id = $1
RETURNING id, provider_id, environment_id, external_id, display_name, email, active, customer_id, created_at, updated_at
`

type UpdateSCIMUserParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	Email       string    `json:"email"`
	Active      bool      `json:"active"`
}

func (q *Queries) UpdateSCIMUser(ctx context.Context, arg UpdateSCIMUserParams) (ScimUser, error) {
	row := q.db.QueryRow(ctx, updateSCIMUser,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.Active,
	)
	var i ScimUser
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.ExternalID,
		&i.DisplayName,
		&i.Email,
		&i.Active,
		&i.CustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
