// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sla_tiers.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createSLATier = `-- name: CreateSLATier :one
INSERT INTO sla_tiers (provider_id, environment_id, code, name, uptime_sla, priority_level, reserved_capacity)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider_id, environment_id, code, name, uptime_sla, priority_level, reserved_capacity, created_at, updated_at
`

type CreateSLATierParams struct {
	ProviderID       uuid.UUID `json:"provider_id"`
	EnvironmentID    uuid.UUID `json:"environment_id"`
	Code             string    `json:"code"`
	Name             string    `json:"name"`
	UptimeSla        float64   `json:"uptime_sla"`
	PriorityLevel    int32     `json:"priority_level"`
	ReservedCapacity []byte    `json:"reserved_capacity"`
}

func (q *Queries) CreateSLATier(ctx context.Context, arg CreateSLATierParams) (SlaTier, error) {
	row := q.db.QueryRow(ctx, createSLATier,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Code,
		arg.Name,
		arg.UptimeSla,
		arg.PriorityLevel,
		arg.ReservedCapacity,
	)
	var i SlaTier
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Code,
		&i.Name,
		&i.UptimeSla,
		&i.PriorityLevel,
		&i.ReservedCapacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSLATier = `-- name: DeleteSLATier :execrows
DELETE FROM sla_tiers
WHERE provider_id = $1 AND environment_id = $2 AND id = $3
`

type DeleteSLATierParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) DeleteSLATier(ctx context.Context, arg DeleteSLATierParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSLATier, arg.ProviderID, arg.EnvironmentID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSLATierByCode = `-- name: GetSLATierByCode :one
SELECT id, provider_id, environment_id, code, name, uptime_sla, priority_level, reserved_capacity, created_at, updated_at FROM sla_tiers
WHERE provider_id = $1 AND environment_id = $2 AND code = $3
`

type GetSLATierByCodeParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Code          string    `json:"code"`
}

func (q *Queries) GetSLATierByCode(ctx context.Context, arg GetSLATierByCodeParams) (SlaTier, error) {
	row := q.db.QueryRow(ctx, getSLATierByCode, arg.ProviderID, arg.EnvironmentID, arg.Code)
	var i SlaTier
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Code,
		&i.Name,
		&i.UptimeSla,
		&i.PriorityLevel,
		&i.ReservedCapacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSLATierByID = `-- name: GetSLATierByID :one
SELECT id, provider_id, environment_id, code, name, uptime_sla, priority_level, reserved_capacity, created_at, updated_at FROM sla_tiers WHERE id = $1
`

func (q *Queries) GetSLATierByID(ctx context.Context, id uuid.UUID) (SlaTier, error) {
	row := q.db.QueryRow(ctx, getSLATierByID, id)
	var i SlaTier
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Code,
		&i.Name,
		&i.UptimeSla,
		&i.PriorityLevel,
		&i.ReservedCapacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSLATiers = `-- name: ListSLATiers :many
SELECT id, provider_id, environment_id, code, name, uptime_sla, priority_level, reserved_capacity, created_at, updated_at FROM sla_tiers
WHERE provider_id = $1 AND environment_id = $2
ORDER BY priority_level DESC
`

type ListSLATiersParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListSLATiers(ctx context.Context, arg ListSLATiersParams) ([]SlaTier, error) {
	rows, err := q.db.Query(ctx, listSLATiers, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaTier
	for rows.Next() {
		var i SlaTier
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Code,
			&i.Name,
			&i.UptimeSla,
			&i.PriorityLevel,
			&i.ReservedCapacity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSLATier = `-- name: UpdateSLATier :one
UPDATE sla_tiers
SET name = $2, uptime_sla = $3, priority_level = $4, reserved_capacity = $5, updated_at = now()
WHERE id = $1
RETURNING id, provider_id, environment_id, code, name, uptime_sla, priority_level, reserved_capacity, created_at, updated_at
`

type UpdateSLATierParams struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	UptimeSla        float64   `json:"uptime_sla"`
	PriorityLevel    int32     `json:"priority_level"`
	ReservedCapacity []byte    `json:"reserved_capacity"`
}

func (q *Queries) UpdateSLATier(ctx context.Context, arg UpdateSLATierParams) (SlaTier, error) {
	row := q.db.QueryRow(ctx, updateSLATier,
		arg.ID,
		arg.Name,
		arg.UptimeSla,
		arg.PriorityLevel,
		arg.ReservedCapacity,
	)
	var i SlaTier
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Code,
		&i.Name,
		&i.UptimeSla,
		&i.PriorityLevel,
		&i.ReservedCapacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
