// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: support_sessions.sql

package storegen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveEmergencySupportSession = `-- name: ApproveEmergencySupportSession :one
UPDATE support_sessions
SET status = 'active', second_approver = $2, granted_at = now(), updated_at = now()
WHERE id = $1 AND status = 'requested' AND access_type = 'emergency'
    AND approved_by IS NOT NULL AND approved_by != $2
RETURNING id, provider_id, environment_id, access_type, status, requested_by, reason, requested_scopes, approved_by, second_approver, granted_at, expires_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

type ApproveEmergencySupportSessionParams struct {
	ID             uuid.UUID   `json:"id"`
	SecondApprover pgtype.Text `json:"second_approver"`
}

// Second operator approves an emergency request. Transitions status to active.
func (q *Queries) ApproveEmergencySupportSession(ctx context.Context, arg ApproveEmergencySupportSessionParams) (SupportSession, error) {
	row := q.db.QueryRow(ctx, approveEmergencySupportSession, arg.ID, arg.SecondApprover)
	var i SupportSession
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.AccessType,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.RequestedScopes,
		&i.ApprovedBy,
		&i.SecondApprover,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const approveSupportSession = `-- name: ApproveSupportSession :one
UPDATE support_sessions
SET status = 'active', approved_by = $2, granted_at = now(), updated_at = now()
WHERE id = $1 AND status = 'requested' AND access_type = 'standard'
RETURNING id, provider_id, environment_id, access_type, status, requested_by, reason, requested_scopes, approved_by, second_approver, granted_at, expires_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

type ApproveSupportSessionParams struct {
	ID         uuid.UUID   `json:"id"`
	ApprovedBy pgtype.Text `json:"approved_by"`
}

// Provider approves a standard support request. Transitions status to active.
func (q *Queries) ApproveSupportSession(ctx context.Context, arg ApproveSupportSessionParams) (SupportSession, error) {
	row := q.db.QueryRow(ctx, approveSupportSession, arg.ID, arg.ApprovedBy)
	var i SupportSession
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.AccessType,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.RequestedScopes,
		&i.ApprovedBy,
		&i.SecondApprover,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSupportSession = `-- name: CreateSupportSession :one
INSERT INTO support_sessions (
    provider_id, environment_id, access_type, requested_by, reason, requested_scopes, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider_id, environment_id, access_type, status, requested_by, reason, requested_scopes, approved_by, second_approver, granted_at, expires_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

type CreateSupportSessionParams struct {
	ProviderID      uuid.UUID `json:"provider_id"`
	EnvironmentID   uuid.UUID `json:"environment_id"`
	AccessType      string    `json:"access_type"`
	RequestedBy     string    `json:"requested_by"`
	Reason          string    `json:"reason"`
	RequestedScopes []string  `json:"requested_scopes"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) CreateSupportSession(ctx context.Context, arg CreateSupportSessionParams) (SupportSession, error) {
	row := q.db.QueryRow(ctx, createSupportSession,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.AccessType,
		arg.RequestedBy,
		arg.Reason,
		arg.RequestedScopes,
		arg.ExpiresAt,
	)
	var i SupportSession
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.AccessType,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.RequestedScopes,
		&i.ApprovedBy,
		&i.SecondApprover,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const denySupportSession = `-- name: DenySupportSession :one
UPDATE support_sessions
SET status = 'denied', revoke_reason = $2, updated_at = now()
WHERE id = $1 AND status = 'requested'
RETURNING id, provider_id, environment_id, access_type, status, requested_by, reason, requested_scopes, approved_by, second_approver, granted_at, expires_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

type DenySupportSessionParams struct {
	ID           uuid.UUID   `json:"id"`
	RevokeReason pgtype.Text `json:"revoke_reason"`
}

// Provider denies a pending standard request. The deny reason is stored
// in revoke_reason (reused for both deny and revoke contexts).
func (q *Queries) DenySupportSession(ctx context.Context, arg DenySupportSessionParams) (SupportSession, error) {
	row := q.db.QueryRow(ctx, denySupportSession, arg.ID, arg.RevokeReason)
	var i SupportSession
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.AccessType,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.RequestedScopes,
		&i.ApprovedBy,
		&i.SecondApprover,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireSupportSessions = `-- name: ExpireSupportSessions :execrows
UPDATE support_sessions
SET status = 'expired', updated_at = now()
WHERE status = 'active' AND expires_at <= now()
`

// Batch-expire all sessions past their expiry. Called by the background sweeper.
func (q *Queries) ExpireSupportSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireSupportSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSupportSessionByID = `-- name: GetSupportSessionByID :one
SELECT id, provider_id, environment_id, access_type, status, requested_by, reason, requested_scopes, approved_by, second_approver, granted_at, expires_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at FROM support_sessions WHERE id = $1
`

func (q *Queries) GetSupportSessionByID(ctx context.Context, id uuid.UUID) (SupportSession, error) {
	row := q.db.QueryRow(ctx, getSupportSessionByID, id)
	var i SupportSession
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.AccessType,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.RequestedScopes,
		&i.ApprovedBy,
		&i.SecondApprover,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSupportSessions = `-- name: ListActiveSupportSessions :many
SELECT id, provider_id, environment_id, access_type, status, requested_by, reason, requested_scopes, approved_by, second_approver, granted_at, expires_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at FROM support_sessions
WHERE provider_id = $1 AND environment_id = $2 AND status = 'active'
ORDER BY granted_at DESC
`

type ListActiveSupportSessionsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListActiveSupportSessions(ctx context.Context, arg ListActiveSupportSessionsParams) ([]SupportSession, error) {
	rows, err := q.db.Query(ctx, listActiveSupportSessions, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportSession
	for rows.Next() {
		var i SupportSession
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.AccessType,
			&i.Status,
			&i.RequestedBy,
			&i.Reason,
			&i.RequestedScopes,
			&i.ApprovedBy,
			&i.SecondApprover,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportSessionsByProvider = `-- name: ListSupportSessionsByProvider :many
SELECT id, provider_id, environment_id, access_type, status, requested_by, reason, requested_scopes, approved_by, second_approver, granted_at, expires_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at FROM support_sessions
WHERE provider_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListSupportSessionsByProviderParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListSupportSessionsByProvider(ctx context.Context, arg ListSupportSessionsByProviderParams) ([]SupportSession, error) {
	rows, err := q.db.Query(ctx, listSupportSessionsByProvider, arg.ProviderID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportSession
	for rows.Next() {
		var i SupportSession
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.AccessType,
			&i.Status,
			&i.RequestedBy,
			&i.Reason,
			&i.RequestedScopes,
			&i.ApprovedBy,
			&i.SecondApprover,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportSessionsByTenant = `-- name: ListSupportSessionsByTenant :many
SELECT id, provider_id, environment_id, access_type, status, requested_by, reason, requested_scopes, approved_by, second_approver, granted_at, expires_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at FROM support_sessions
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListSupportSessionsByTenantParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListSupportSessionsByTenant(ctx context.Context, arg ListSupportSessionsByTenantParams) ([]SupportSession, error) {
	rows, err := q.db.Query(ctx, listSupportSessionsByTenant, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportSession
	for rows.Next() {
		var i SupportSession
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.AccessType,
			&i.Status,
			&i.RequestedBy,
			&i.Reason,
			&i.RequestedScopes,
			&i.ApprovedBy,
			&i.SecondApprover,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSupportSession = `-- name: RevokeSupportSession :one
UPDATE support_sessions
SET status = 'revoked', revoked_at = now(), revoked_by = $2, revoke_reason = $3, updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, provider_id, environment_id, access_type, status, requested_by, reason, requested_scopes, approved_by, second_approver, granted_at, expires_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

type RevokeSupportSessionParams struct {
	ID           uuid.UUID   `json:"id"`
	RevokedBy    pgtype.Text `json:"revoked_by"`
	RevokeReason pgtype.Text `json:"revoke_reason"`
}

// Early termination of an active session by operator or provider.
func (q *Queries) RevokeSupportSession(ctx context.Context, arg RevokeSupportSessionParams) (SupportSession, error) {
	row := q.db.QueryRow(ctx, revokeSupportSession, arg.ID, arg.RevokedBy, arg.RevokeReason)
	var i SupportSession
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.AccessType,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.RequestedScopes,
		&i.ApprovedBy,
		&i.SecondApprover,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setEmergencyFirstApprover = `-- name: SetEmergencyFirstApprover :one
UPDATE support_sessions
SET approved_by = $2, updated_at = now()
WHERE id = $1 AND status = 'requested' AND access_type = 'emergency' AND approved_by IS NULL
RETURNING id, provider_id, environment_id, access_type, status, requested_by, reason, requested_scopes, approved_by, second_approver, granted_at, expires_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

type SetEmergencyFirstApproverParams struct {
	ID         uuid.UUID   `json:"id"`
	ApprovedBy pgtype.Text `json:"approved_by"`
}

// First operator approves an emergency request (sets approved_by, status stays requested).
func (q *Queries) SetEmergencyFirstApprover(ctx context.Context, arg SetEmergencyFirstApproverParams) (SupportSession, error) {
	row := q.db.QueryRow(ctx, setEmergencyFirstApprover, arg.ID, arg.ApprovedBy)
	var i SupportSession
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.AccessType,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.RequestedScopes,
		&i.ApprovedBy,
		&i.SecondApprover,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
