// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: team_members.sql

package storegen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO team_members (
    provider_id, environment_id, email, display_name, role, status, credential_id, invited_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, provider_id, environment_id, email, display_name, role, status, credential_id, invited_by, created_at, updated_at
`

type CreateTeamMemberParams struct {
	ProviderID    uuid.UUID     `json:"provider_id"`
	EnvironmentID uuid.UUID     `json:"environment_id"`
	Email         string        `json:"email"`
	DisplayName   string        `json:"display_name"`
	Role          string        `json:"role"`
	Status        string        `json:"status"`
	CredentialID  uuid.NullUUID `json:"credential_id"`
	InvitedBy     string        `json:"invited_by"`
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, createTeamMember,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.Status,
		arg.CredentialID,
		arg.InvitedBy,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.CredentialID,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMemberByEmail = `-- name: GetTeamMemberByEmail :one
SELECT id, provider_id, environment_id, email, display_name, role, status, credential_id, invited_by, created_at, updated_at FROM team_members
WHERE provider_id = $1 AND environment_id = $2 AND email = $3
`

type GetTeamMemberByEmailParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Email         string    `json:"email"`
}

func (q *Queries) GetTeamMemberByEmail(ctx context.Context, arg GetTeamMemberByEmailParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMemberByEmail, arg.ProviderID, arg.EnvironmentID, arg.Email)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.CredentialID,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMemberByID = `-- name: GetTeamMemberByID :one
SELECT id, provider_id, environment_id, email, display_name, role, status, credential_id, invited_by, created_at, updated_at FROM team_members WHERE id = $1
`

func (q *Queries) GetTeamMemberByID(ctx context.Context, id uuid.UUID) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMemberByID, id)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.CredentialID,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTeamMembers = `-- name: ListActiveTeamMembers :many
SELECT id, provider_id, environment_id, email, display_name, role, status, credential_id, invited_by, created_at, updated_at FROM team_members
WHERE provider_id = $1 AND environment_id = $2 AND status = 'active'
ORDER BY created_at DESC
`

type ListActiveTeamMembersParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListActiveTeamMembers(ctx context.Context, arg ListActiveTeamMembersParams) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, listActiveTeamMembers, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.CredentialID,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT id, provider_id, environment_id, email, display_name, role, status, credential_id, invited_by, created_at, updated_at FROM team_members
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at DESC
`

type ListTeamMembersParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.CredentialID,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateTeamMember = `-- name: ReactivateTeamMember :one
UPDATE team_members
SET status = 'active', updated_at = now()
WHERE id = $1 AND status = 'suspended'
RETURNING id, provider_id, environment_id, email, display_name, role, status, credential_id, invited_by, created_at, updated_at
`

func (q *Queries) ReactivateTeamMember(ctx context.Context, id uuid.UUID) (TeamMember, error) {
	row := q.db.QueryRow(ctx, reactivateTeamMember, id)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.CredentialID,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeTeamMember = `-- name: RemoveTeamMember :one
UPDATE team_members
SET status = 'removed', updated_at = now()
WHERE id = $1 AND status IN ('active', 'suspended')
RETURNING id, provider_id, environment_id, email, display_name, role, status, credential_id, invited_by, created_at, updated_at
`

func (q *Queries) RemoveTeamMember(ctx context.Context, id uuid.UUID) (TeamMember, error) {
	row := q.db.QueryRow(ctx, removeTeamMember, id)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.CredentialID,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTeamMemberCredential = `-- name: SetTeamMemberCredential :exec
UPDATE team_members
SET credential_id = $2, updated_at = now()
WHERE id = $1
`

type SetTeamMemberCredentialParams struct {
	ID           uuid.UUID     `json:"id"`
	CredentialID uuid.NullUUID `json:"credential_id"`
}

func (q *Queries) SetTeamMemberCredential(ctx context.Context, arg SetTeamMemberCredentialParams) error {
	_, err := q.db.Exec(ctx, setTeamMemberCredential, arg.ID, arg.CredentialID)
	return err
}

const suspendTeamMember = `-- name: SuspendTeamMember :one
UPDATE team_members
SET status = 'suspended', updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, provider_id, environment_id, email, display_name, role, status, credential_id, invited_by, created_at, updated_at
`

func (q *Queries) SuspendTeamMember(ctx context.Context, id uuid.UUID) (TeamMember, error) {
	row := q.db.QueryRow(ctx, suspendTeamMember, id)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.CredentialID,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :one
UPDATE team_members
SET role = $2, updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, provider_id, environment_id, email, display_name, role, status, credential_id, invited_by, created_at, updated_at
`

type UpdateTeamMemberRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, updateTeamMemberRole, arg.ID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.CredentialID,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
