// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: webhooks.sql

package storegen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingWebhookDeliveries = `-- name: ClaimPendingWebhookDeliveries :many
UPDATE webhook_deliveries
SET next_attempt_at = now() + interval '60 seconds',
    attempts = attempts + 1
WHERE id IN (
    SELECT id FROM webhook_deliveries
    WHERE (status = 'pending' AND (next_attempt_at IS NULL OR next_attempt_at <= now()))
       OR (status = 'failed' AND next_attempt_at IS NOT NULL AND next_attempt_at <= now())
    ORDER BY created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, endpoint_id, outbox_event_id, provider_id, environment_id, status, attempts, response_status, response_body, next_attempt_at, delivered_at, created_at
`

func (q *Queries) ClaimPendingWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimPendingWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.OutboxEventID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Status,
			&i.Attempts,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :exec
INSERT INTO webhook_deliveries (endpoint_id, outbox_event_id, provider_id, environment_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (endpoint_id, outbox_event_id) DO NOTHING
`

type CreateWebhookDeliveryParams struct {
	EndpointID    uuid.UUID `json:"endpoint_id"`
	OutboxEventID uuid.UUID `json:"outbox_event_id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, createWebhookDelivery,
		arg.EndpointID,
		arg.OutboxEventID,
		arg.ProviderID,
		arg.EnvironmentID,
	)
	return err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (provider_id, environment_id, url, secret, enabled, events)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider_id, environment_id, url, secret, enabled, events, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Url           string    `json:"url"`
	Secret        string    `json:"secret"`
	Enabled       bool      `json:"enabled"`
	Events        []string  `json:"events"`
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.ProviderID,
		arg.EnvironmentID,
		arg.Url,
		arg.Secret,
		arg.Enabled,
		arg.Events,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Url,
		&i.Secret,
		&i.Enabled,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints
WHERE id = $1 AND provider_id = $2 AND environment_id = $3
`

type DeleteWebhookEndpointParams struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) error {
	_, err := q.db.Exec(ctx, deleteWebhookEndpoint, arg.ID, arg.ProviderID, arg.EnvironmentID)
	return err
}

const findUndeliveredOutboxEvents = `-- name: FindUndeliveredOutboxEvents :many
SELECT oe.id, oe.provider_id, oe.environment_id, oe.aggregate_type, oe.aggregate_id, oe.event_type, oe.payload, oe.payload_hash, oe.transaction_id, oe.status, oe.attempts, oe.created_at, oe.published_at, oe.next_attempt_at
FROM outbox_events oe
WHERE oe.status = 'published'
  AND NOT EXISTS (SELECT 1 FROM webhook_deliveries wd WHERE wd.outbox_event_id = oe.id)
ORDER BY oe.created_at
LIMIT $1
`

func (q *Queries) FindUndeliveredOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, findUndeliveredOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.PayloadHash,
			&i.TransactionID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutboxEventByIDForWebhook = `-- name: GetOutboxEventByIDForWebhook :one
SELECT id, provider_id, environment_id, aggregate_type, aggregate_id, event_type, payload, payload_hash, transaction_id, status, attempts, created_at, published_at, next_attempt_at FROM outbox_events
WHERE id = $1 AND provider_id = $2 AND environment_id = $3
`

type GetOutboxEventByIDForWebhookParams struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) GetOutboxEventByIDForWebhook(ctx context.Context, arg GetOutboxEventByIDForWebhookParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEventByIDForWebhook, arg.ID, arg.ProviderID, arg.EnvironmentID)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.PayloadHash,
		&i.TransactionID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const getWebhookEndpointByID = `-- name: GetWebhookEndpointByID :one
SELECT id, provider_id, environment_id, url, secret, enabled, events, created_at, updated_at FROM webhook_endpoints
WHERE id = $1 AND provider_id = $2 AND environment_id = $3
`

type GetWebhookEndpointByIDParams struct {
	ID            uuid.UUID `json:"id"`
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) GetWebhookEndpointByID(ctx context.Context, arg GetWebhookEndpointByIDParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByID, arg.ID, arg.ProviderID, arg.EnvironmentID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.EnvironmentID,
		&i.Url,
		&i.Secret,
		&i.Enabled,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledWebhooksByTenant = `-- name: ListEnabledWebhooksByTenant :many
SELECT id, provider_id, environment_id, url, secret, enabled, events, created_at, updated_at FROM webhook_endpoints
WHERE provider_id = $1 AND environment_id = $2 AND enabled = true
`

type ListEnabledWebhooksByTenantParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListEnabledWebhooksByTenant(ctx context.Context, arg ListEnabledWebhooksByTenantParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listEnabledWebhooksByTenant, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Url,
			&i.Secret,
			&i.Enabled,
			&i.Events,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByProvider = `-- name: ListWebhookDeliveriesByProvider :many
SELECT id, endpoint_id, outbox_event_id, provider_id, environment_id, status, attempts, response_status, response_body, next_attempt_at, delivered_at, created_at FROM webhook_deliveries WHERE provider_id = $1 ORDER BY created_at DESC LIMIT 200
`

func (q *Queries) ListWebhookDeliveriesByProvider(ctx context.Context, providerID uuid.UUID) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.OutboxEventID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Status,
			&i.Attempts,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByTenant = `-- name: ListWebhookDeliveriesByTenant :many
SELECT wd.id, wd.endpoint_id, wd.outbox_event_id, wd.provider_id, wd.environment_id, wd.status, wd.attempts, wd.response_status, wd.response_body, wd.next_attempt_at, wd.delivered_at, wd.created_at
FROM webhook_deliveries wd
WHERE wd.provider_id = $1 AND wd.environment_id = $2
ORDER BY wd.created_at DESC
LIMIT $3
`

type ListWebhookDeliveriesByTenantParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListWebhookDeliveriesByTenant(ctx context.Context, arg ListWebhookDeliveriesByTenantParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByTenant, arg.ProviderID, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.OutboxEventID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Status,
			&i.Attempts,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, provider_id, environment_id, url, secret, enabled, events, created_at, updated_at FROM webhook_endpoints
WHERE provider_id = $1 AND environment_id = $2
ORDER BY created_at
`

type ListWebhookEndpointsParams struct {
	ProviderID    uuid.UUID `json:"provider_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListWebhookEndpoints(ctx context.Context, arg ListWebhookEndpointsParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, arg.ProviderID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Url,
			&i.Secret,
			&i.Enabled,
			&i.Events,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpointsByProvider = `-- name: ListWebhookEndpointsByProvider :many
SELECT id, provider_id, environment_id, url, secret, enabled, events, created_at, updated_at FROM webhook_endpoints WHERE provider_id = $1 ORDER BY created_at
`

func (q *Queries) ListWebhookEndpointsByProvider(ctx context.Context, providerID uuid.UUID) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpointsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.EnvironmentID,
			&i.Url,
			&i.Secret,
			&i.Enabled,
			&i.Events,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeadLetter = `-- name: MarkWebhookDeadLetter :exec
UPDATE webhook_deliveries
SET status = 'dead_letter', response_status = $2, response_body = $3, next_attempt_at = NULL
WHERE id = $1
`

type MarkWebhookDeadLetterParams struct {
	ID             uuid.UUID   `json:"id"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ResponseBody   pgtype.Text `json:"response_body"`
}

func (q *Queries) MarkWebhookDeadLetter(ctx context.Context, arg MarkWebhookDeadLetterParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeadLetter, arg.ID, arg.ResponseStatus, arg.ResponseBody)
	return err
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :exec
UPDATE webhook_deliveries
SET status = 'delivered', response_status = $2, response_body = $3, delivered_at = now()
WHERE id = $1
`

type MarkWebhookDeliveredParams struct {
	ID             uuid.UUID   `json:"id"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ResponseBody   pgtype.Text `json:"response_body"`
}

func (q *Queries) MarkWebhookDelivered(ctx context.Context, arg MarkWebhookDeliveredParams) error {
	_, err := q.db.Exec(ctx, markWebhookDelivered, arg.ID, arg.ResponseStatus, arg.ResponseBody)
	return err
}

const markWebhookRetry = `-- name: MarkWebhookRetry :exec
UPDATE webhook_deliveries
SET status = 'failed', response_status = $2, response_body = $3, next_attempt_at = $4
WHERE id = $1
`

type MarkWebhookRetryParams struct {
	ID             uuid.UUID   `json:"id"`
	ResponseStatus pgtype.Int4 `json:"response_status"`
	ResponseBody   pgtype.Text `json:"response_body"`
	NextAttemptAt  *time.Time  `json:"next_attempt_at"`
}

func (q *Queries) MarkWebhookRetry(ctx context.Context, arg MarkWebhookRetryParams) error {
	_, err := q.db.Exec(ctx, markWebhookRetry,
		arg.ID,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.NextAttemptAt,
	)
	return err
}
