// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: workspaces.sql

package storegen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const countWorkspaceAdmins = `-- name: CountWorkspaceAdmins :one
SELECT count(*)::bigint FROM workspace_members
WHERE workspace_id = $1 AND role = 'provider_admin' AND status = 'active'
`

func (q *Queries) CountWorkspaceAdmins(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceAdmins, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createWorkspace = `-- name: CreateWorkspace :one

INSERT INTO workspaces (slug, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, slug, name, created_by, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Slug      string `json:"slug"`
	Name      string `json:"name"`
	CreatedBy string `json:"created_by"`
}

// Workspace control-plane queries (design baseline §3.1 R11).
func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Slug, arg.Name, arg.CreatedBy)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, user_sub, role)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, user_sub, role, status, created_at, updated_at
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserSub     string    `json:"user_sub"`
	Role        string    `json:"role"`
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, createWorkspaceMember, arg.WorkspaceID, arg.UserSub, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserSub,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, slug, name, created_by, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, slug, name, created_by, created_at, updated_at FROM workspaces WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT id, workspace_id, user_sub, role, status, created_at, updated_at FROM workspace_members WHERE workspace_id = $1 AND user_sub = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserSub     string    `json:"user_sub"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserSub)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserSub,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT id, workspace_id, user_sub, role, status, created_at, updated_at FROM workspace_members WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceMember, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceMember
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserSub,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT w.id, w.slug, w.name, w.created_by, w.created_at, w.updated_at, m.role AS membership_role, m.status AS membership_status
FROM workspace_members m
JOIN workspaces w ON w.id = m.workspace_id
WHERE m.user_sub = $1 AND m.status = 'active'
ORDER BY w.created_at
`

type ListWorkspacesByUserRow struct {
	ID               uuid.UUID `json:"id"`
	Slug             string    `json:"slug"`
	Name             string    `json:"name"`
	CreatedBy        string    `json:"created_by"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	MembershipRole   string    `json:"membership_role"`
	MembershipStatus string    `json:"membership_status"`
}

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userSub string) ([]ListWorkspacesByUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacesByUserRow
	for rows.Next() {
		var i ListWorkspacesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MembershipRole,
			&i.MembershipStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :exec
DELETE FROM workspace_members WHERE workspace_id = $1 AND user_sub = $2
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserSub     string    `json:"user_sub"`
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.UserSub)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces SET name = $2, slug = $3, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, created_by, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Name, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :one
UPDATE workspace_members SET role = $3, updated_at = now()
WHERE workspace_id = $1 AND user_sub = $2 AND status = 'active'
RETURNING id, workspace_id, user_sub, role, status, created_at, updated_at
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserSub     string    `json:"user_sub"`
	Role        string    `json:"role"`
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.UserSub, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserSub,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspaceMember = `-- name: UpsertWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, user_sub, role, status)
VALUES ($1, $2, $3, 'active')
ON CONFLICT (workspace_id, user_sub)
DO UPDATE SET role = EXCLUDED.role, status = 'active', updated_at = now()
RETURNING id, workspace_id, user_sub, role, status, created_at, updated_at
`

type UpsertWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserSub     string    `json:"user_sub"`
	Role        string    `json:"role"`
}

func (q *Queries) UpsertWorkspaceMember(ctx context.Context, arg UpsertWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceMember, arg.WorkspaceID, arg.UserSub, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserSub,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
